## Car Features and MSRP

### Cars dataset with features including make, model, year, engine, and other properties of the car used to predict its price

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\Lakshmeesh s reddy\Desktop\Dinku\JOB\ML-project\data car.csv")

In [3]:
df.head(5)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [4]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [5]:
df.head(5)

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [6]:
strings = list(df.dtypes[df.dtypes == 'object'].index)

In [7]:
strings

['make',
 'model',
 'engine_fuel_type',
 'transmission_type',
 'driven_wheels',
 'market_category',
 'vehicle_size',
 'vehicle_style']

In [8]:
for col in strings:
    df[col] = df[col].str.lower().str.replace(' ', '_')

In [9]:
High_yr = df['year'].max()
High_yr

2017

In [10]:
df['age'] =  (High_yr + 1) - df.year

In [11]:
df.head()

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
0,bmw,1_series_m,2011,premium_unleaded_(required),335.0,6.0,manual,rear_wheel_drive,2.0,"factory_tuner,luxury,high-performance",compact,coupe,26,19,3916,46135,7
1,bmw,1_series,2011,premium_unleaded_(required),300.0,6.0,manual,rear_wheel_drive,2.0,"luxury,performance",compact,convertible,28,19,3916,40650,7
2,bmw,1_series,2011,premium_unleaded_(required),300.0,6.0,manual,rear_wheel_drive,2.0,"luxury,high-performance",compact,coupe,28,20,3916,36350,7
3,bmw,1_series,2011,premium_unleaded_(required),230.0,6.0,manual,rear_wheel_drive,2.0,"luxury,performance",compact,coupe,28,18,3916,29450,7
4,bmw,1_series,2011,premium_unleaded_(required),230.0,6.0,manual,rear_wheel_drive,2.0,luxury,compact,convertible,28,18,3916,34500,7

In [12]:
df['number_of_doors'] = df['number_of_doors'].astype('object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   make               11914 non-null  object
 1   model              11914 non-null  object
 2   year               11914 non-null  int64
 3   engine_fuel_type   11911 non-null  object
 4   engine_hp          11845 non-null  float64
 5   engine_cylinders   11884 non-null  float64
 6   transmission_type  11914 non-null  object
 7   driven_wheels      11914 non-null  object
 8   number_of_doors    11908 non-null  object
 9   market_category    8172 non-null   object
 10  vehicle_size       11914 non-null  object
 11  vehicle_style      11914 non-null  object
 12  highway_mpg        11914 non-null  int64
 13  city_mpg           11914 non-null  int64
 14  popularity         11914 non-null  int64
 15  msrp               11914 non-null  int64
 16  age                11914 non-null  int64
dtypes: float64(2), int64(6), object(9)
memory usage: 1.5+ MB

In [14]:
df[df['engine_fuel_type'].isna()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
11321,suzuki,verona,2004,NaN,155.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,25,17,481,17199,14
11322,suzuki,verona,2004,NaN,155.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,25,17,481,20199,14
11323,suzuki,verona,2004,NaN,155.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,25,17,481,18499,14

In [15]:
df[df['make'].isin(['suzuki'])].engine_fuel_type.unique()

array(['regular_unleaded', nan], dtype=object)

In [16]:
df[df['model'] == 'verona']

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
11321,suzuki,verona,2004,NaN,155.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,25,17,481,17199,14
11322,suzuki,verona,2004,NaN,155.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,25,17,481,20199,14
11323,suzuki,verona,2004,NaN,155.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,25,17,481,18499,14
11324,suzuki,verona,2005,regular_unleaded,155.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,25,18,481,19349,13
11325,suzuki,verona,2005,regular_unleaded,155.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,25,18,481,21049,13
11326,suzuki,verona,2005,regular_unleaded,155.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,25,18,481,17549,13
11327,suzuki,verona,2005,regular_unleaded,155.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,25,18,481,20549,13
11328,suzuki,verona,2006,regular_unleaded,155.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,25,17,481,20299,12
11329,suzuki,verona,2006,regular_unleaded,155.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,25,17,481,18299,12

In [17]:
df['engine_fuel_type'] = df['engine_fuel_type'].replace(np.nan, 'regular_unleaded')

In [18]:
df['engine_fuel_type'].isna().sum()

0

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   make               11914 non-null  object
 1   model              11914 non-null  object
 2   year               11914 non-null  int64
 3   engine_fuel_type   11914 non-null  object
 4   engine_hp          11845 non-null  float64
 5   engine_cylinders   11884 non-null  float64
 6   transmission_type  11914 non-null  object
 7   driven_wheels      11914 non-null  object
 8   number_of_doors    11908 non-null  object
 9   market_category    8172 non-null   object
 10  vehicle_size       11914 non-null  object
 11  vehicle_style      11914 non-null  object
 12  highway_mpg        11914 non-null  int64
 13  city_mpg           11914 non-null  int64
 14  popularity         11914 non-null  int64
 15  msrp               11914 non-null  int64
 16  age                11914 non-null  int64
dtypes: float64(2), int64(6), object(9)
memory usage: 1.5+ MB

In [20]:
df[df['engine_hp'].isna()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
539,fiat,500e,2015,electric,NaN,0.0,direct_drive,front_wheel_drive,2.0,hatchback,compact,2dr_hatchback,108,122,819,31800,3
540,fiat,500e,2016,electric,NaN,0.0,direct_drive,front_wheel_drive,2.0,hatchback,compact,2dr_hatchback,103,121,819,31800,2
541,fiat,500e,2017,electric,NaN,0.0,direct_drive,front_wheel_drive,2.0,hatchback,compact,2dr_hatchback,103,121,819,31800,1
2905,lincoln,continental,2017,premium_unleaded_(recommended),NaN,6.0,automatic,all_wheel_drive,4.0,luxury,large,sedan,25,17,61,55915,1
2906,lincoln,continental,2017,premium_unleaded_(recommended),NaN,6.0,automatic,front_wheel_drive,4.0,luxury,large,sedan,27,18,61,62915,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9850,kia,soul_ev,2015,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,35700,3
9851,kia,soul_ev,2015,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,33700,3
9852,kia,soul_ev,2016,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,33950,2
9853,kia,soul_ev,2016,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,31950,2
9854,kia,soul_ev,2016,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,35950,2

In [21]:
df[(df.engine_fuel_type == 'electric') & (df.make == 'fiat')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
539,fiat,500e,2015,electric,NaN,0.0,direct_drive,front_wheel_drive,2.0,hatchback,compact,2dr_hatchback,108,122,819,31800,3
540,fiat,500e,2016,electric,NaN,0.0,direct_drive,front_wheel_drive,2.0,hatchback,compact,2dr_hatchback,103,121,819,31800,2
541,fiat,500e,2017,electric,NaN,0.0,direct_drive,front_wheel_drive,2.0,hatchback,compact,2dr_hatchback,103,121,819,31800,1

In [22]:
re = df['make'] == 'fiat'
mean_fiat = df[df.make == 'fiat']['engine_hp'].mean()
df.loc[re, 'engine_hp'] =  df.loc[re, 'engine_hp'].fillna(mean_fiat)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   make               11914 non-null  object
 1   model              11914 non-null  object
 2   year               11914 non-null  int64
 3   engine_fuel_type   11914 non-null  object
 4   engine_hp          11848 non-null  float64
 5   engine_cylinders   11884 non-null  float64
 6   transmission_type  11914 non-null  object
 7   driven_wheels      11914 non-null  object
 8   number_of_doors    11908 non-null  object
 9   market_category    8172 non-null   object
 10  vehicle_size       11914 non-null  object
 11  vehicle_style      11914 non-null  object
 12  highway_mpg        11914 non-null  int64
 13  city_mpg           11914 non-null  int64
 14  popularity         11914 non-null  int64
 15  msrp               11914 non-null  int64
 16  age                11914 non-null  int64
dtypes: float64(2), int64(6), object(9)
memory usage: 1.5+ MB

In [24]:
df[df['engine_hp'].isna()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
2905,lincoln,continental,2017,premium_unleaded_(recommended),NaN,6.0,automatic,all_wheel_drive,4.0,luxury,large,sedan,25,17,61,55915,1
2906,lincoln,continental,2017,premium_unleaded_(recommended),NaN,6.0,automatic,front_wheel_drive,4.0,luxury,large,sedan,27,18,61,62915,1
2907,lincoln,continental,2017,premium_unleaded_(recommended),NaN,6.0,automatic,front_wheel_drive,4.0,luxury,large,sedan,27,18,61,53915,1
2908,lincoln,continental,2017,premium_unleaded_(recommended),NaN,6.0,automatic,all_wheel_drive,4.0,luxury,large,sedan,25,17,61,64915,1
4203,ford,escape,2017,regular_unleaded,NaN,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,30,23,5657,29100,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9850,kia,soul_ev,2015,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,35700,3
9851,kia,soul_ev,2015,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,33700,3
9852,kia,soul_ev,2016,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,33950,2
9853,kia,soul_ev,2016,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,31950,2
9854,kia,soul_ev,2016,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,35950,2

In [25]:
mean_1 = df[(df.make == 'lincoln') & (df.model == 'continental')]['engine_hp'].mean()

m = (df.make == 'lincoln') & (df.model == 'continental')

df.loc[m,'engine_hp'] =  df.loc[m,'engine_hp'].fillna(mean_1)

In [26]:
df[(df.make == 'lincoln') & (df.model == 'continental')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
2897,lincoln,continental,2001,regular_unleaded,275.000000,8.0,automatic,front_wheel_drive,4.0,luxury,large,sedan,23,15,61,39660,17
2898,lincoln,continental,2002,premium_unleaded_(required),275.000000,8.0,automatic,front_wheel_drive,4.0,luxury,large,sedan,23,15,61,39895,16
2899,lincoln,continental,2002,premium_unleaded_(required),275.000000,8.0,automatic,front_wheel_drive,4.0,luxury,large,sedan,23,15,61,38185,16
2900,lincoln,continental,2002,premium_unleaded_(required),275.000000,8.0,automatic,front_wheel_drive,4.0,luxury,large,sedan,23,15,61,38790,16
2901,lincoln,continental,2002,premium_unleaded_(required),275.000000,8.0,automatic,front_wheel_drive,4.0,luxury,large,sedan,23,15,61,39775,16
2902,lincoln,continental,2017,regular_unleaded,305.000000,6.0,automatic,front_wheel_drive,4.0,luxury,large,sedan,26,17,61,44560,1
2903,lincoln,continental,2017,regular_unleaded,305.000000,6.0,automatic,all_wheel_drive,4.0,luxury,large,sedan,24,16,61,46560,1
2904,lincoln,continental,2017,regular_unleaded,305.000000,6.0,automatic,all_wheel_drive,4.0,luxury,large,sedan,24,16,61,49515,1
2905,lincoln,continental,2017,premium_unleaded_(recommended),288.333333,6.0,automatic,all_wheel_drive,4.0,luxury,large,sedan,25,17,61,55915,1
2906,lincoln,continental,2017,premium_unleaded_(recommended),288.333333,6.0,automatic,front_wheel_drive,4.0,luxury,large,sedan,27,18,61,62915,1
2907,lincoln,continental,2017,premium_unleaded_(recommended),288.333333,6.0,automatic,front_wheel_drive,4.0,luxury,large,sedan,27,18,61,53915,1
2908,lincoln,continental,2017,premium_unleaded_(recommended),288.333333,6.0,automatic,all_wheel_drive,4.0,luxury,large,sedan,25,17,61,64915,1
2909,lincoln,continental,2017,regular_unleaded,305.000000,6.0,automatic,front_wheel_drive,4.0,luxury,large,sedan,26,17,61,47515,1

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   make               11914 non-null  object
 1   model              11914 non-null  object
 2   year               11914 non-null  int64
 3   engine_fuel_type   11914 non-null  object
 4   engine_hp          11852 non-null  float64
 5   engine_cylinders   11884 non-null  float64
 6   transmission_type  11914 non-null  object
 7   driven_wheels      11914 non-null  object
 8   number_of_doors    11908 non-null  object
 9   market_category    8172 non-null   object
 10  vehicle_size       11914 non-null  object
 11  vehicle_style      11914 non-null  object
 12  highway_mpg        11914 non-null  int64
 13  city_mpg           11914 non-null  int64
 14  popularity         11914 non-null  int64
 15  msrp               11914 non-null  int64
 16  age                11914 non-null  int64
dtypes: float64(2), int64(6), object(9)
memory usage: 1.5+ MB

In [28]:
df[df['engine_hp'].isna()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
4203,ford,escape,2017,regular_unleaded,NaN,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,30,23,5657,29100,1
4204,ford,escape,2017,regular_unleaded,NaN,4.0,automatic,all_wheel_drive,4.0,crossover,compact,4dr_suv,28,22,5657,30850,1
4205,ford,escape,2017,regular_unleaded,NaN,4.0,automatic,all_wheel_drive,4.0,crossover,compact,4dr_suv,28,22,5657,26850,1
4206,ford,escape,2017,regular_unleaded,NaN,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,30,23,5657,25100,1
4705,honda,fit_ev,2013,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,105,132,2202,36625,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9850,kia,soul_ev,2015,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,35700,3
9851,kia,soul_ev,2015,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,33700,3
9852,kia,soul_ev,2016,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,33950,2
9853,kia,soul_ev,2016,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,31950,2
9854,kia,soul_ev,2016,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,35950,2

In [29]:
ford_na_models = list(df[(df.make == 'ford') & (df['engine_hp'].isnull())]['model'].unique())
ford_na_models

['escape', 'focus', 'freestar']

In [30]:
df[df['model'].isin(ford_na_models)]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
4192,ford,escape,2015,premium_unleaded_(recommended),178.0,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,32,23,5657,29735,3
4193,ford,escape,2015,premium_unleaded_(recommended),178.0,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,32,23,5657,25650,3
4194,ford,escape,2015,premium_unleaded_(recommended),178.0,4.0,automatic,all_wheel_drive,4.0,crossover,compact,4dr_suv,30,22,5657,27400,3
4195,ford,escape,2015,regular_unleaded,168.0,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,31,22,5657,23450,3
4196,ford,escape,2015,premium_unleaded_(recommended),178.0,4.0,automatic,all_wheel_drive,4.0,crossover,compact,4dr_suv,30,22,5657,31485,3
4197,ford,escape,2016,premium_unleaded_(recommended),178.0,4.0,automatic,all_wheel_drive,4.0,crossover,compact,4dr_suv,29,22,5657,27540,2
4198,ford,escape,2016,premium_unleaded_(recommended),178.0,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,32,23,5657,25790,2
4199,ford,escape,2016,premium_unleaded_(recommended),178.0,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,32,23,5657,29995,2
4200,ford,escape,2016,regular_unleaded,168.0,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,31,22,5657,23590,2
4201,ford,escape,2016,premium_unleaded_(recommended),178.0,4.0,automatic,all_wheel_drive,4.0,crossover,compact,4dr_suv,29,22,5657,31745,2
4202,ford,escape,2017,regular_unleaded,168.0,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,29,21,5657,23600,1
4203,ford,escape,2017,regular_unleaded,NaN,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,30,23,5657,29100,1
4204,ford,escape,2017,regular_unleaded,NaN,4.0,automatic,all_wheel_drive,4.0,crossover,compact,4dr_suv,28,22,5657,30850,1
4205,ford,escape,2017,regular_unleaded,NaN,4.0,automatic,all_wheel_drive,4.0,crossover,compact,4dr_suv,28,22,5657,26850,1
4206,ford,escape,2017,regular_unleaded,NaN,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,30,23,5657,25100,1
4780,ford,focus,2015,flex-fuel_(unleaded/e85),160.0,4.0,manual,front_wheel_drive,4.0,flex_fuel,compact,sedan,36,26,5657,18460,3
4781,ford,focus,2015,flex-fuel_(unleaded/e85),160.0,4.0,manual,front_wheel_drive,4.0,"hatchback,flex_fuel",compact,4dr_hatchback,36,26,5657,18960,3
4782,ford,focus,2015,flex-fuel_(unleaded/e85),160.0,4.0,automated_manual,front_wheel_drive,4.0,flex_fuel,compact,sedan,40,27,5657,23170,3
4783,ford,focus,2015,flex-fuel_(unleaded/e85),160.0,4.0,manual,front_wheel_drive,4.0,flex_fuel,compact,sedan,36,26,5657,17170,3
4784,ford,focus,2015,flex-fuel_(unleaded/e85),160.0,4.0,automated_manual,front_wheel_drive,4.0,"hatchback,flex_fuel",compact,4dr_hatchback,40,27,5657,23670,3
4785,ford,focus,2015,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,99,110,5657,29170,3
4786,ford,focus,2016,flex-fuel_(unleaded/e85),160.0,4.0,manual,front_wheel_drive,4.0,flex_fuel,compact,sedan,36,26,5657,18515,2
4787,ford,focus,2016,flex-fuel_(unleaded/e85),160.0,4.0,automated_manual,front_wheel_drive,4.0,"hatchback,flex_fuel",compact,4dr_hatchback,40,27,5657,23725,2
4788,ford,focus,2016,flex-fuel_(unleaded/e85),160.0,4.0,automated_manual,front_wheel_drive,4.0,flex_fuel,compact,sedan,40,27,5657,23225,2
4789,ford,focus,2016,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,99,110,5657,29170,2
4790,ford,focus,2016,flex-fuel_(unleaded/e85),160.0,4.0,manual,front_wheel_drive,4.0,"hatchback,flex_fuel",compact,4dr_hatchback,36,26,5657,19015,2
4791,ford,focus,2016,flex-fuel_(unleaded/e85),160.0,4.0,manual,front_wheel_drive,4.0,flex_fuel,compact,sedan,36,26,5657,17225,2
4792,ford,focus,2017,flex-fuel_(unleaded/e85),160.0,4.0,automated_manual,front_wheel_drive,4.0,"hatchback,flex_fuel",compact,4dr_hatchback,40,27,5657,21675,1
4793,ford,focus,2017,regular_unleaded,123.0,3.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,42,30,5657,18175,1
4794,ford,focus,2017,flex-fuel_(unleaded/e85),160.0,4.0,manual,front_wheel_drive,4.0,flex_fuel,compact,sedan,36,26,5657,16775,1
4795,ford,focus,2017,flex-fuel_(unleaded/e85),160.0,4.0,automated_manual,front_wheel_drive,4.0,"hatchback,flex_fuel",compact,4dr_hatchback,40,27,5657,24075,1
4796,ford,focus,2017,flex-fuel_(unleaded/e85),160.0,4.0,automated_manual,front_wheel_drive,4.0,flex_fuel,compact,sedan,40,27,5657,23575,1
4797,ford,focus,2017,flex-fuel_(unleaded/e85),160.0,4.0,automated_manual,front_wheel_drive,4.0,flex_fuel,compact,sedan,40,27,5657,21175,1
4798,ford,focus,2017,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,99,110,5657,29120,1
4799,ford,focus,2017,flex-fuel_(unleaded/e85),160.0,4.0,automated_manual,front_wheel_drive,4.0,"hatchback,flex_fuel",compact,4dr_hatchback,40,27,5657,19765,1
4914,ford,freestar,2005,regular_unleaded,NaN,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,22,16,5657,28030,13
4915,ford,freestar,2005,regular_unleaded,NaN,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,22,16,5657,23930,13
4916,ford,freestar,2005,regular_unleaded,NaN,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,cargo_minivan,22,16,5657,21630,13
4917,ford,freestar,2005,regular_unleaded,NaN,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,22,16,5657,26530,13
4918,ford,freestar,2005,regular_unleaded,NaN,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,21,16,5657,29030,13
4919,ford,freestar,2005,regular_unleaded,NaN,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,21,16,5657,32755,13
4920,ford,freestar,2006,regular_unleaded,193.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,cargo_minivan,22,16,5657,19650,12
4921,ford,freestar,2006,regular_unleaded,201.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,21,15,5657,29575,12
4922,ford,freestar,2006,regular_unleaded,193.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,22,16,5657,23655,12
4923,ford,freestar,2006,regular_unleaded,201.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,21,15,5657,26615,12
4924,ford,freestar,2007,regular_unleaded,201.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,21,15,5657,26665,11
4925,ford,freestar,2007,regular_unleaded,201.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,21,15,5657,23705,11
4926,ford,freestar,2007,regular_unleaded,201.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,21,15,5657,29575,11
4927,ford,freestar,2007,regular_unleaded,201.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,cargo_minivan,21,15,5657,19700,11

In [31]:
ford_escape_mean = df[(df.make == 'ford') & (df.model == 'escape') & (df.engine_fuel_type == 'regular_unleaded')]['engine_hp'].mean()

ford_escape_mean

168.0

In [32]:
df[(df.make == 'ford') & (df.model == 'escape') & (df.engine_fuel_type == 'regular_unleaded')] = df[(df.make == 'ford') & (df.model == 'escape') & (df.engine_fuel_type == 'regular_unleaded')].fillna(ford_escape_mean)

df[(df.make == 'ford') & (df.model == 'escape') & (df.engine_fuel_type == 'regular_unleaded')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
4195,ford,escape,2015,regular_unleaded,168.0,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,31,22,5657,23450,3
4200,ford,escape,2016,regular_unleaded,168.0,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,31,22,5657,23590,2
4202,ford,escape,2017,regular_unleaded,168.0,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,29,21,5657,23600,1
4203,ford,escape,2017,regular_unleaded,168.0,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,30,23,5657,29100,1
4204,ford,escape,2017,regular_unleaded,168.0,4.0,automatic,all_wheel_drive,4.0,crossover,compact,4dr_suv,28,22,5657,30850,1
4205,ford,escape,2017,regular_unleaded,168.0,4.0,automatic,all_wheel_drive,4.0,crossover,compact,4dr_suv,28,22,5657,26850,1
4206,ford,escape,2017,regular_unleaded,168.0,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,30,23,5657,25100,1

In [33]:
df[(df.make == 'ford') & (df.model == 'focus')][['engine_hp', 'vehicle_style']]

      engine_hp  vehicle_style
4780      160.0          sedan
4781      160.0  4dr_hatchback
4782      160.0          sedan
4783      160.0          sedan
4784      160.0  4dr_hatchback
4785        NaN  4dr_hatchback
4786      160.0          sedan
4787      160.0  4dr_hatchback
4788      160.0          sedan
4789        NaN  4dr_hatchback
4790      160.0  4dr_hatchback
4791      160.0          sedan
4792      160.0  4dr_hatchback
4793      123.0          sedan
4794      160.0          sedan
4795      160.0  4dr_hatchback
4796      160.0          sedan
4797      160.0          sedan
4798        NaN  4dr_hatchback
4799      160.0  4dr_hatchback

In [34]:
ford_focus_mean = df[(df.make == 'ford') & (df.model == 'focus') & (df.vehicle_style == '4dr_hatchback')]['engine_hp'].mean()
ford_focus_mean

160.0

In [35]:
ford_focus = (df.make == 'ford') & (df.model == 'focus') & (df.vehicle_style == '4dr_hatchback')

ford_focus

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [36]:
df.loc[ford_focus, 'engine_hp'] = df.loc[ford_focus, 'engine_hp'].fillna(ford_focus_mean)

In [37]:
df[(df.make == 'ford') & (df.model == 'focus')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
4780,ford,focus,2015,flex-fuel_(unleaded/e85),160.0,4.0,manual,front_wheel_drive,4.0,flex_fuel,compact,sedan,36,26,5657,18460,3
4781,ford,focus,2015,flex-fuel_(unleaded/e85),160.0,4.0,manual,front_wheel_drive,4.0,"hatchback,flex_fuel",compact,4dr_hatchback,36,26,5657,18960,3
4782,ford,focus,2015,flex-fuel_(unleaded/e85),160.0,4.0,automated_manual,front_wheel_drive,4.0,flex_fuel,compact,sedan,40,27,5657,23170,3
4783,ford,focus,2015,flex-fuel_(unleaded/e85),160.0,4.0,manual,front_wheel_drive,4.0,flex_fuel,compact,sedan,36,26,5657,17170,3
4784,ford,focus,2015,flex-fuel_(unleaded/e85),160.0,4.0,automated_manual,front_wheel_drive,4.0,"hatchback,flex_fuel",compact,4dr_hatchback,40,27,5657,23670,3
4785,ford,focus,2015,electric,160.0,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,99,110,5657,29170,3
4786,ford,focus,2016,flex-fuel_(unleaded/e85),160.0,4.0,manual,front_wheel_drive,4.0,flex_fuel,compact,sedan,36,26,5657,18515,2
4787,ford,focus,2016,flex-fuel_(unleaded/e85),160.0,4.0,automated_manual,front_wheel_drive,4.0,"hatchback,flex_fuel",compact,4dr_hatchback,40,27,5657,23725,2
4788,ford,focus,2016,flex-fuel_(unleaded/e85),160.0,4.0,automated_manual,front_wheel_drive,4.0,flex_fuel,compact,sedan,40,27,5657,23225,2
4789,ford,focus,2016,electric,160.0,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,99,110,5657,29170,2
4790,ford,focus,2016,flex-fuel_(unleaded/e85),160.0,4.0,manual,front_wheel_drive,4.0,"hatchback,flex_fuel",compact,4dr_hatchback,36,26,5657,19015,2
4791,ford,focus,2016,flex-fuel_(unleaded/e85),160.0,4.0,manual,front_wheel_drive,4.0,flex_fuel,compact,sedan,36,26,5657,17225,2
4792,ford,focus,2017,flex-fuel_(unleaded/e85),160.0,4.0,automated_manual,front_wheel_drive,4.0,"hatchback,flex_fuel",compact,4dr_hatchback,40,27,5657,21675,1
4793,ford,focus,2017,regular_unleaded,123.0,3.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,42,30,5657,18175,1
4794,ford,focus,2017,flex-fuel_(unleaded/e85),160.0,4.0,manual,front_wheel_drive,4.0,flex_fuel,compact,sedan,36,26,5657,16775,1
4795,ford,focus,2017,flex-fuel_(unleaded/e85),160.0,4.0,automated_manual,front_wheel_drive,4.0,"hatchback,flex_fuel",compact,4dr_hatchback,40,27,5657,24075,1
4796,ford,focus,2017,flex-fuel_(unleaded/e85),160.0,4.0,automated_manual,front_wheel_drive,4.0,flex_fuel,compact,sedan,40,27,5657,23575,1
4797,ford,focus,2017,flex-fuel_(unleaded/e85),160.0,4.0,automated_manual,front_wheel_drive,4.0,flex_fuel,compact,sedan,40,27,5657,21175,1
4798,ford,focus,2017,electric,160.0,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,99,110,5657,29120,1
4799,ford,focus,2017,flex-fuel_(unleaded/e85),160.0,4.0,automated_manual,front_wheel_drive,4.0,"hatchback,flex_fuel",compact,4dr_hatchback,40,27,5657,19765,1

In [38]:
ford_freestar_mean = df[(df.make == 'ford') & (df.model == 'freestar')]['engine_hp'].mean()
ford_freestar_mean

199.0

In [39]:
ford_freestar = (df.make == 'ford') & (df.model == 'freestar')

In [40]:
df.loc[ford_freestar, 'engine_hp'] = df.loc[ford_freestar, 'engine_hp'].fillna(ford_freestar_mean)

In [41]:
df[(df.make == 'ford') & (df.model == 'freestar')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
4914,ford,freestar,2005,regular_unleaded,199.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,22,16,5657,28030,13
4915,ford,freestar,2005,regular_unleaded,199.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,22,16,5657,23930,13
4916,ford,freestar,2005,regular_unleaded,199.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,cargo_minivan,22,16,5657,21630,13
4917,ford,freestar,2005,regular_unleaded,199.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,22,16,5657,26530,13
4918,ford,freestar,2005,regular_unleaded,199.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,21,16,5657,29030,13
4919,ford,freestar,2005,regular_unleaded,199.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,21,16,5657,32755,13
4920,ford,freestar,2006,regular_unleaded,193.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,cargo_minivan,22,16,5657,19650,12
4921,ford,freestar,2006,regular_unleaded,201.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,21,15,5657,29575,12
4922,ford,freestar,2006,regular_unleaded,193.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,22,16,5657,23655,12
4923,ford,freestar,2006,regular_unleaded,201.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,21,15,5657,26615,12
4924,ford,freestar,2007,regular_unleaded,201.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,21,15,5657,26665,11
4925,ford,freestar,2007,regular_unleaded,201.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,21,15,5657,23705,11
4926,ford,freestar,2007,regular_unleaded,201.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,21,15,5657,29575,11
4927,ford,freestar,2007,regular_unleaded,201.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,cargo_minivan,21,15,5657,19700,11

In [42]:
df[df['engine_hp'].isnull()]['make'].unique()

array(['honda', 'mitsubishi', 'chevrolet', 'nissan', 'mercedes-benz',
       'lincoln', 'tesla', 'toyota', 'kia'], dtype=object)

In [43]:
# df[(df.make == 'ford') & (df.model == 'freestar')]
list(df[(df.make == 'honda') & (df['engine_hp'].isnull())]['model'].unique())

['fit_ev']

In [44]:
df[(df.make == 'honda') & (df.model == 'fit_ev')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
4705,honda,fit_ev,2013,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,105,132,2202,36625,5
4706,honda,fit_ev,2014,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,105,132,2202,36625,4

In [45]:
honda_fit_ev_mean = df[(df.make == 'honda') & (df.vehicle_style == '4dr_hatchback') & (df.market_category == 'hatchback')]['engine_hp'].mean()
honda_fit_ev_mean

134.4

In [46]:
honda_fit_ev = (df.make == 'honda') & (df.model == 'fit_ev')

In [47]:
df.loc[honda_fit_ev, 'engine_hp'] = df.loc[honda_fit_ev, 'engine_hp'].fillna(honda_fit_ev_mean)

In [48]:
df[(df.make == 'honda') & (df.model == 'fit_ev')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
4705,honda,fit_ev,2013,electric,134.4,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,105,132,2202,36625,5
4706,honda,fit_ev,2014,electric,134.4,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,105,132,2202,36625,4

In [49]:
list(df[(df.make == 'mitsubishi') & (df['engine_hp'].isnull())]['model'].unique())

['i-miev']

In [50]:
df[(df.make == 'mitsubishi') & (df.model == 'i-miev')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
5778,mitsubishi,i-miev,2014,electric,NaN,NaN,direct_drive,rear_wheel_drive,4.0,hatchback,compact,4dr_hatchback,99,126,436,22995,4
5779,mitsubishi,i-miev,2016,electric,66.0,NaN,direct_drive,rear_wheel_drive,4.0,hatchback,compact,4dr_hatchback,99,126,436,22995,2
5780,mitsubishi,i-miev,2017,electric,66.0,NaN,direct_drive,rear_wheel_drive,4.0,hatchback,compact,4dr_hatchback,102,121,436,22995,1

In [51]:
mitsubishi_ele_mean = df[(df.make == 'mitsubishi') & (df.model == 'i-miev')]['engine_hp'].mean()
mitsubishi_ele_mean

66.0

In [52]:
mitsubishi_enghp = (df.make == 'mitsubishi') & (df.model == 'i-miev')

In [53]:
df.loc[mitsubishi_enghp, 'engine_hp'] = df.loc[mitsubishi_enghp, 'engine_hp'].fillna(mitsubishi_ele_mean)
df[(df.make == 'mitsubishi') & (df.model == 'i-miev')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
5778,mitsubishi,i-miev,2014,electric,66.0,NaN,direct_drive,rear_wheel_drive,4.0,hatchback,compact,4dr_hatchback,99,126,436,22995,4
5779,mitsubishi,i-miev,2016,electric,66.0,NaN,direct_drive,rear_wheel_drive,4.0,hatchback,compact,4dr_hatchback,99,126,436,22995,2
5780,mitsubishi,i-miev,2017,electric,66.0,NaN,direct_drive,rear_wheel_drive,4.0,hatchback,compact,4dr_hatchback,102,121,436,22995,1

# list(df[(df.make == 'honda') & (df['engine_hp'].isnull())]['model'].unique())
df[(df.make == 'honda') & (df.model == 'fit_ev')]
honda_fit_ev = (df.make == 'honda') & (df.model == 'fit_ev')
df.loc[honda_fit_ev, 'engine_hp'] = df.loc[honda_fit_ev, 'engine_hp'].fillna(honda_fit_ev_mean)
df[(df.make == 'honda') & (df.model == 'fit_ev')]

In [54]:
df[df['engine_hp'].isnull()]['make'].unique()

array(['chevrolet', 'nissan', 'mercedes-benz', 'lincoln', 'tesla',
       'toyota', 'kia'], dtype=object)

In [55]:
list(df[(df.make == 'chevrolet') & (df['engine_hp'].isnull())]['model'].unique())

['impala']

In [56]:
df[(df.make == 'chevrolet') & (df.model == 'impala')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
5823,chevrolet,impala,2015,regular_unleaded,195.0,4.0,automatic,front_wheel_drive,4.0,NaN,large,sedan,31,21,1385,34465,3
5824,chevrolet,impala,2015,regular_unleaded,195.0,4.0,automatic,front_wheel_drive,4.0,NaN,large,sedan,31,21,1385,27060,3
5825,chevrolet,impala,2015,flex-fuel_(unleaded/natural_gas),NaN,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,25,17,1385,40660,3
5826,chevrolet,impala,2015,flex-fuel_(unleaded/e85),305.0,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,29,19,1385,35440,3
5827,chevrolet,impala,2015,flex-fuel_(unleaded/e85),305.0,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,29,19,1385,30285,3
5828,chevrolet,impala,2015,regular_unleaded,195.0,4.0,automatic,front_wheel_drive,4.0,NaN,large,sedan,31,21,1385,29310,3
5829,chevrolet,impala,2015,regular_unleaded,195.0,4.0,automatic,front_wheel_drive,4.0,NaN,large,sedan,31,21,1385,27060,3
5830,chevrolet,impala,2015,flex-fuel_(unleaded/natural_gas),NaN,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,25,17,1385,37535,3
5831,chevrolet,impala,2016,flex-fuel_(unleaded/natural_gas),NaN,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,25,17,1385,40810,2
5832,chevrolet,impala,2016,flex-fuel_(unleaded/e85),305.0,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,29,19,1385,35540,2
5833,chevrolet,impala,2016,flex-fuel_(unleaded/natural_gas),NaN,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,25,17,1385,37570,2
5834,chevrolet,impala,2016,flex-fuel_(unleaded/e85),305.0,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,29,19,1385,30435,2
5835,chevrolet,impala,2016,regular_unleaded,195.0,4.0,automatic,front_wheel_drive,4.0,NaN,large,sedan,31,22,1385,27095,2
5836,chevrolet,impala,2016,regular_unleaded,195.0,4.0,automatic,front_wheel_drive,4.0,NaN,large,sedan,31,22,1385,29460,2
5837,chevrolet,impala,2016,regular_unleaded,195.0,4.0,automatic,front_wheel_drive,4.0,NaN,large,sedan,31,22,1385,27095,2
5838,chevrolet,impala,2017,flex-fuel_(unleaded/e85),305.0,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,28,19,1385,35645,1
5839,chevrolet,impala,2017,flex-fuel_(unleaded/natural_gas),NaN,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,25,17,1385,37675,1
5840,chevrolet,impala,2017,flex-fuel_(unleaded/natural_gas),NaN,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,25,17,1385,40915,1

In [57]:
chevrolet_eng_hp_mean = df[(df.make == 'chevrolet') & (df.model == 'impala')]['engine_hp'].mean()
chevrolet_eng_hp_mean

240.83333333333334

In [58]:
chevrolet_eng_hp_ = (df.make == 'chevrolet') & (df.model == 'impala')

In [59]:
df.loc[chevrolet_eng_hp_, 'engine_hp'] = df.loc[chevrolet_eng_hp_, 'engine_hp'].fillna(chevrolet_eng_hp_mean)
df[(df.make == 'chevrolet') & (df.model == 'impala')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
5823,chevrolet,impala,2015,regular_unleaded,195.000000,4.0,automatic,front_wheel_drive,4.0,NaN,large,sedan,31,21,1385,34465,3
5824,chevrolet,impala,2015,regular_unleaded,195.000000,4.0,automatic,front_wheel_drive,4.0,NaN,large,sedan,31,21,1385,27060,3
5825,chevrolet,impala,2015,flex-fuel_(unleaded/natural_gas),240.833333,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,25,17,1385,40660,3
5826,chevrolet,impala,2015,flex-fuel_(unleaded/e85),305.000000,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,29,19,1385,35440,3
5827,chevrolet,impala,2015,flex-fuel_(unleaded/e85),305.000000,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,29,19,1385,30285,3
5828,chevrolet,impala,2015,regular_unleaded,195.000000,4.0,automatic,front_wheel_drive,4.0,NaN,large,sedan,31,21,1385,29310,3
5829,chevrolet,impala,2015,regular_unleaded,195.000000,4.0,automatic,front_wheel_drive,4.0,NaN,large,sedan,31,21,1385,27060,3
5830,chevrolet,impala,2015,flex-fuel_(unleaded/natural_gas),240.833333,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,25,17,1385,37535,3
5831,chevrolet,impala,2016,flex-fuel_(unleaded/natural_gas),240.833333,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,25,17,1385,40810,2
5832,chevrolet,impala,2016,flex-fuel_(unleaded/e85),305.000000,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,29,19,1385,35540,2
5833,chevrolet,impala,2016,flex-fuel_(unleaded/natural_gas),240.833333,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,25,17,1385,37570,2
5834,chevrolet,impala,2016,flex-fuel_(unleaded/e85),305.000000,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,29,19,1385,30435,2
5835,chevrolet,impala,2016,regular_unleaded,195.000000,4.0,automatic,front_wheel_drive,4.0,NaN,large,sedan,31,22,1385,27095,2
5836,chevrolet,impala,2016,regular_unleaded,195.000000,4.0,automatic,front_wheel_drive,4.0,NaN,large,sedan,31,22,1385,29460,2
5837,chevrolet,impala,2016,regular_unleaded,195.000000,4.0,automatic,front_wheel_drive,4.0,NaN,large,sedan,31,22,1385,27095,2
5838,chevrolet,impala,2017,flex-fuel_(unleaded/e85),305.000000,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,28,19,1385,35645,1
5839,chevrolet,impala,2017,flex-fuel_(unleaded/natural_gas),240.833333,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,25,17,1385,37675,1
5840,chevrolet,impala,2017,flex-fuel_(unleaded/natural_gas),240.833333,6.0,automatic,front_wheel_drive,4.0,"flex_fuel,performance",large,sedan,25,17,1385,40915,1

In [60]:
df[df['engine_hp'].isnull()]['make'].unique()

array(['nissan', 'mercedes-benz', 'lincoln', 'tesla', 'toyota', 'kia'],
      dtype=object)

In [61]:
list(df[(df.make == 'nissan') & (df['engine_hp'].isnull())]['model'].unique())

['leaf']

In [62]:
df[(df.make == 'nissan') & (df.model == 'leaf')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
6385,nissan,leaf,2014,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,101,126,2009,35020,4
6386,nissan,leaf,2014,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,101,126,2009,32000,4
6387,nissan,leaf,2014,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,101,126,2009,28980,4
6388,nissan,leaf,2015,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,101,126,2009,32100,3
6389,nissan,leaf,2015,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,101,126,2009,35120,3
6390,nissan,leaf,2015,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,101,126,2009,29010,3
6391,nissan,leaf,2015,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,101,126,2009,32000,3
6392,nissan,leaf,2016,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,101,126,2009,29010,2
6393,nissan,leaf,2016,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,101,124,2009,34200,2
6394,nissan,leaf,2016,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,101,124,2009,36790,2

In [63]:
nissan_enghp_mean = df[(df.make == 'nissan') & (df.vehicle_style == '4dr_hatchback') & (df.market_category == 'hatchback') ]['engine_hp'].mean()
nissan_enghp_mean

109.0

In [64]:
nissan_enghp = (df.make == 'nissan') & (df.model == 'leaf')
nissan_enghp

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [65]:
df.loc[nissan_enghp, 'engine_hp'] = df.loc[nissan_enghp, 'engine_hp'].fillna(nissan_enghp_mean)
df[(df.make == 'nissan') & (df.model == 'leaf')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
6385,nissan,leaf,2014,electric,109.0,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,101,126,2009,35020,4
6386,nissan,leaf,2014,electric,109.0,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,101,126,2009,32000,4
6387,nissan,leaf,2014,electric,109.0,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,101,126,2009,28980,4
6388,nissan,leaf,2015,electric,109.0,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,101,126,2009,32100,3
6389,nissan,leaf,2015,electric,109.0,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,101,126,2009,35120,3
6390,nissan,leaf,2015,electric,109.0,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,101,126,2009,29010,3
6391,nissan,leaf,2015,electric,109.0,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,101,126,2009,32000,3
6392,nissan,leaf,2016,electric,109.0,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,101,126,2009,29010,2
6393,nissan,leaf,2016,electric,109.0,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,101,124,2009,34200,2
6394,nissan,leaf,2016,electric,109.0,0.0,direct_drive,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,101,124,2009,36790,2

In [66]:
df[df['engine_hp'].isnull()]['make'].unique()

array(['mercedes-benz', 'lincoln', 'tesla', 'toyota', 'kia'], dtype=object)

In [67]:
list(df[(df.make == 'mercedes-benz') & (df['engine_hp'].isnull())]['model'].unique())

['m-class']

In [68]:
benz_enghp_mean = df[(df.make == 'mercedes-benz') & (df.model == 'm-class') & (df.engine_fuel_type == 'diesel')]['engine_hp'].mean()
benz_enghp_mean

240.0

In [69]:
benz_enghp = (df.make == 'mercedes-benz') & (df.model == 'm-class') & (df.engine_fuel_type == 'diesel')

In [70]:
df.loc[benz_enghp, 'engine_hp'] = df.loc[benz_enghp, 'engine_hp'].fillna(benz_enghp_mean)
df[(df.make == 'mercedes-benz') & (df.model == 'm-class') & (df.engine_fuel_type == 'diesel')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
6566,mercedes-benz,m-class,2013,diesel,240.0,6.0,automatic,all_wheel_drive,4.0,"crossover,luxury,diesel",midsize,4dr_suv,28,20,617,51270,5
6572,mercedes-benz,m-class,2014,diesel,240.0,6.0,automatic,all_wheel_drive,4.0,"crossover,luxury,diesel",midsize,4dr_suv,28,20,617,51790,4
6578,mercedes-benz,m-class,2015,diesel,240.0,4.0,automatic,all_wheel_drive,4.0,"crossover,luxury,diesel",midsize,4dr_suv,29,22,617,49800,3

In [71]:
df[df['engine_hp'].isnull()]['make'].unique()

array(['lincoln', 'tesla', 'toyota', 'kia'], dtype=object)

In [72]:
list(df[(df.make == 'lincoln') & (df['engine_hp'].isnull())]['model'].unique())

['mkz']

In [73]:
df[(df.make == 'lincoln') & (df.model == 'mkz') & (df['engine_hp'].isnull())]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
6908,lincoln,mkz,2017,regular_unleaded,NaN,4.0,automatic,front_wheel_drive,4.0,"luxury,hybrid",midsize,sedan,38,41,61,35010,1
6910,lincoln,mkz,2017,regular_unleaded,NaN,4.0,automatic,front_wheel_drive,4.0,"luxury,hybrid",midsize,sedan,38,41,61,39510,1
6916,lincoln,mkz,2017,regular_unleaded,NaN,4.0,automatic,front_wheel_drive,4.0,"luxury,hybrid",midsize,sedan,38,41,61,36760,1
6918,lincoln,mkz,2017,regular_unleaded,NaN,4.0,automatic,front_wheel_drive,4.0,"luxury,hybrid",midsize,sedan,38,41,61,47670,1

In [74]:
lincoln_enghp_mean = df[(df.make == 'lincoln') & (df.model == 'mkz') & (df.engine_fuel_type == 'regular_unleaded') & (df.driven_wheels == 'front_wheel_drive') & (df.market_category == 'luxury,hybrid')]['engine_hp'].mean()
lincoln_enghp_mean

188.0

In [75]:
lincoln_enghp = (df.make == 'lincoln') & (df.model == 'mkz') & (df['engine_hp'].isnull())
lincoln_enghp

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [76]:
df.loc[lincoln_enghp, 'engine_hp'] = df.loc[lincoln_enghp, 'engine_hp'].fillna(lincoln_enghp_mean)
df[(df.make == 'lincoln') & (df.model == 'mkz') & (df['engine_hp'].isnull())]

Empty DataFrame
Columns: [make, model, year, engine_fuel_type, engine_hp, engine_cylinders, transmission_type, driven_wheels, number_of_doors, market_category, vehicle_size, vehicle_style, highway_mpg, city_mpg, popularity, msrp, age]
Index: []

In [77]:
df[df['engine_hp'].isnull()]['make'].unique()

array(['tesla', 'toyota', 'kia'], dtype=object)

In [78]:
list(df[(df.make == 'tesla') & (df['engine_hp'].isnull())]['model'].unique())

['model_s']

In [79]:
df[(df.make == 'tesla') & (df.model == 'model_s') & (df['engine_hp'].isnull())]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
6921,tesla,model_s,2014,electric,NaN,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,high-performance",large,sedan,90,88,1391,79900,4
6922,tesla,model_s,2014,electric,NaN,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,performance",large,sedan,97,94,1391,69900,4
6923,tesla,model_s,2014,electric,NaN,0.0,direct_drive,all_wheel_drive,4.0,"exotic,high-performance",large,sedan,94,86,1391,104500,4
6924,tesla,model_s,2014,electric,NaN,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,high-performance",large,sedan,90,88,1391,93400,4
6925,tesla,model_s,2015,electric,NaN,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,performance",large,sedan,97,94,1391,69900,3
6926,tesla,model_s,2015,electric,NaN,0.0,direct_drive,all_wheel_drive,4.0,"exotic,performance",large,sedan,102,101,1391,75000,3
6927,tesla,model_s,2015,electric,NaN,0.0,direct_drive,all_wheel_drive,4.0,"exotic,high-performance",large,sedan,106,95,1391,85000,3
6928,tesla,model_s,2015,electric,NaN,0.0,direct_drive,all_wheel_drive,4.0,"exotic,high-performance",large,sedan,98,89,1391,105000,3
6929,tesla,model_s,2015,electric,NaN,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,performance",large,sedan,90,88,1391,80000,3
6930,tesla,model_s,2016,electric,NaN,0.0,direct_drive,all_wheel_drive,NaN,"exotic,performance",large,sedan,105,102,1391,79500,2
6931,tesla,model_s,2016,electric,NaN,0.0,direct_drive,all_wheel_drive,NaN,"exotic,performance",large,sedan,101,98,1391,66000,2
6932,tesla,model_s,2016,electric,NaN,0.0,direct_drive,all_wheel_drive,NaN,"exotic,high-performance",large,sedan,105,92,1391,134500,2
6933,tesla,model_s,2016,electric,NaN,0.0,direct_drive,rear_wheel_drive,NaN,"exotic,performance",large,sedan,100,97,1391,74500,2
6934,tesla,model_s,2016,electric,NaN,0.0,direct_drive,all_wheel_drive,NaN,"exotic,performance",large,sedan,107,101,1391,71000,2
6935,tesla,model_s,2016,electric,NaN,0.0,direct_drive,all_wheel_drive,4.0,"exotic,performance",large,sedan,102,101,1391,75000,2
6936,tesla,model_s,2016,electric,NaN,0.0,direct_drive,all_wheel_drive,4.0,"exotic,high-performance",large,sedan,107,101,1391,89500,2
6937,tesla,model_s,2016,electric,NaN,0.0,direct_drive,all_wheel_drive,4.0,"exotic,high-performance",large,sedan,100,91,1391,112000,2
6938,tesla,model_s,2016,electric,NaN,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,performance",large,sedan,90,88,1391,70000,2

In [80]:
df[(df.make == 'tesla') & (df['engine_hp'].notnull())]

Empty DataFrame
Columns: [make, model, year, engine_fuel_type, engine_hp, engine_cylinders, transmission_type, driven_wheels, number_of_doors, market_category, vehicle_size, vehicle_style, highway_mpg, city_mpg, popularity, msrp, age]
Index: []

In [81]:
# considering exotic as luxury
tesla_rear_drive_mean = df[(df.engine_fuel_type == 'electric') & (df.driven_wheels == 'rear_wheel_drive') & (df['engine_hp'].notnull()) & (df.market_category == 'hatchback,luxury')]['engine_hp'].mean()
tesla_rear_drive_mean

170.0

In [82]:
tesla_rear = (df.make == 'tesla') & (df.driven_wheels == 'rear_wheel_drive')
tesla_rear

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [83]:
df.loc[tesla_rear, 'engine_hp'] = df.loc[tesla_rear, 'engine_hp'].fillna(tesla_rear_drive_mean)
df[(df.make == 'tesla') & (df.driven_wheels == 'rear_wheel_drive')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
6921,tesla,model_s,2014,electric,170.0,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,high-performance",large,sedan,90,88,1391,79900,4
6922,tesla,model_s,2014,electric,170.0,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,performance",large,sedan,97,94,1391,69900,4
6924,tesla,model_s,2014,electric,170.0,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,high-performance",large,sedan,90,88,1391,93400,4
6925,tesla,model_s,2015,electric,170.0,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,performance",large,sedan,97,94,1391,69900,3
6929,tesla,model_s,2015,electric,170.0,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,performance",large,sedan,90,88,1391,80000,3
6933,tesla,model_s,2016,electric,170.0,0.0,direct_drive,rear_wheel_drive,NaN,"exotic,performance",large,sedan,100,97,1391,74500,2
6938,tesla,model_s,2016,electric,170.0,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,performance",large,sedan,90,88,1391,70000,2

In [84]:
tesla_all_wheel_mean = df[(df.engine_fuel_type == 'electric') & (df['engine_hp'].notnull()) & ((df.market_category == 'hatchback,luxury') | (df.market_category.str.contains(r"\b(exotic)\b")))]['engine_hp'].mean()
tesla_all_wheel_mean

C:\Users\Lakshmeesh s reddy\AppData\Local\Temp\ipykernel_14248\1526185067.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  tesla_all_wheel_mean = df[(df.engine_fuel_type == 'electric') & (df['engine_hp'].notnull()) & ((df.market_category == 'hatchback,luxury') | (df.market_category.str.contains(r"\b(exotic)\b")))]['engine_hp'].mean()

171.5

In [85]:
tesla_all_wheel = (df.make == 'tesla') & (df.driven_wheels == 'all_wheel_drive')
tesla_all_wheel

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [86]:
df.loc[tesla_all_wheel,'engine_hp'] = df.loc[tesla_all_wheel,'engine_hp'].fillna(tesla_all_wheel_mean)

In [87]:
df[(df.make == 'tesla')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
6921,tesla,model_s,2014,electric,170.0,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,high-performance",large,sedan,90,88,1391,79900,4
6922,tesla,model_s,2014,electric,170.0,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,performance",large,sedan,97,94,1391,69900,4
6923,tesla,model_s,2014,electric,171.5,0.0,direct_drive,all_wheel_drive,4.0,"exotic,high-performance",large,sedan,94,86,1391,104500,4
6924,tesla,model_s,2014,electric,170.0,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,high-performance",large,sedan,90,88,1391,93400,4
6925,tesla,model_s,2015,electric,170.0,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,performance",large,sedan,97,94,1391,69900,3
6926,tesla,model_s,2015,electric,171.5,0.0,direct_drive,all_wheel_drive,4.0,"exotic,performance",large,sedan,102,101,1391,75000,3
6927,tesla,model_s,2015,electric,171.5,0.0,direct_drive,all_wheel_drive,4.0,"exotic,high-performance",large,sedan,106,95,1391,85000,3
6928,tesla,model_s,2015,electric,171.5,0.0,direct_drive,all_wheel_drive,4.0,"exotic,high-performance",large,sedan,98,89,1391,105000,3
6929,tesla,model_s,2015,electric,170.0,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,performance",large,sedan,90,88,1391,80000,3
6930,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,NaN,"exotic,performance",large,sedan,105,102,1391,79500,2
6931,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,NaN,"exotic,performance",large,sedan,101,98,1391,66000,2
6932,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,NaN,"exotic,high-performance",large,sedan,105,92,1391,134500,2
6933,tesla,model_s,2016,electric,170.0,0.0,direct_drive,rear_wheel_drive,NaN,"exotic,performance",large,sedan,100,97,1391,74500,2
6934,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,NaN,"exotic,performance",large,sedan,107,101,1391,71000,2
6935,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,4.0,"exotic,performance",large,sedan,102,101,1391,75000,2
6936,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,4.0,"exotic,high-performance",large,sedan,107,101,1391,89500,2
6937,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,4.0,"exotic,high-performance",large,sedan,100,91,1391,112000,2
6938,tesla,model_s,2016,electric,170.0,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,performance",large,sedan,90,88,1391,70000,2

In [88]:
df[df['engine_hp'].isnull()]['make'].unique()

array(['toyota', 'kia'], dtype=object)

In [89]:
list(df[(df.make == 'toyota') & (df['engine_hp'].isnull())]['model'].unique())

['rav4_ev']

In [90]:
df[(df.make == 'toyota') & (df.model == 'rav4_ev')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
8373,toyota,rav4_ev,2012,electric,154.0,NaN,direct_drive,front_wheel_drive,4.0,crossover,midsize,4dr_suv,74,78,2031,49800,6
8374,toyota,rav4_ev,2013,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,crossover,midsize,4dr_suv,74,78,2031,49800,5
8375,toyota,rav4_ev,2014,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,crossover,midsize,4dr_suv,74,78,2031,49800,4

In [91]:
toyota_ele_mean = df[(df.make == 'toyota') & (df.model == 'rav4_ev')]['engine_hp'].mean()
toyota_ele_mean

154.0

In [92]:
toyota_ele = (df.make == 'toyota') & (df.model == 'rav4_ev')
toyota_ele

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [93]:
df.loc[toyota_ele, 'engine_hp'] = df.loc[toyota_ele, 'engine_hp'].fillna(toyota_ele_mean)
df[(df.make == 'toyota') & (df.model == 'rav4_ev')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
8373,toyota,rav4_ev,2012,electric,154.0,NaN,direct_drive,front_wheel_drive,4.0,crossover,midsize,4dr_suv,74,78,2031,49800,6
8374,toyota,rav4_ev,2013,electric,154.0,0.0,direct_drive,front_wheel_drive,4.0,crossover,midsize,4dr_suv,74,78,2031,49800,5
8375,toyota,rav4_ev,2014,electric,154.0,0.0,direct_drive,front_wheel_drive,4.0,crossover,midsize,4dr_suv,74,78,2031,49800,4

In [94]:
df[df['engine_hp'].isnull()]['make'].unique()

array(['kia'], dtype=object)

In [95]:
list(df[(df.make == 'kia') & (df['engine_hp'].isnull())]['model'].unique())

['soul_ev']

In [96]:
df[(df.make == 'kia') & (df.model == 'soul_ev')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
9850,kia,soul_ev,2015,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,35700,3
9851,kia,soul_ev,2015,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,33700,3
9852,kia,soul_ev,2016,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,33950,2
9853,kia,soul_ev,2016,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,31950,2
9854,kia,soul_ev,2016,electric,NaN,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,35950,2

In [97]:
kia_ele_mean = df[(df.make == 'kia') & (df['engine_hp'].notnull()) & (df.vehicle_size == 'compact') & (df.driven_wheels == 'front_wheel_drive')]['engine_hp'].mean()
kia_ele_mean

156.91379310344828

In [98]:
kia_ele = (df.make == 'kia') & (df.model == 'soul_ev')
kia_ele

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [99]:
df.loc[kia_ele, 'engine_hp'] = df.loc[kia_ele, 'engine_hp'].fillna(kia_ele_mean)
df[(df.make == 'kia') & (df.model == 'soul_ev')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
9850,kia,soul_ev,2015,electric,156.913793,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,35700,3
9851,kia,soul_ev,2015,electric,156.913793,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,33700,3
9852,kia,soul_ev,2016,electric,156.913793,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,33950,2
9853,kia,soul_ev,2016,electric,156.913793,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,31950,2
9854,kia,soul_ev,2016,electric,156.913793,0.0,direct_drive,front_wheel_drive,4.0,NaN,compact,wagon,92,120,1720,35950,2

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   make               11914 non-null  object
 1   model              11914 non-null  object
 2   year               11914 non-null  int64
 3   engine_fuel_type   11914 non-null  object
 4   engine_hp          11914 non-null  float64
 5   engine_cylinders   11884 non-null  float64
 6   transmission_type  11914 non-null  object
 7   driven_wheels      11914 non-null  object
 8   number_of_doors    11908 non-null  object
 9   market_category    8172 non-null   object
 10  vehicle_size       11914 non-null  object
 11  vehicle_style      11914 non-null  object
 12  highway_mpg        11914 non-null  int64
 13  city_mpg           11914 non-null  int64
 14  popularity         11914 non-null  int64
 15  msrp               11914 non-null  int64
 16  age                11914 non-null  int64
dtypes: float64(2), int64(6), object(9)
memory usage: 1.5+ MB

In [101]:
ele_eng_cy = df.engine_fuel_type == 'electric'

In [102]:
df.loc[ele_eng_cy, 'engine_cylinders'] = df.loc[ele_eng_cy, 'engine_cylinders'].fillna(0.0)

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   make               11914 non-null  object
 1   model              11914 non-null  object
 2   year               11914 non-null  int64
 3   engine_fuel_type   11914 non-null  object
 4   engine_hp          11914 non-null  float64
 5   engine_cylinders   11894 non-null  float64
 6   transmission_type  11914 non-null  object
 7   driven_wheels      11914 non-null  object
 8   number_of_doors    11908 non-null  object
 9   market_category    8172 non-null   object
 10  vehicle_size       11914 non-null  object
 11  vehicle_style      11914 non-null  object
 12  highway_mpg        11914 non-null  int64
 13  city_mpg           11914 non-null  int64
 14  popularity         11914 non-null  int64
 15  msrp               11914 non-null  int64
 16  age                11914 non-null  int64
dtypes: float64(2), int64(6), object(9)
memory usage: 1.5+ MB

In [104]:
df[(df['engine_cylinders'].isnull()) & (df.make == 'mazda')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
8695,mazda,rx-7,1993,regular_unleaded,255.0,NaN,manual,rear_wheel_drive,2.0,"factory_tuner,performance",compact,coupe,23,15,586,7523,25
8696,mazda,rx-7,1994,regular_unleaded,255.0,NaN,manual,rear_wheel_drive,2.0,"factory_tuner,performance",compact,coupe,23,15,586,8147,24
8697,mazda,rx-7,1995,regular_unleaded,255.0,NaN,manual,rear_wheel_drive,2.0,"factory_tuner,performance",compact,coupe,23,15,586,8839,23
8698,mazda,rx-8,2009,premium_unleaded_(required),232.0,NaN,manual,rear_wheel_drive,4.0,performance,compact,coupe,22,16,586,31930,9
8699,mazda,rx-8,2009,premium_unleaded_(required),212.0,NaN,automatic,rear_wheel_drive,4.0,performance,compact,coupe,23,16,586,26435,9
8700,mazda,rx-8,2009,premium_unleaded_(required),232.0,NaN,manual,rear_wheel_drive,4.0,performance,compact,coupe,22,16,586,27860,9
8701,mazda,rx-8,2009,premium_unleaded_(required),232.0,NaN,manual,rear_wheel_drive,4.0,performance,compact,coupe,22,16,586,31000,9
8702,mazda,rx-8,2009,premium_unleaded_(required),232.0,NaN,manual,rear_wheel_drive,4.0,performance,compact,coupe,22,16,586,26435,9
8703,mazda,rx-8,2009,premium_unleaded_(required),212.0,NaN,automatic,rear_wheel_drive,4.0,performance,compact,coupe,23,16,586,31700,9
8704,mazda,rx-8,2009,premium_unleaded_(required),212.0,NaN,automatic,rear_wheel_drive,4.0,performance,compact,coupe,23,16,586,28560,9
8705,mazda,rx-8,2010,premium_unleaded_(required),232.0,NaN,manual,rear_wheel_drive,4.0,performance,compact,coupe,22,16,586,32140,8
8706,mazda,rx-8,2010,premium_unleaded_(required),212.0,NaN,automatic,rear_wheel_drive,4.0,performance,compact,coupe,23,16,586,26645,8
8707,mazda,rx-8,2010,premium_unleaded_(required),212.0,NaN,automatic,rear_wheel_drive,4.0,performance,compact,coupe,23,16,586,32810,8
8708,mazda,rx-8,2010,premium_unleaded_(required),232.0,NaN,manual,rear_wheel_drive,4.0,performance,compact,coupe,22,16,586,26645,8
8709,mazda,rx-8,2010,premium_unleaded_(required),232.0,NaN,manual,rear_wheel_drive,4.0,performance,compact,coupe,22,16,586,32110,8
8710,mazda,rx-8,2011,premium_unleaded_(required),212.0,NaN,automatic,rear_wheel_drive,4.0,performance,compact,coupe,23,16,586,32960,7
8711,mazda,rx-8,2011,premium_unleaded_(required),232.0,NaN,manual,rear_wheel_drive,4.0,performance,compact,coupe,22,16,586,32260,7
8712,mazda,rx-8,2011,premium_unleaded_(required),232.0,NaN,manual,rear_wheel_drive,4.0,performance,compact,coupe,22,16,586,32290,7
8713,mazda,rx-8,2011,premium_unleaded_(required),232.0,NaN,manual,rear_wheel_drive,4.0,performance,compact,coupe,22,16,586,26795,7
8714,mazda,rx-8,2011,premium_unleaded_(required),212.0,NaN,automatic,rear_wheel_drive,4.0,performance,compact,coupe,23,16,586,26795,7

In [105]:
rx7_mean = df[(df.make == 'mazda') & (df.transmission_type == 'manual') & (df.engine_fuel_type == 'regular_unleaded') & (df.driven_wheels == 'rear_wheel_drive') & (df.number_of_doors == 2.0) & (df.year <= 1995)]['engine_cylinders'].mean()
rx7_mean

6.0

In [106]:
ma_cy = (df.make == 'mazda') & (df.model == 'rx-7')
ma_cy

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [107]:
df.loc[ma_cy,'engine_cylinders'] = df.loc[ma_cy,'engine_cylinders'].fillna(rx7_mean)

In [108]:
df[(df.make == 'mazda') & (df.model == 'rx-7')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
8695,mazda,rx-7,1993,regular_unleaded,255.0,6.0,manual,rear_wheel_drive,2.0,"factory_tuner,performance",compact,coupe,23,15,586,7523,25
8696,mazda,rx-7,1994,regular_unleaded,255.0,6.0,manual,rear_wheel_drive,2.0,"factory_tuner,performance",compact,coupe,23,15,586,8147,24
8697,mazda,rx-7,1995,regular_unleaded,255.0,6.0,manual,rear_wheel_drive,2.0,"factory_tuner,performance",compact,coupe,23,15,586,8839,23

In [109]:
df[(df['engine_cylinders'].isnull()) & (df.make == 'mazda')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
8698,mazda,rx-8,2009,premium_unleaded_(required),232.0,NaN,manual,rear_wheel_drive,4.0,performance,compact,coupe,22,16,586,31930,9
8699,mazda,rx-8,2009,premium_unleaded_(required),212.0,NaN,automatic,rear_wheel_drive,4.0,performance,compact,coupe,23,16,586,26435,9
8700,mazda,rx-8,2009,premium_unleaded_(required),232.0,NaN,manual,rear_wheel_drive,4.0,performance,compact,coupe,22,16,586,27860,9
8701,mazda,rx-8,2009,premium_unleaded_(required),232.0,NaN,manual,rear_wheel_drive,4.0,performance,compact,coupe,22,16,586,31000,9
8702,mazda,rx-8,2009,premium_unleaded_(required),232.0,NaN,manual,rear_wheel_drive,4.0,performance,compact,coupe,22,16,586,26435,9
8703,mazda,rx-8,2009,premium_unleaded_(required),212.0,NaN,automatic,rear_wheel_drive,4.0,performance,compact,coupe,23,16,586,31700,9
8704,mazda,rx-8,2009,premium_unleaded_(required),212.0,NaN,automatic,rear_wheel_drive,4.0,performance,compact,coupe,23,16,586,28560,9
8705,mazda,rx-8,2010,premium_unleaded_(required),232.0,NaN,manual,rear_wheel_drive,4.0,performance,compact,coupe,22,16,586,32140,8
8706,mazda,rx-8,2010,premium_unleaded_(required),212.0,NaN,automatic,rear_wheel_drive,4.0,performance,compact,coupe,23,16,586,26645,8
8707,mazda,rx-8,2010,premium_unleaded_(required),212.0,NaN,automatic,rear_wheel_drive,4.0,performance,compact,coupe,23,16,586,32810,8
8708,mazda,rx-8,2010,premium_unleaded_(required),232.0,NaN,manual,rear_wheel_drive,4.0,performance,compact,coupe,22,16,586,26645,8
8709,mazda,rx-8,2010,premium_unleaded_(required),232.0,NaN,manual,rear_wheel_drive,4.0,performance,compact,coupe,22,16,586,32110,8
8710,mazda,rx-8,2011,premium_unleaded_(required),212.0,NaN,automatic,rear_wheel_drive,4.0,performance,compact,coupe,23,16,586,32960,7
8711,mazda,rx-8,2011,premium_unleaded_(required),232.0,NaN,manual,rear_wheel_drive,4.0,performance,compact,coupe,22,16,586,32260,7
8712,mazda,rx-8,2011,premium_unleaded_(required),232.0,NaN,manual,rear_wheel_drive,4.0,performance,compact,coupe,22,16,586,32290,7
8713,mazda,rx-8,2011,premium_unleaded_(required),232.0,NaN,manual,rear_wheel_drive,4.0,performance,compact,coupe,22,16,586,26795,7
8714,mazda,rx-8,2011,premium_unleaded_(required),212.0,NaN,automatic,rear_wheel_drive,4.0,performance,compact,coupe,23,16,586,26795,7

In [110]:
df[(df.make == 'mazda') & (df.transmission_type == 'manual') & (df.engine_fuel_type == 'regular_unleaded') & (df.driven_wheels == 'rear_wheel_drive') & (df.number_of_doors == 4.0) & (df.year >= 1995)]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1689,mazda,b-series_pickup,1998,regular_unleaded,119.0,4.0,manual,rear_wheel_drive,4.0,NaN,compact,extended_cab_pickup,24,19,586,2717,20
1707,mazda,b-series_pickup,1999,regular_unleaded,119.0,4.0,manual,rear_wheel_drive,4.0,NaN,compact,extended_cab_pickup,24,19,586,2857,19
1726,mazda,b-series_truck,2007,regular_unleaded,148.0,6.0,manual,rear_wheel_drive,4.0,NaN,compact,extended_cab_pickup,21,16,586,19040,11
1727,mazda,b-series_truck,2007,regular_unleaded,148.0,6.0,manual,rear_wheel_drive,4.0,NaN,compact,extended_cab_pickup,21,16,586,21430,11
1737,mazda,b-series,2001,regular_unleaded,150.0,6.0,manual,rear_wheel_drive,4.0,NaN,compact,extended_cab_pickup,21,15,586,18485,17
1741,mazda,b-series,2001,regular_unleaded,207.0,6.0,manual,rear_wheel_drive,4.0,NaN,compact,extended_cab_pickup,20,16,586,19340,17
10832,mazda,truck,2002,regular_unleaded,207.0,6.0,manual,rear_wheel_drive,4.0,NaN,compact,extended_cab_pickup,20,16,586,19885,16
10840,mazda,truck,2003,regular_unleaded,147.0,6.0,manual,rear_wheel_drive,4.0,NaN,compact,extended_cab_pickup,21,17,586,19215,15
10842,mazda,truck,2003,regular_unleaded,207.0,6.0,manual,rear_wheel_drive,4.0,NaN,compact,extended_cab_pickup,20,15,586,20880,15

In [111]:
engine_cy = (df.make == 'mazda') & (df['engine_cylinders'].isnull())
engine_cy

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [112]:
df.loc[engine_cy, 'engine_cylinders'] = df.loc[engine_cy, 'engine_cylinders'].fillna(6.0)
df[(df.make == 'mazda') & (df['engine_cylinders'].isnull())]

Empty DataFrame
Columns: [make, model, year, engine_fuel_type, engine_hp, engine_cylinders, transmission_type, driven_wheels, number_of_doors, market_category, vehicle_size, vehicle_style, highway_mpg, city_mpg, popularity, msrp, age]
Index: []

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   make               11914 non-null  object
 1   model              11914 non-null  object
 2   year               11914 non-null  int64
 3   engine_fuel_type   11914 non-null  object
 4   engine_hp          11914 non-null  float64
 5   engine_cylinders   11914 non-null  float64
 6   transmission_type  11914 non-null  object
 7   driven_wheels      11914 non-null  object
 8   number_of_doors    11908 non-null  object
 9   market_category    8172 non-null   object
 10  vehicle_size       11914 non-null  object
 11  vehicle_style      11914 non-null  object
 12  highway_mpg        11914 non-null  int64
 13  city_mpg           11914 non-null  int64
 14  popularity         11914 non-null  int64
 15  msrp               11914 non-null  int64
 16  age                11914 non-null  int64
dtypes: float64(2), int64(6), object(9)
memory usage: 1.5+ MB

In [114]:
df[df['number_of_doors'].isnull()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
4666,ferrari,ff,2013,premium_unleaded_(required),651.0,12.0,automated_manual,all_wheel_drive,NaN,"exotic,high-performance",large,coupe,16,11,2774,295000,5
6930,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,NaN,"exotic,performance",large,sedan,105,102,1391,79500,2
6931,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,NaN,"exotic,performance",large,sedan,101,98,1391,66000,2
6932,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,NaN,"exotic,high-performance",large,sedan,105,92,1391,134500,2
6933,tesla,model_s,2016,electric,170.0,0.0,direct_drive,rear_wheel_drive,NaN,"exotic,performance",large,sedan,100,97,1391,74500,2
6934,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,NaN,"exotic,performance",large,sedan,107,101,1391,71000,2

In [115]:
df[(df.make == 'ferrari') & (df.model == 'ff')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
4666,ferrari,ff,2013,premium_unleaded_(required),651.0,12.0,automated_manual,all_wheel_drive,NaN,"exotic,high-performance",large,coupe,16,11,2774,295000,5
4667,ferrari,ff,2014,premium_unleaded_(required),651.0,12.0,automated_manual,all_wheel_drive,2.0,"exotic,high-performance",large,coupe,16,11,2774,295000,4
4668,ferrari,ff,2015,premium_unleaded_(required),651.0,12.0,automated_manual,all_wheel_drive,2.0,"exotic,high-performance",large,coupe,16,11,2774,295000,3

In [116]:
fer_nodoor = (df.make == 'ferrari') & (df.model == 'ff')
fer_nodoor

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [117]:
df.loc[fer_nodoor, 'number_of_doors'] = df.loc[fer_nodoor, 'number_of_doors'].fillna(2.0)
df[(df.make == 'ferrari') & (df.model == 'ff')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
4666,ferrari,ff,2013,premium_unleaded_(required),651.0,12.0,automated_manual,all_wheel_drive,2.0,"exotic,high-performance",large,coupe,16,11,2774,295000,5
4667,ferrari,ff,2014,premium_unleaded_(required),651.0,12.0,automated_manual,all_wheel_drive,2.0,"exotic,high-performance",large,coupe,16,11,2774,295000,4
4668,ferrari,ff,2015,premium_unleaded_(required),651.0,12.0,automated_manual,all_wheel_drive,2.0,"exotic,high-performance",large,coupe,16,11,2774,295000,3

In [118]:
df[df['number_of_doors'].isnull()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
6930,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,NaN,"exotic,performance",large,sedan,105,102,1391,79500,2
6931,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,NaN,"exotic,performance",large,sedan,101,98,1391,66000,2
6932,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,NaN,"exotic,high-performance",large,sedan,105,92,1391,134500,2
6933,tesla,model_s,2016,electric,170.0,0.0,direct_drive,rear_wheel_drive,NaN,"exotic,performance",large,sedan,100,97,1391,74500,2
6934,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,NaN,"exotic,performance",large,sedan,107,101,1391,71000,2

In [119]:
df[(df.make == 'tesla') & (df.model == 'model_s')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
6921,tesla,model_s,2014,electric,170.0,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,high-performance",large,sedan,90,88,1391,79900,4
6922,tesla,model_s,2014,electric,170.0,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,performance",large,sedan,97,94,1391,69900,4
6923,tesla,model_s,2014,electric,171.5,0.0,direct_drive,all_wheel_drive,4.0,"exotic,high-performance",large,sedan,94,86,1391,104500,4
6924,tesla,model_s,2014,electric,170.0,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,high-performance",large,sedan,90,88,1391,93400,4
6925,tesla,model_s,2015,electric,170.0,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,performance",large,sedan,97,94,1391,69900,3
6926,tesla,model_s,2015,electric,171.5,0.0,direct_drive,all_wheel_drive,4.0,"exotic,performance",large,sedan,102,101,1391,75000,3
6927,tesla,model_s,2015,electric,171.5,0.0,direct_drive,all_wheel_drive,4.0,"exotic,high-performance",large,sedan,106,95,1391,85000,3
6928,tesla,model_s,2015,electric,171.5,0.0,direct_drive,all_wheel_drive,4.0,"exotic,high-performance",large,sedan,98,89,1391,105000,3
6929,tesla,model_s,2015,electric,170.0,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,performance",large,sedan,90,88,1391,80000,3
6930,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,NaN,"exotic,performance",large,sedan,105,102,1391,79500,2
6931,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,NaN,"exotic,performance",large,sedan,101,98,1391,66000,2
6932,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,NaN,"exotic,high-performance",large,sedan,105,92,1391,134500,2
6933,tesla,model_s,2016,electric,170.0,0.0,direct_drive,rear_wheel_drive,NaN,"exotic,performance",large,sedan,100,97,1391,74500,2
6934,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,NaN,"exotic,performance",large,sedan,107,101,1391,71000,2
6935,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,4.0,"exotic,performance",large,sedan,102,101,1391,75000,2
6936,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,4.0,"exotic,high-performance",large,sedan,107,101,1391,89500,2
6937,tesla,model_s,2016,electric,171.5,0.0,direct_drive,all_wheel_drive,4.0,"exotic,high-performance",large,sedan,100,91,1391,112000,2
6938,tesla,model_s,2016,electric,170.0,0.0,direct_drive,rear_wheel_drive,4.0,"exotic,performance",large,sedan,90,88,1391,70000,2

In [120]:
tesla_nodoor = (df.make == 'tesla') & (df.model == 'model_s')
tesla_nodoor

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [121]:
df.loc[tesla_nodoor, 'number_of_doors'] = df.loc[tesla_nodoor, 'number_of_doors'].fillna(4.0)
df[df['number_of_doors'].isnull()]

Empty DataFrame
Columns: [make, model, year, engine_fuel_type, engine_hp, engine_cylinders, transmission_type, driven_wheels, number_of_doors, market_category, vehicle_size, vehicle_style, highway_mpg, city_mpg, popularity, msrp, age]
Index: []

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   make               11914 non-null  object
 1   model              11914 non-null  object
 2   year               11914 non-null  int64
 3   engine_fuel_type   11914 non-null  object
 4   engine_hp          11914 non-null  float64
 5   engine_cylinders   11914 non-null  float64
 6   transmission_type  11914 non-null  object
 7   driven_wheels      11914 non-null  object
 8   number_of_doors    11914 non-null  object
 9   market_category    8172 non-null   object
 10  vehicle_size       11914 non-null  object
 11  vehicle_style      11914 non-null  object
 12  highway_mpg        11914 non-null  int64
 13  city_mpg           11914 non-null  int64
 14  popularity         11914 non-null  int64
 15  msrp               11914 non-null  int64
 16  age                11914 non-null  int64
dtypes: float64(2), int64(6), object(9)
memory usage: 1.5+ MB

In [123]:
df[df['market_category'].isnull()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
87,nissan,200sx,1996,regular_unleaded,115.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,36,26,2009,2000,22
88,nissan,200sx,1996,regular_unleaded,115.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,36,26,2009,2000,22
91,nissan,200sx,1997,regular_unleaded,115.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,35,25,2009,2000,21
92,nissan,200sx,1997,regular_unleaded,115.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,35,25,2009,2000,21
93,nissan,200sx,1998,regular_unleaded,115.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,35,25,2009,2000,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11794,subaru,xt,1991,regular_unleaded,145.0,6.0,manual,all_wheel_drive,2.0,NaN,compact,coupe,23,16,640,2000,27
11809,toyota,yaris_ia,2017,regular_unleaded,106.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,39,30,2031,15950,1
11810,toyota,yaris_ia,2017,regular_unleaded,106.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,40,32,2031,17050,1
11867,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,4dr_suv,21,15,549,64520,3
11868,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,21,14,549,67520,3

In [124]:
df[(df.make == 'nissan') & (df.model == '200sx')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
87,nissan,200sx,1996,regular_unleaded,115.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,36,26,2009,2000,22
88,nissan,200sx,1996,regular_unleaded,115.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,36,26,2009,2000,22
89,nissan,200sx,1996,regular_unleaded,140.0,4.0,manual,front_wheel_drive,2.0,performance,compact,coupe,29,21,2009,2000,22
90,nissan,200sx,1997,regular_unleaded,140.0,4.0,manual,front_wheel_drive,2.0,performance,compact,coupe,29,21,2009,2000,21
91,nissan,200sx,1997,regular_unleaded,115.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,35,25,2009,2000,21
92,nissan,200sx,1997,regular_unleaded,115.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,35,25,2009,2000,21
93,nissan,200sx,1998,regular_unleaded,115.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,35,25,2009,2000,20
94,nissan,200sx,1998,regular_unleaded,115.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,35,25,2009,2000,20
95,nissan,200sx,1998,regular_unleaded,140.0,4.0,manual,front_wheel_drive,2.0,performance,compact,coupe,28,20,2009,2073,20

In [125]:
lst_200x_ = list(df[(df.make == 'nissan') & (df.model == '200sx')]['market_category'].unique())
lst_200x_

[nan, 'performance']

In [126]:
mar_cat_val = [x for x in lst_200x_ if isinstance(x, str)]
mar_cat_val

['performance']

In [127]:
mar_cat_val[0]

'performance'

In [128]:
ni_200sx_mar_cat = (df.make == 'nissan') & (df.model == '200sx')

In [129]:
df.loc[ni_200sx_mar_cat,'market_category'] = df.loc[ni_200sx_mar_cat,'market_category'].fillna(mar_cat_val[0])
df[(df.make == 'nissan') & (df.model == '200sx')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
87,nissan,200sx,1996,regular_unleaded,115.0,4.0,manual,front_wheel_drive,2.0,performance,compact,coupe,36,26,2009,2000,22
88,nissan,200sx,1996,regular_unleaded,115.0,4.0,manual,front_wheel_drive,2.0,performance,compact,coupe,36,26,2009,2000,22
89,nissan,200sx,1996,regular_unleaded,140.0,4.0,manual,front_wheel_drive,2.0,performance,compact,coupe,29,21,2009,2000,22
90,nissan,200sx,1997,regular_unleaded,140.0,4.0,manual,front_wheel_drive,2.0,performance,compact,coupe,29,21,2009,2000,21
91,nissan,200sx,1997,regular_unleaded,115.0,4.0,manual,front_wheel_drive,2.0,performance,compact,coupe,35,25,2009,2000,21
92,nissan,200sx,1997,regular_unleaded,115.0,4.0,manual,front_wheel_drive,2.0,performance,compact,coupe,35,25,2009,2000,21
93,nissan,200sx,1998,regular_unleaded,115.0,4.0,manual,front_wheel_drive,2.0,performance,compact,coupe,35,25,2009,2000,20
94,nissan,200sx,1998,regular_unleaded,115.0,4.0,manual,front_wheel_drive,2.0,performance,compact,coupe,35,25,2009,2000,20
95,nissan,200sx,1998,regular_unleaded,140.0,4.0,manual,front_wheel_drive,2.0,performance,compact,coupe,28,20,2009,2073,20

In [130]:
dum_df = df[df['market_category'].isnull()]
dum_df

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
203,chrysler,300,2015,regular_unleaded,300.0,6.0,automatic,all_wheel_drive,4.0,NaN,large,sedan,27,18,1013,37570,3
204,chrysler,300,2015,regular_unleaded,292.0,6.0,automatic,rear_wheel_drive,4.0,NaN,large,sedan,31,19,1013,31695,3
205,chrysler,300,2015,regular_unleaded,292.0,6.0,automatic,rear_wheel_drive,4.0,NaN,large,sedan,31,19,1013,38070,3
206,chrysler,300,2015,regular_unleaded,292.0,6.0,automatic,all_wheel_drive,4.0,NaN,large,sedan,27,18,1013,44895,3
209,chrysler,300,2015,regular_unleaded,292.0,6.0,automatic,all_wheel_drive,4.0,NaN,large,sedan,27,18,1013,34195,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11794,subaru,xt,1991,regular_unleaded,145.0,6.0,manual,all_wheel_drive,2.0,NaN,compact,coupe,23,16,640,2000,27
11809,toyota,yaris_ia,2017,regular_unleaded,106.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,39,30,2031,15950,1
11810,toyota,yaris_ia,2017,regular_unleaded,106.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,40,32,2031,17050,1
11867,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,4dr_suv,21,15,549,64520,3
11868,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,21,14,549,67520,3

In [131]:
df[(df.make == 'chrysler') & (df.model == '300')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
203,chrysler,300,2015,regular_unleaded,300.0,6.0,automatic,all_wheel_drive,4.0,NaN,large,sedan,27,18,1013,37570,3
204,chrysler,300,2015,regular_unleaded,292.0,6.0,automatic,rear_wheel_drive,4.0,NaN,large,sedan,31,19,1013,31695,3
205,chrysler,300,2015,regular_unleaded,292.0,6.0,automatic,rear_wheel_drive,4.0,NaN,large,sedan,31,19,1013,38070,3
206,chrysler,300,2015,regular_unleaded,292.0,6.0,automatic,all_wheel_drive,4.0,NaN,large,sedan,27,18,1013,44895,3
207,chrysler,300,2015,regular_unleaded,300.0,6.0,automatic,rear_wheel_drive,4.0,performance,large,sedan,31,19,1013,35070,3
208,chrysler,300,2015,regular_unleaded,292.0,6.0,automatic,rear_wheel_drive,4.0,performance,large,sedan,31,19,1013,42395,3
209,chrysler,300,2015,regular_unleaded,292.0,6.0,automatic,all_wheel_drive,4.0,NaN,large,sedan,27,18,1013,34195,3
210,chrysler,300,2015,regular_unleaded,292.0,6.0,automatic,all_wheel_drive,4.0,NaN,large,sedan,27,18,1013,40570,3
211,chrysler,300,2016,regular_unleaded,300.0,6.0,automatic,all_wheel_drive,4.0,NaN,large,sedan,27,18,1013,38095,2
212,chrysler,300,2016,regular_unleaded,300.0,6.0,automatic,rear_wheel_drive,4.0,performance,large,sedan,31,19,1013,35595,2
213,chrysler,300,2016,regular_unleaded,292.0,6.0,automatic,all_wheel_drive,4.0,NaN,large,sedan,27,18,1013,45190,2
214,chrysler,300,2016,regular_unleaded,292.0,6.0,automatic,rear_wheel_drive,4.0,NaN,large,sedan,31,19,1013,32260,2
215,chrysler,300,2016,regular_unleaded,292.0,6.0,automatic,all_wheel_drive,4.0,NaN,large,sedan,27,18,1013,37755,2
216,chrysler,300,2016,regular_unleaded,292.0,6.0,automatic,all_wheel_drive,4.0,NaN,large,sedan,27,18,1013,41055,2
217,chrysler,300,2016,regular_unleaded,300.0,6.0,automatic,rear_wheel_drive,4.0,performance,large,sedan,31,19,1013,36090,2
218,chrysler,300,2016,regular_unleaded,292.0,6.0,automatic,rear_wheel_drive,4.0,performance,large,sedan,31,19,1013,42690,2
219,chrysler,300,2016,regular_unleaded,292.0,6.0,automatic,rear_wheel_drive,4.0,NaN,large,sedan,31,19,1013,38555,2
220,chrysler,300,2016,regular_unleaded,292.0,6.0,automatic,rear_wheel_drive,4.0,NaN,large,sedan,31,19,1013,35255,2
221,chrysler,300,2016,regular_unleaded,300.0,6.0,automatic,all_wheel_drive,4.0,NaN,large,sedan,27,18,1013,38590,2
222,chrysler,300,2016,regular_unleaded,292.0,6.0,automatic,all_wheel_drive,4.0,NaN,large,sedan,27,18,1013,34760,2
223,chrysler,300,2017,regular_unleaded,292.0,6.0,automatic,all_wheel_drive,4.0,NaN,large,sedan,27,18,1013,41135,1
224,chrysler,300,2017,regular_unleaded,292.0,6.0,automatic,all_wheel_drive,4.0,NaN,large,sedan,27,18,1013,45270,1
225,chrysler,300,2017,regular_unleaded,300.0,6.0,automatic,all_wheel_drive,4.0,NaN,large,sedan,27,18,1013,38670,1
226,chrysler,300,2017,regular_unleaded,292.0,6.0,automatic,rear_wheel_drive,4.0,performance,large,sedan,30,19,1013,38635,1
227,chrysler,300,2017,regular_unleaded,300.0,6.0,automatic,rear_wheel_drive,4.0,performance,large,sedan,30,19,1013,36170,1
228,chrysler,300,2017,regular_unleaded,300.0,6.0,automatic,all_wheel_drive,4.0,NaN,large,sedan,27,18,1013,38175,1
229,chrysler,300,2017,regular_unleaded,292.0,6.0,automatic,rear_wheel_drive,4.0,NaN,large,sedan,30,19,1013,32340,1
230,chrysler,300,2017,regular_unleaded,292.0,6.0,automatic,rear_wheel_drive,4.0,performance,large,sedan,30,19,1013,42770,1
231,chrysler,300,2017,regular_unleaded,292.0,6.0,automatic,all_wheel_drive,4.0,NaN,large,sedan,27,18,1013,34840,1
232,chrysler,300,2017,regular_unleaded,300.0,6.0,automatic,rear_wheel_drive,4.0,performance,large,sedan,30,19,1013,35675,1

In [132]:
lst_300_ = list(df[(df.make == 'chrysler') & (df.model == '300')]['market_category'].unique())
lst_300_

[nan, 'performance']

In [133]:
mar_cat_val_2 = [x for x in lst_200x_ if isinstance(x, str)]
mar_cat_val_2

['performance']

In [134]:
mar_cat_val_2[0]

'performance'

In [135]:
chrysler_300_mar_cat = (df.make == 'chrysler') & (df.model == '300')

In [136]:
df.loc[chrysler_300_mar_cat,'market_category'] = df.loc[chrysler_300_mar_cat,'market_category'].fillna(mar_cat_val_2[0])
df[(df.make == 'chrysler') & (df.model == '300s')]

Empty DataFrame
Columns: [make, model, year, engine_fuel_type, engine_hp, engine_cylinders, transmission_type, driven_wheels, number_of_doors, market_category, vehicle_size, vehicle_style, highway_mpg, city_mpg, popularity, msrp, age]
Index: []

In [137]:
dum_df = df[df['market_category'].isnull()]
dum_df

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
360,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,41,30,586,23795,3
361,mazda,3,2015,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,41,29,586,19595,3
362,mazda,3,2015,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,41,29,586,18445,3
368,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,41,30,586,19495,3
373,mazda,3,2015,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,41,29,586,16945,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11794,subaru,xt,1991,regular_unleaded,145.0,6.0,manual,all_wheel_drive,2.0,NaN,compact,coupe,23,16,640,2000,27
11809,toyota,yaris_ia,2017,regular_unleaded,106.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,39,30,2031,15950,1
11810,toyota,yaris_ia,2017,regular_unleaded,106.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,40,32,2031,17050,1
11867,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,4dr_suv,21,15,549,64520,3
11868,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,21,14,549,67520,3

In [138]:
lst_3_ = list(df[(df.make == 'mazda') & (df.model == '3')]['market_category'].unique())
lst_3_

['performance', nan, 'hatchback,performance', 'hatchback']

In [139]:
df[(df.make == 'mazda') & (df.model == '3') & (df.transmission_type == 'automatic') & (df.vehicle_style == 'sedan')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
359,mazda,3,2015,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,39,28,586,26095,3
360,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,41,30,586,23795,3
365,mazda,3,2015,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,39,28,586,24895,3
368,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,41,30,586,19495,3
375,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,41,30,586,20645,3
379,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,41,30,586,17995,3
381,mazda,3,2016,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,41,30,586,21095,2
385,mazda,3,2016,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,41,30,586,23595,2
390,mazda,3,2016,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,41,30,586,18895,2
394,mazda,3,2016,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,39,28,586,25795,2
397,mazda,3,2016,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,39,28,586,24795,2
398,mazda,3,2017,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,37,28,586,21495,1
401,mazda,3,2017,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,36,27,586,24195,1
407,mazda,3,2017,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,37,28,586,18895,1

In [140]:
mazda_3_mar_cat = (df.make == 'mazda') & (df.model == '3') & (df.transmission_type == 'automatic') & (df.vehicle_style == 'sedan')

In [141]:
df.loc[mazda_3_mar_cat,'market_category'] = df.loc[mazda_3_mar_cat,'market_category'].fillna('performance')
df[(df.make == 'mazda') & (df.model == '3') & (df.transmission_type == 'automatic') & (df.vehicle_style == 'sedan')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
359,mazda,3,2015,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,39,28,586,26095,3
360,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,41,30,586,23795,3
365,mazda,3,2015,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,39,28,586,24895,3
368,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,41,30,586,19495,3
375,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,41,30,586,20645,3
379,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,41,30,586,17995,3
381,mazda,3,2016,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,41,30,586,21095,2
385,mazda,3,2016,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,41,30,586,23595,2
390,mazda,3,2016,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,41,30,586,18895,2
394,mazda,3,2016,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,39,28,586,25795,2
397,mazda,3,2016,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,39,28,586,24795,2
398,mazda,3,2017,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,37,28,586,21495,1
401,mazda,3,2017,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,36,27,586,24195,1
407,mazda,3,2017,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,37,28,586,18895,1

In [142]:
df[(df.make == 'mazda') & (df.model == '3') & (df.transmission_type == 'automatic') & (df.vehicle_style == '4dr_hatchback') &(df.engine_hp == 155.0)]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
367,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,40,30,586,24295,3
370,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,40,30,586,19995,3
371,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,40,30,586,21145,3
384,mazda,3,2016,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,40,30,586,24295,2
386,mazda,3,2016,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,40,30,586,21795,2
391,mazda,3,2016,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,40,30,586,19595,2
402,mazda,3,2017,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,37,28,586,20145,1
408,mazda,3,2017,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,37,28,586,22245,1

In [143]:
mazda_3_mar_cat_last = (df.make == 'mazda') & (df.model == '3') & (df.transmission_type == 'automatic') & (df.vehicle_style == '4dr_hatchback') &(df.engine_hp == 155.0)
mazda_3_mar_cat_last

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [144]:
du = (df.make == 'mazda') & (df.model == '3') & (df['market_category'].isnull())

In [145]:
df.loc[du, 'market_category'] = df.loc[du, 'market_category'].fillna('hatchback')

In [146]:
df[(df.make == 'mazda') & (df.model == '3')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
358,mazda,3,2015,regular_unleaded,184.0,4.0,manual,front_wheel_drive,4.0,performance,compact,sedan,37,25,586,25045,3
359,mazda,3,2015,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,39,28,586,26095,3
360,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,41,30,586,23795,3
361,mazda,3,2015,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,sedan,41,29,586,19595,3
362,mazda,3,2015,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,sedan,41,29,586,18445,3
363,mazda,3,2015,regular_unleaded,184.0,4.0,manual,front_wheel_drive,4.0,performance,compact,sedan,37,25,586,23845,3
364,mazda,3,2015,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,"hatchback,performance",compact,4dr_hatchback,37,27,586,25395,3
365,mazda,3,2015,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,39,28,586,24895,3
366,mazda,3,2015,regular_unleaded,184.0,4.0,manual,front_wheel_drive,4.0,"hatchback,performance",compact,4dr_hatchback,35,26,586,25545,3
367,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,40,30,586,24295,3
368,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,41,30,586,19495,3
369,mazda,3,2015,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,40,29,586,20095,3
370,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,40,30,586,19995,3
371,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,40,30,586,21145,3
372,mazda,3,2015,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,40,29,586,23245,3
373,mazda,3,2015,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,sedan,41,29,586,16945,3
374,mazda,3,2015,regular_unleaded,184.0,4.0,manual,front_wheel_drive,4.0,"hatchback,performance",compact,4dr_hatchback,35,26,586,24345,3
375,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,41,30,586,20645,3
376,mazda,3,2015,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,40,29,586,18945,3
377,mazda,3,2015,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,"hatchback,performance",compact,4dr_hatchback,37,27,586,26595,3
378,mazda,3,2015,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,sedan,41,29,586,22745,3
379,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,41,30,586,17995,3
380,mazda,3,2016,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,sedan,41,29,586,22545,2
381,mazda,3,2016,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,41,30,586,21095,2
382,mazda,3,2016,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,"hatchback,performance",compact,4dr_hatchback,37,27,586,25495,2
383,mazda,3,2016,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,40,29,586,20745,2
384,mazda,3,2016,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,40,30,586,24295,2
385,mazda,3,2016,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,41,30,586,23595,2
386,mazda,3,2016,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,40,30,586,21795,2
387,mazda,3,2016,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,sedan,41,29,586,17845,2
388,mazda,3,2016,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,"hatchback,performance",compact,4dr_hatchback,37,27,586,26495,2
389,mazda,3,2016,regular_unleaded,184.0,4.0,manual,front_wheel_drive,4.0,performance,compact,sedan,37,25,586,24745,2
390,mazda,3,2016,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,41,30,586,18895,2
391,mazda,3,2016,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,40,30,586,19595,2
392,mazda,3,2016,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,40,29,586,23245,2
393,mazda,3,2016,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,40,29,586,18545,2
394,mazda,3,2016,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,39,28,586,25795,2
395,mazda,3,2016,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,sedan,41,29,586,20045,2
396,mazda,3,2016,regular_unleaded,184.0,4.0,manual,front_wheel_drive,4.0,"hatchback,performance",compact,4dr_hatchback,35,26,586,25445,2
397,mazda,3,2016,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,39,28,586,24795,2
398,mazda,3,2017,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,37,28,586,21495,1
399,mazda,3,2017,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,midsize,sedan,37,27,586,17845,1
400,mazda,3,2017,regular_unleaded,184.0,4.0,manual,front_wheel_drive,4.0,performance,midsize,sedan,34,25,586,23145,1
401,mazda,3,2017,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,36,27,586,24195,1
402,mazda,3,2017,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,37,28,586,20145,1
403,mazda,3,2017,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,"hatchback,performance",compact,4dr_hatchback,35,26,586,24945,1
404,mazda,3,2017,regular_unleaded,184.0,4.0,manual,front_wheel_drive,4.0,"hatchback,performance",compact,4dr_hatchback,33,25,586,23895,1
405,mazda,3,2017,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,37,27,586,19095,1
406,mazda,3,2017,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,"hatchback,performance",compact,4dr_hatchback,35,26,586,23445,1
407,mazda,3,2017,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,37,28,586,18895,1
408,mazda,3,2017,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,37,28,586,22245,1
409,mazda,3,2017,regular_unleaded,184.0,4.0,manual,front_wheel_drive,4.0,"hatchback,performance",compact,4dr_hatchback,33,25,586,22395,1
410,mazda,3,2017,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,midsize,sedan,37,27,586,20445,1

In [147]:
dum_df = df[df['market_category'].isnull()]
dum_df

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
479,toyota,4runner,2014,regular_unleaded,270.0,6.0,automatic,rear_wheel_drive,4.0,NaN,midsize,4dr_suv,23,17,2031,41365,4
480,toyota,4runner,2014,regular_unleaded,270.0,6.0,automatic,rear_wheel_drive,4.0,NaN,midsize,4dr_suv,23,17,2031,35740,4
481,toyota,4runner,2014,regular_unleaded,270.0,6.0,automatic,four_wheel_drive,4.0,NaN,midsize,4dr_suv,22,17,2031,37615,4
482,toyota,4runner,2014,regular_unleaded,270.0,6.0,automatic,four_wheel_drive,4.0,NaN,midsize,4dr_suv,22,17,2031,34695,4
483,toyota,4runner,2014,regular_unleaded,270.0,6.0,automatic,four_wheel_drive,4.0,NaN,midsize,4dr_suv,22,17,2031,35725,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11794,subaru,xt,1991,regular_unleaded,145.0,6.0,manual,all_wheel_drive,2.0,NaN,compact,coupe,23,16,640,2000,27
11809,toyota,yaris_ia,2017,regular_unleaded,106.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,39,30,2031,15950,1
11810,toyota,yaris_ia,2017,regular_unleaded,106.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,40,32,2031,17050,1
11867,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,4dr_suv,21,15,549,64520,3
11868,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,21,14,549,67520,3

In [148]:
list(df[(df.make == 'toyota') & (df.model == '4runner')]['market_category'].unique())

[nan]

In [149]:
df[(df.make == 'toyota') & df['market_category'].isnull()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
479,toyota,4runner,2014,regular_unleaded,270.0,6.0,automatic,rear_wheel_drive,4.0,NaN,midsize,4dr_suv,23,17,2031,41365,4
480,toyota,4runner,2014,regular_unleaded,270.0,6.0,automatic,rear_wheel_drive,4.0,NaN,midsize,4dr_suv,23,17,2031,35740,4
481,toyota,4runner,2014,regular_unleaded,270.0,6.0,automatic,four_wheel_drive,4.0,NaN,midsize,4dr_suv,22,17,2031,37615,4
482,toyota,4runner,2014,regular_unleaded,270.0,6.0,automatic,four_wheel_drive,4.0,NaN,midsize,4dr_suv,22,17,2031,34695,4
483,toyota,4runner,2014,regular_unleaded,270.0,6.0,automatic,four_wheel_drive,4.0,NaN,midsize,4dr_suv,22,17,2031,35725,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11061,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,crew_cab_pickup,17,13,2031,46010,1
11062,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,crew_cab_pickup,18,13,2031,41145,1
11064,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,crew_cab_pickup,17,13,2031,38470,1
11809,toyota,yaris_ia,2017,regular_unleaded,106.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,39,30,2031,15950,1
11810,toyota,yaris_ia,2017,regular_unleaded,106.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,40,32,2031,17050,1

In [150]:
df[(df.make == 'toyota') & (df.engine_fuel_type == 'regular_unleaded') & (df.vehicle_size == 'midsize') & (df.engine_cylinders == 6)]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
479,toyota,4runner,2014,regular_unleaded,270.0,6.0,automatic,rear_wheel_drive,4.0,NaN,midsize,4dr_suv,23,17,2031,41365,4
480,toyota,4runner,2014,regular_unleaded,270.0,6.0,automatic,rear_wheel_drive,4.0,NaN,midsize,4dr_suv,23,17,2031,35740,4
481,toyota,4runner,2014,regular_unleaded,270.0,6.0,automatic,four_wheel_drive,4.0,NaN,midsize,4dr_suv,22,17,2031,37615,4
482,toyota,4runner,2014,regular_unleaded,270.0,6.0,automatic,four_wheel_drive,4.0,NaN,midsize,4dr_suv,22,17,2031,34695,4
483,toyota,4runner,2014,regular_unleaded,270.0,6.0,automatic,four_wheel_drive,4.0,NaN,midsize,4dr_suv,22,17,2031,35725,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11283,toyota,venza,2014,regular_unleaded,268.0,6.0,automatic,all_wheel_drive,4.0,"crossover,performance",midsize,wagon,25,18,2031,31220,4
11285,toyota,venza,2014,regular_unleaded,268.0,6.0,automatic,front_wheel_drive,4.0,"crossover,performance",midsize,wagon,26,19,2031,38120,4
11288,toyota,venza,2015,regular_unleaded,268.0,6.0,automatic,all_wheel_drive,4.0,"crossover,performance",midsize,wagon,25,18,2031,35600,3
11290,toyota,venza,2015,regular_unleaded,268.0,6.0,automatic,all_wheel_drive,4.0,"crossover,performance",midsize,wagon,25,18,2031,39940,3
11293,toyota,venza,2015,regular_unleaded,268.0,6.0,automatic,front_wheel_drive,4.0,"crossover,performance",midsize,wagon,26,19,2031,34150,3

In [151]:
T1 = (df.make == 'toyota') & (df.engine_fuel_type == 'regular_unleaded') & (df.vehicle_size == 'midsize') & (df.engine_cylinders == 6)
T1

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [152]:
df.loc[T1, 'market_category'] = df.loc[T1, 'market_category'].fillna('crossover,performance')

In [153]:
df[(df.make == 'toyota') & (df.engine_fuel_type == 'regular_unleaded') & (df.vehicle_size == 'midsize') & (df.engine_cylinders == 6)]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
479,toyota,4runner,2014,regular_unleaded,270.0,6.0,automatic,rear_wheel_drive,4.0,"crossover,performance",midsize,4dr_suv,23,17,2031,41365,4
480,toyota,4runner,2014,regular_unleaded,270.0,6.0,automatic,rear_wheel_drive,4.0,"crossover,performance",midsize,4dr_suv,23,17,2031,35740,4
481,toyota,4runner,2014,regular_unleaded,270.0,6.0,automatic,four_wheel_drive,4.0,"crossover,performance",midsize,4dr_suv,22,17,2031,37615,4
482,toyota,4runner,2014,regular_unleaded,270.0,6.0,automatic,four_wheel_drive,4.0,"crossover,performance",midsize,4dr_suv,22,17,2031,34695,4
483,toyota,4runner,2014,regular_unleaded,270.0,6.0,automatic,four_wheel_drive,4.0,"crossover,performance",midsize,4dr_suv,22,17,2031,35725,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11283,toyota,venza,2014,regular_unleaded,268.0,6.0,automatic,all_wheel_drive,4.0,"crossover,performance",midsize,wagon,25,18,2031,31220,4
11285,toyota,venza,2014,regular_unleaded,268.0,6.0,automatic,front_wheel_drive,4.0,"crossover,performance",midsize,wagon,26,19,2031,38120,4
11288,toyota,venza,2015,regular_unleaded,268.0,6.0,automatic,all_wheel_drive,4.0,"crossover,performance",midsize,wagon,25,18,2031,35600,3
11290,toyota,venza,2015,regular_unleaded,268.0,6.0,automatic,all_wheel_drive,4.0,"crossover,performance",midsize,wagon,25,18,2031,39940,3
11293,toyota,venza,2015,regular_unleaded,268.0,6.0,automatic,front_wheel_drive,4.0,"crossover,performance",midsize,wagon,26,19,2031,34150,3

In [154]:
df[(df.make == 'toyota') & df['market_category'].isnull()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
2212,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,21855,12
2216,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,30,21,2031,21025,12
2218,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,20360,12
2219,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,30,21,2031,19530,12
2221,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,23405,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11061,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,crew_cab_pickup,17,13,2031,46010,1
11062,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,crew_cab_pickup,18,13,2031,41145,1
11064,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,crew_cab_pickup,17,13,2031,38470,1
11809,toyota,yaris_ia,2017,regular_unleaded,106.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,39,30,2031,15950,1
11810,toyota,yaris_ia,2017,regular_unleaded,106.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,40,32,2031,17050,1

In [155]:
df[(df.make == 'toyota') & (df.engine_fuel_type == 'regular_unleaded')  & (df.engine_cylinders == 8.0)]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
6347,toyota,land_cruiser,2015,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,4.0,luxury,midsize,4dr_suv,18,13,2031,80155,3
6348,toyota,land_cruiser,2016,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,4.0,luxury,midsize,4dr_suv,18,13,2031,83825,2
6349,toyota,land_cruiser,2017,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,4.0,luxury,midsize,4dr_suv,18,13,2031,84325,1
9114,toyota,sequoia,2015,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,17,13,2031,64320,3
9115,toyota,sequoia,2015,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,17,13,2031,47620,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11059,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,extended_cab_pickup,18,13,2031,39280,1
11060,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,extended_cab_pickup,17,13,2031,36150,1
11061,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,crew_cab_pickup,17,13,2031,46010,1
11062,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,crew_cab_pickup,18,13,2031,41145,1
11064,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,crew_cab_pickup,17,13,2031,38470,1

In [156]:
df[(df.vehicle_style == 'crew_cab_pickup') & (df.engine_fuel_type == 'regular_unleaded')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1777,subaru,baja,2004,regular_unleaded,165.0,4.0,automatic,all_wheel_drive,4.0,crossover,compact,crew_cab_pickup,25,19,640,22795,14
1780,subaru,baja,2004,regular_unleaded,165.0,4.0,manual,all_wheel_drive,4.0,crossover,compact,crew_cab_pickup,25,19,640,21995,14
1782,subaru,baja,2005,regular_unleaded,165.0,4.0,manual,all_wheel_drive,4.0,crossover,compact,crew_cab_pickup,25,19,640,22345,13
1786,subaru,baja,2005,regular_unleaded,165.0,4.0,automatic,all_wheel_drive,4.0,crossover,compact,crew_cab_pickup,25,19,640,23145,13
1788,subaru,baja,2006,regular_unleaded,165.0,4.0,manual,all_wheel_drive,4.0,crossover,compact,crew_cab_pickup,26,20,640,22495,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11047,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,crew_cab_pickup,18,13,2031,46980,1
11057,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,crew_cab_pickup,18,13,2031,35420,1
11061,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,crew_cab_pickup,17,13,2031,46010,1
11062,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,crew_cab_pickup,18,13,2031,41145,1
11064,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,crew_cab_pickup,17,13,2031,38470,1

In [157]:
T2 = (df.vehicle_style == 'crew_cab_pickup') & (df.engine_fuel_type == 'regular_unleaded') & (df.make == 'toyota')
T2

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [158]:
df.loc[T2, 'market_category'] = df.loc[T2, 'market_category'].fillna('crossover')
df[(df.vehicle_style == 'crew_cab_pickup') & (df.engine_fuel_type == 'regular_unleaded') & (df.make == 'toyota')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
10166,toyota,tacoma,2015,regular_unleaded,236.0,6.0,manual,four_wheel_drive,4.0,crossover,compact,crew_cab_pickup,19,15,2031,27355,3
10167,toyota,tacoma,2015,regular_unleaded,159.0,4.0,automatic,rear_wheel_drive,4.0,crossover,compact,crew_cab_pickup,24,19,2031,23075,3
10173,toyota,tacoma,2015,regular_unleaded,159.0,4.0,automatic,rear_wheel_drive,4.0,crossover,compact,crew_cab_pickup,24,19,2031,23625,3
10174,toyota,tacoma,2015,regular_unleaded,236.0,6.0,automatic,four_wheel_drive,4.0,crossover,compact,crew_cab_pickup,21,16,2031,37615,3
10175,toyota,tacoma,2015,regular_unleaded,236.0,6.0,automatic,rear_wheel_drive,4.0,crossover,compact,crew_cab_pickup,21,17,2031,25060,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11047,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,rear_wheel_drive,4.0,crossover,large,crew_cab_pickup,18,13,2031,46980,1
11057,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,rear_wheel_drive,4.0,crossover,large,crew_cab_pickup,18,13,2031,35420,1
11061,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,4.0,crossover,large,crew_cab_pickup,17,13,2031,46010,1
11062,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,rear_wheel_drive,4.0,crossover,large,crew_cab_pickup,18,13,2031,41145,1
11064,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,4.0,crossover,large,crew_cab_pickup,17,13,2031,38470,1

In [159]:
df[(df.make == 'toyota') & (df['market_category'].isnull())]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
2212,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,21855,12
2216,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,30,21,2031,21025,12
2218,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,20360,12
2219,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,30,21,2031,19530,12
2221,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,23405,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11058,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,extended_cab_pickup,17,13,2031,36480,1
11059,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,extended_cab_pickup,18,13,2031,39280,1
11060,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,extended_cab_pickup,17,13,2031,36150,1
11809,toyota,yaris_ia,2017,regular_unleaded,106.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,39,30,2031,15950,1
11810,toyota,yaris_ia,2017,regular_unleaded,106.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,40,32,2031,17050,1

In [160]:
T3 = (df.vehicle_style == 'extended_cab_pickup') & (df.engine_fuel_type == 'regular_unleaded') & (df.make == 'toyota')
T3

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [161]:
df.loc[T3, 'market_category'] = df.loc[T3, 'market_category'].fillna('crossover')
df[(df.vehicle_style == 'extended_cab_pickup') & (df.engine_fuel_type == 'regular_unleaded') & (df.make == 'toyota')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
7565,toyota,pickup,1993,regular_unleaded,150.0,6.0,manual,rear_wheel_drive,2.0,crossover,compact,extended_cab_pickup,20,15,2031,2047,25
7566,toyota,pickup,1993,regular_unleaded,150.0,6.0,manual,four_wheel_drive,2.0,crossover,compact,extended_cab_pickup,17,14,2031,2550,25
7567,toyota,pickup,1993,regular_unleaded,150.0,6.0,manual,four_wheel_drive,2.0,crossover,compact,extended_cab_pickup,17,14,2031,2221,25
7568,toyota,pickup,1993,regular_unleaded,150.0,6.0,manual,rear_wheel_drive,2.0,crossover,compact,extended_cab_pickup,20,15,2031,2000,25
7569,toyota,pickup,1993,regular_unleaded,116.0,4.0,manual,four_wheel_drive,2.0,crossover,compact,extended_cab_pickup,20,17,2031,2142,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11055,toyota,tundra,2017,regular_unleaded,310.0,8.0,automatic,rear_wheel_drive,4.0,crossover,large,extended_cab_pickup,19,15,2031,30020,1
11056,toyota,tundra,2017,regular_unleaded,310.0,8.0,automatic,four_wheel_drive,4.0,crossover,large,extended_cab_pickup,18,14,2031,33070,1
11058,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,4.0,crossover,large,extended_cab_pickup,17,13,2031,36480,1
11059,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,rear_wheel_drive,4.0,crossover,large,extended_cab_pickup,18,13,2031,39280,1
11060,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,4.0,crossover,large,extended_cab_pickup,17,13,2031,36150,1

In [162]:
df[(df.make == 'toyota') & (df['market_category'].isnull())]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
2212,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,21855,12
2216,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,30,21,2031,21025,12
2218,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,20360,12
2219,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,30,21,2031,19530,12
2221,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,23405,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11013,toyota,tundra,2016,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,2.0,NaN,large,regular_cab_pickup,17,13,2031,33000,2
11017,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,2.0,NaN,large,regular_cab_pickup,17,13,2031,33450,1
11029,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,rear_wheel_drive,2.0,NaN,large,regular_cab_pickup,18,13,2031,30400,1
11809,toyota,yaris_ia,2017,regular_unleaded,106.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,39,30,2031,15950,1
11810,toyota,yaris_ia,2017,regular_unleaded,106.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,40,32,2031,17050,1

In [163]:
df[(df.vehicle_style == 'sedan') & (df.engine_cylinders == 4.0) & (df.engine_fuel_type == 'regular_unleaded') & (df.driven_wheels == 'front_wheel_drive')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
358,mazda,3,2015,regular_unleaded,184.0,4.0,manual,front_wheel_drive,4.0,performance,compact,sedan,37,25,586,25045,3
359,mazda,3,2015,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,39,28,586,26095,3
360,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,41,30,586,23795,3
361,mazda,3,2015,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,sedan,41,29,586,19595,3
362,mazda,3,2015,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,sedan,41,29,586,18445,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11359,nissan,versa,2017,regular_unleaded,109.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,36,27,2009,11990,1
11360,nissan,versa,2017,regular_unleaded,109.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,39,31,2009,14130,1
11361,nissan,versa,2017,regular_unleaded,109.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,39,31,2009,15720,1
11809,toyota,yaris_ia,2017,regular_unleaded,106.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,39,30,2031,15950,1
11810,toyota,yaris_ia,2017,regular_unleaded,106.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,40,32,2031,17050,1

In [164]:
## performance has higher hp therefor we are choosing hatchback

T4 = (df.vehicle_style == 'sedan') & (df.vehicle_size == 'compact') &(df.engine_fuel_type == 'regular_unleaded') & (df.make == 'toyota')
T4

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [165]:
df.loc[T4, 'market_category'] = df.loc[T4, 'market_category'].fillna('hatchback')

In [166]:
df[(df.make == 'toyota') & df['market_category'].isnull()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
2212,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,21855,12
2216,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,30,21,2031,21025,12
2218,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,20360,12
2219,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,30,21,2031,19530,12
2221,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,23405,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10965,toyota,tundra,2015,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,2.0,NaN,large,regular_cab_pickup,17,13,2031,32170,3
11000,toyota,tundra,2016,regular_unleaded,381.0,8.0,automatic,rear_wheel_drive,2.0,NaN,large,regular_cab_pickup,18,13,2031,29950,2
11013,toyota,tundra,2016,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,2.0,NaN,large,regular_cab_pickup,17,13,2031,33000,2
11017,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,2.0,NaN,large,regular_cab_pickup,17,13,2031,33450,1
11029,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,rear_wheel_drive,2.0,NaN,large,regular_cab_pickup,18,13,2031,30400,1

In [167]:
df[(df.vehicle_style == 'regular_cab_pickup') & (df.engine_fuel_type == 'regular_unleaded') & (df.make == 'toyota')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
7570,toyota,pickup,1993,regular_unleaded,116.0,4.0,manual,four_wheel_drive,2.0,NaN,compact,regular_cab_pickup,20,17,2031,2013,25
7572,toyota,pickup,1994,regular_unleaded,150.0,6.0,manual,four_wheel_drive,2.0,NaN,compact,regular_cab_pickup,17,14,2031,2281,24
7573,toyota,pickup,1994,regular_unleaded,116.0,4.0,manual,rear_wheel_drive,2.0,NaN,compact,regular_cab_pickup,25,19,2031,2000,24
7574,toyota,pickup,1994,regular_unleaded,116.0,4.0,manual,rear_wheel_drive,2.0,NaN,compact,regular_cab_pickup,25,19,2031,2000,24
7575,toyota,pickup,1994,regular_unleaded,116.0,4.0,manual,four_wheel_drive,2.0,NaN,compact,regular_cab_pickup,20,17,2031,2115,24
7585,toyota,pickup,1995,regular_unleaded,116.0,4.0,manual,four_wheel_drive,2.0,NaN,compact,regular_cab_pickup,20,17,2031,2409,23
7587,toyota,pickup,1995,regular_unleaded,116.0,4.0,manual,rear_wheel_drive,2.0,NaN,compact,regular_cab_pickup,25,19,2031,2000,23
7589,toyota,pickup,1995,regular_unleaded,150.0,6.0,manual,four_wheel_drive,2.0,NaN,compact,regular_cab_pickup,17,14,2031,2539,23
7590,toyota,pickup,1995,regular_unleaded,116.0,4.0,manual,rear_wheel_drive,2.0,NaN,compact,regular_cab_pickup,25,19,2031,2000,23
10154,toyota,t100,1996,regular_unleaded,150.0,4.0,manual,rear_wheel_drive,2.0,NaN,large,regular_cab_pickup,22,18,2031,2141,22
10158,toyota,t100,1997,regular_unleaded,150.0,4.0,manual,rear_wheel_drive,2.0,NaN,large,regular_cab_pickup,22,17,2031,2348,21
10161,toyota,t100,1998,regular_unleaded,150.0,4.0,manual,rear_wheel_drive,2.0,NaN,large,regular_cab_pickup,22,17,2031,2540,20
10928,toyota,tundra,2015,regular_unleaded,381.0,8.0,automatic,rear_wheel_drive,2.0,NaN,large,regular_cab_pickup,18,13,2031,29120,3
10965,toyota,tundra,2015,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,2.0,NaN,large,regular_cab_pickup,17,13,2031,32170,3
11000,toyota,tundra,2016,regular_unleaded,381.0,8.0,automatic,rear_wheel_drive,2.0,NaN,large,regular_cab_pickup,18,13,2031,29950,2
11013,toyota,tundra,2016,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,2.0,NaN,large,regular_cab_pickup,17,13,2031,33000,2
11017,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,four_wheel_drive,2.0,NaN,large,regular_cab_pickup,17,13,2031,33450,1
11029,toyota,tundra,2017,regular_unleaded,381.0,8.0,automatic,rear_wheel_drive,2.0,NaN,large,regular_cab_pickup,18,13,2031,30400,1

In [168]:
T5 = (df.vehicle_style == 'regular_cab_pickup') & (df.engine_fuel_type == 'regular_unleaded') & (df.make == 'toyota')
T5

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [169]:
df.loc[T5, 'market_category'] = df.loc[T5, 'market_category'].fillna('crossover')

In [170]:
df[(df.make == 'toyota') & (df['market_category'].isnull())]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
2212,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,21855,12
2216,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,30,21,2031,21025,12
2218,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,20360,12
2219,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,30,21,2031,19530,12
2221,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,23405,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10330,toyota,tercel,1996,regular_unleaded,93.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,35,27,2031,2000,22
10332,toyota,tercel,1996,regular_unleaded,93.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,36,29,2031,2000,22
10333,toyota,tercel,1997,regular_unleaded,93.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,35,28,2031,2012,21
10335,toyota,tercel,1997,regular_unleaded,93.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,35,28,2031,2000,21
10336,toyota,tercel,1998,regular_unleaded,93.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,35,27,2031,2148,20

In [171]:
df[(df.driven_wheels == 'front_wheel_drive') & (df.number_of_doors == 2.0) & (df.engine_fuel_type == 'regular_unleaded') & (df.vehicle_style == 'coupe') & (df.vehicle_size == 'compact')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
87,nissan,200sx,1996,regular_unleaded,115.0,4.0,manual,front_wheel_drive,2.0,performance,compact,coupe,36,26,2009,2000,22
88,nissan,200sx,1996,regular_unleaded,115.0,4.0,manual,front_wheel_drive,2.0,performance,compact,coupe,36,26,2009,2000,22
89,nissan,200sx,1996,regular_unleaded,140.0,4.0,manual,front_wheel_drive,2.0,performance,compact,coupe,29,21,2009,2000,22
90,nissan,200sx,1997,regular_unleaded,140.0,4.0,manual,front_wheel_drive,2.0,performance,compact,coupe,29,21,2009,2000,21
91,nissan,200sx,1997,regular_unleaded,115.0,4.0,manual,front_wheel_drive,2.0,performance,compact,coupe,35,25,2009,2000,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10333,toyota,tercel,1997,regular_unleaded,93.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,35,28,2031,2012,21
10335,toyota,tercel,1997,regular_unleaded,93.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,35,28,2031,2000,21
10336,toyota,tercel,1998,regular_unleaded,93.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,35,27,2031,2148,20
11792,subaru,xt,1991,regular_unleaded,97.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,29,22,640,2000,27
11793,subaru,xt,1991,regular_unleaded,145.0,6.0,automatic,front_wheel_drive,2.0,NaN,compact,coupe,26,18,640,2000,27

In [172]:
T6 = (df.driven_wheels == 'front_wheel_drive') & (df.number_of_doors == 2.0) & (df.engine_fuel_type == 'regular_unleaded') & (df.vehicle_style == 'coupe') & (df.vehicle_size == 'compact') & (df.make == 'toyota')
T6

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [173]:
df.loc[T6, 'market_category'] = df.loc[T6, 'market_category'].fillna('performance')

In [174]:
df[(df.make == 'toyota') & (df['market_category'].isnull())]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
2212,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,21855,12
2216,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,30,21,2031,21025,12
2218,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,20360,12
2219,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,30,21,2031,19530,12
2221,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,23405,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9248,toyota,sienna,2017,regular_unleaded,296.0,6.0,automatic,front_wheel_drive,4.0,NaN,large,passenger_minivan,27,19,2031,40830,1
9249,toyota,sienna,2017,regular_unleaded,296.0,6.0,automatic,front_wheel_drive,4.0,NaN,large,passenger_minivan,27,19,2031,27645,1
9250,toyota,sienna,2017,regular_unleaded,296.0,6.0,automatic,all_wheel_drive,4.0,NaN,large,passenger_minivan,24,18,2031,38520,1
9251,toyota,sienna,2017,regular_unleaded,296.0,6.0,automatic,front_wheel_drive,4.0,NaN,large,passenger_minivan,27,19,2031,46170,1
9252,toyota,sienna,2017,regular_unleaded,296.0,6.0,automatic,all_wheel_drive,4.0,NaN,large,passenger_minivan,24,18,2031,47310,1

In [175]:
df[(df.vehicle_style == 'coupe') & (df.vehicle_size == 'midsize') & (df.driven_wheels == 'front_wheel_drive') & (df.engine_cylinders == 4.0)]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1215,honda,accord,2015,regular_unleaded,185.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,34,24,2202,23775,3
1216,honda,accord,2015,regular_unleaded,185.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,35,26,2202,26300,3
1218,honda,accord,2015,regular_unleaded,185.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,34,24,2202,25450,3
1222,honda,accord,2015,regular_unleaded,185.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,35,26,2202,30270,3
1224,honda,accord,2015,regular_unleaded,185.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,35,26,2202,28495,3
1230,honda,accord,2015,regular_unleaded,185.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,35,26,2202,24625,3
1235,honda,accord,2016,regular_unleaded,185.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,35,26,2202,26850,2
1240,honda,accord,2016,regular_unleaded,185.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,35,26,2202,27850,2
1241,honda,accord,2016,regular_unleaded,185.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,35,26,2202,24725,2
1244,honda,accord,2016,regular_unleaded,185.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,35,26,2202,30845,2
1247,honda,accord,2016,regular_unleaded,185.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,34,23,2202,23875,2
1248,honda,accord,2016,regular_unleaded,185.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,35,26,2202,28845,2
1250,honda,accord,2016,regular_unleaded,185.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,34,23,2202,26000,2
1251,honda,accord,2016,regular_unleaded,185.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,35,26,2202,25725,2
1260,honda,accord,2017,regular_unleaded,185.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,32,23,2202,24025,1
1261,honda,accord,2017,regular_unleaded,185.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,34,26,2202,30995,1
1264,honda,accord,2017,regular_unleaded,185.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,32,23,2202,26150,1
1274,honda,accord,2017,regular_unleaded,185.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,34,26,2202,27000,1
1275,honda,accord,2017,regular_unleaded,185.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,34,26,2202,28000,1
1277,honda,accord,2017,regular_unleaded,185.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,34,26,2202,28995,1
1280,honda,accord,2017,regular_unleaded,185.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,34,26,2202,25875,1
1286,honda,accord,2017,regular_unleaded,185.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,34,26,2202,24875,1
1288,oldsmobile,achieva,1996,regular_unleaded,150.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,26,2000,22
1289,oldsmobile,achieva,1997,regular_unleaded,150.0,4.0,unknown,front_wheel_drive,2.0,NaN,midsize,coupe,29,19,26,2000,21
1348,oldsmobile,alero,2002,regular_unleaded,140.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,21,26,17805,16
1349,oldsmobile,alero,2002,regular_unleaded,140.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,21,26,19855,16
1352,oldsmobile,alero,2003,regular_unleaded,140.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,21,26,18085,15
1358,oldsmobile,alero,2003,regular_unleaded,140.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,21,26,20035,15
1362,oldsmobile,alero,2004,regular_unleaded,140.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,31,21,26,20435,14
1363,oldsmobile,alero,2004,regular_unleaded,140.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,31,21,26,18485,14
1958,chevrolet,beretta,1995,regular_unleaded,120.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,33,21,1385,2000,23
1960,chevrolet,beretta,1996,regular_unleaded,120.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,33,22,1385,2000,22
2212,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,21855,12
2216,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,30,21,2031,21025,12
2218,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,20360,12
2219,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,30,21,2031,19530,12
2221,toyota,camry_solara,2006,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,30,20,2031,23405,12
2222,toyota,camry_solara,2007,regular_unleaded,155.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,31,21,2031,19930,11
2225,toyota,camry_solara,2007,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,31,22,2031,20760,11
2226,toyota,camry_solara,2007,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,31,22,2031,23030,11
2228,toyota,camry_solara,2007,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,31,22,2031,23905,11
2232,toyota,camry_solara,2007,regular_unleaded,155.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,31,21,2031,22200,11
2234,toyota,camry_solara,2008,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,31,22,2031,24155,10
2235,toyota,camry_solara,2008,regular_unleaded,155.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,31,21,2031,22450,10
2239,toyota,camry_solara,2008,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,31,22,2031,21010,10
2241,toyota,camry_solara,2008,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,31,22,2031,23280,10
2243,toyota,camry_solara,2008,regular_unleaded,155.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,31,21,2031,20180,10
5192,pontiac,g6,2009,regular_unleaded,164.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,33,22,210,22220,9
9651,buick,skylark,1996,regular_unleaded,150.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,29,19,155,2000,22
9656,buick,skylark,1997,regular_unleaded,150.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,29,19,155,2000,21
10012,dodge,stratus,2004,regular_unleaded,147.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,29,21,1851,19850,14
10013,dodge,stratus,2004,regular_unleaded,142.0,4.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,26,19,1851,20675,14
10018,dodge,stratus,2005,regular_unleaded,147.0,4.0,manual,front_wheel_drive,2.0,NaN,midsize,coupe,29,21,1851,20135,13

In [176]:
df[(df.vehicle_style == 'coupe') & (df['market_category'].notnull()) & (df.engine_cylinders == 4.0) & (df.vehicle_size == 'midsize') & (df.engine_fuel_type == 'regular_unleaded')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
757,volvo,780,1990,regular_unleaded,188.0,4.0,automatic,rear_wheel_drive,2.0,luxury,midsize,coupe,20,16,870,2000,28
3036,volvo,coupe,1991,regular_unleaded,188.0,4.0,automatic,rear_wheel_drive,2.0,luxury,midsize,coupe,20,17,870,2000,27

In [177]:
T7 = (df.vehicle_style == 'coupe') & (df.vehicle_size == 'midsize') & (df.driven_wheels == 'front_wheel_drive') & (df.engine_cylinders == 4.0)
T7

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [178]:
df.loc[T7, 'market_category'] = df.loc[T7, 'market_category'].fillna('luxury')

In [179]:
df[df['market_category'].isnull()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
545,fiat,500,2015,premium_unleaded_(recommended),101.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,convertible,34,28,819,22800,3
546,fiat,500,2015,premium_unleaded_(recommended),101.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,convertible,34,28,819,24700,3
549,fiat,500,2015,premium_unleaded_(recommended),101.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,convertible,34,28,819,20345,3
558,fiat,500,2016,premium_unleaded_(recommended),101.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,convertible,40,31,819,24495,2
560,fiat,500,2016,premium_unleaded_(recommended),101.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,convertible,40,31,819,20395,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11792,subaru,xt,1991,regular_unleaded,97.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,29,22,640,2000,27
11793,subaru,xt,1991,regular_unleaded,145.0,6.0,automatic,front_wheel_drive,2.0,NaN,compact,coupe,26,18,640,2000,27
11794,subaru,xt,1991,regular_unleaded,145.0,6.0,manual,all_wheel_drive,2.0,NaN,compact,coupe,23,16,640,2000,27
11867,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,4dr_suv,21,15,549,64520,3
11868,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,21,14,549,67520,3

In [180]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   make               11914 non-null  object
 1   model              11914 non-null  object
 2   year               11914 non-null  int64
 3   engine_fuel_type   11914 non-null  object
 4   engine_hp          11914 non-null  float64
 5   engine_cylinders   11914 non-null  float64
 6   transmission_type  11914 non-null  object
 7   driven_wheels      11914 non-null  object
 8   number_of_doors    11914 non-null  object
 9   market_category    8599 non-null   object
 10  vehicle_size       11914 non-null  object
 11  vehicle_style      11914 non-null  object
 12  highway_mpg        11914 non-null  int64
 13  city_mpg           11914 non-null  int64
 14  popularity         11914 non-null  int64
 15  msrp               11914 non-null  int64
 16  age                11914 non-null  int64
dtypes: float64(2), int64(6), object(9)
memory usage: 1.5+ MB

In [181]:
df[(df.make == 'fiat') & (df.model == '500') & (df.vehicle_style == 'convertible')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
542,fiat,500,2015,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,2.0,"factory_tuner,performance",compact,convertible,34,28,819,26595,3
545,fiat,500,2015,premium_unleaded_(recommended),101.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,convertible,34,28,819,22800,3
546,fiat,500,2015,premium_unleaded_(recommended),101.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,convertible,34,28,819,24700,3
549,fiat,500,2015,premium_unleaded_(recommended),101.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,convertible,34,28,819,20345,3
553,fiat,500,2016,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,2.0,"factory_tuner,performance",compact,convertible,34,28,819,26695,2
558,fiat,500,2016,premium_unleaded_(recommended),101.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,convertible,40,31,819,24495,2
560,fiat,500,2016,premium_unleaded_(recommended),101.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,convertible,40,31,819,20395,2
563,fiat,500,2016,premium_unleaded_(recommended),101.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,convertible,40,31,819,21395,2
566,fiat,500,2017,premium_unleaded_(recommended),101.0,4.0,automatic,front_wheel_drive,2.0,NaN,compact,convertible,33,27,819,17485,1
567,fiat,500,2017,premium_unleaded_(recommended),101.0,4.0,automatic,front_wheel_drive,2.0,NaN,compact,convertible,33,27,819,20885,1
568,fiat,500,2017,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,2.0,"factory_tuner,performance",compact,convertible,33,28,819,21490,1

In [182]:
F1 = (df.make == 'fiat') & (df.model == '500') & (df.vehicle_style == 'convertible')
F1

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [183]:
df.loc[F1, 'market_category'] = df.loc[F1, 'market_category'].fillna('factory_tuner,performance')

In [184]:
df[(df.make == 'fiat') & (df.model == '500') & (df.vehicle_style == 'convertible')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
542,fiat,500,2015,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,2.0,"factory_tuner,performance",compact,convertible,34,28,819,26595,3
545,fiat,500,2015,premium_unleaded_(recommended),101.0,4.0,manual,front_wheel_drive,2.0,"factory_tuner,performance",compact,convertible,34,28,819,22800,3
546,fiat,500,2015,premium_unleaded_(recommended),101.0,4.0,manual,front_wheel_drive,2.0,"factory_tuner,performance",compact,convertible,34,28,819,24700,3
549,fiat,500,2015,premium_unleaded_(recommended),101.0,4.0,manual,front_wheel_drive,2.0,"factory_tuner,performance",compact,convertible,34,28,819,20345,3
553,fiat,500,2016,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,2.0,"factory_tuner,performance",compact,convertible,34,28,819,26695,2
558,fiat,500,2016,premium_unleaded_(recommended),101.0,4.0,manual,front_wheel_drive,2.0,"factory_tuner,performance",compact,convertible,40,31,819,24495,2
560,fiat,500,2016,premium_unleaded_(recommended),101.0,4.0,manual,front_wheel_drive,2.0,"factory_tuner,performance",compact,convertible,40,31,819,20395,2
563,fiat,500,2016,premium_unleaded_(recommended),101.0,4.0,manual,front_wheel_drive,2.0,"factory_tuner,performance",compact,convertible,40,31,819,21395,2
566,fiat,500,2017,premium_unleaded_(recommended),101.0,4.0,automatic,front_wheel_drive,2.0,"factory_tuner,performance",compact,convertible,33,27,819,17485,1
567,fiat,500,2017,premium_unleaded_(recommended),101.0,4.0,automatic,front_wheel_drive,2.0,"factory_tuner,performance",compact,convertible,33,27,819,20885,1
568,fiat,500,2017,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,2.0,"factory_tuner,performance",compact,convertible,33,28,819,21490,1

In [185]:
df[df['market_category'].isnull()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
570,fiat,500l,2015,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,33,25,819,19345,3
571,fiat,500l,2015,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,33,25,819,23095,3
572,fiat,500l,2015,premium_unleaded_(recommended),160.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,30,22,819,24695,3
573,fiat,500l,2015,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,33,25,819,21695,3
574,fiat,500l,2015,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,33,25,819,20695,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11792,subaru,xt,1991,regular_unleaded,97.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,29,22,640,2000,27
11793,subaru,xt,1991,regular_unleaded,145.0,6.0,automatic,front_wheel_drive,2.0,NaN,compact,coupe,26,18,640,2000,27
11794,subaru,xt,1991,regular_unleaded,145.0,6.0,manual,all_wheel_drive,2.0,NaN,compact,coupe,23,16,640,2000,27
11867,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,4dr_suv,21,15,549,64520,3
11868,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,21,14,549,67520,3

In [186]:
df[(df.make == 'fiat') & (df.model == '500l')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
570,fiat,500l,2015,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,33,25,819,19345,3
571,fiat,500l,2015,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,33,25,819,23095,3
572,fiat,500l,2015,premium_unleaded_(recommended),160.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,30,22,819,24695,3
573,fiat,500l,2015,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,33,25,819,21695,3
574,fiat,500l,2015,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,33,25,819,20695,3
575,fiat,500l,2016,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,33,25,819,21880,2
576,fiat,500l,2016,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,33,25,819,23395,2
577,fiat,500l,2016,premium_unleaded_(recommended),160.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,30,22,819,24795,2
578,fiat,500l,2016,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,33,25,819,20795,2
579,fiat,500l,2016,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,33,25,819,19495,2
580,fiat,500l,2017,premium_unleaded_(recommended),160.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,30,22,819,23695,1
581,fiat,500l,2017,premium_unleaded_(recommended),160.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,30,22,819,20995,1
582,fiat,500l,2017,premium_unleaded_(recommended),160.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,30,22,819,22995,1

In [187]:
df[(df['market_category'].notnull())& (df.vehicle_size == 'compact') & (df.engine_fuel_type == 'premium_unleaded_(recommended)') & (df.driven_wheels == 'front_wheel_drive') & (df.vehicle_style == 'wagon')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
824,saab,9-3,2009,premium_unleaded_(recommended),210.0,4.0,automatic,front_wheel_drive,4.0,luxury,compact,wagon,27,19,376,38305,9
829,saab,9-3,2009,premium_unleaded_(recommended),210.0,4.0,manual,front_wheel_drive,4.0,luxury,compact,wagon,29,19,376,31790,9
830,saab,9-3,2009,premium_unleaded_(recommended),210.0,4.0,automatic,front_wheel_drive,4.0,luxury,compact,wagon,27,19,376,35315,9
838,saab,9-3,2010,premium_unleaded_(recommended),207.0,4.0,manual,front_wheel_drive,4.0,luxury,compact,wagon,31,21,376,30330,8
844,saab,9-3,2010,premium_unleaded_(recommended),207.0,4.0,automatic,front_wheel_drive,4.0,luxury,compact,wagon,27,19,376,37020,8
849,saab,9-3,2011,premium_unleaded_(recommended),210.0,4.0,manual,front_wheel_drive,4.0,luxury,compact,wagon,31,21,376,30330,7
850,saab,9-3,2011,premium_unleaded_(recommended),210.0,4.0,automatic,front_wheel_drive,4.0,luxury,compact,wagon,27,19,376,37020,7
5710,chevrolet,hhr,2009,premium_unleaded_(recommended),260.0,4.0,manual,front_wheel_drive,4.0,"factory_tuner,performance",compact,wagon,29,21,1385,25135,9
5712,chevrolet,hhr,2009,premium_unleaded_(recommended),260.0,4.0,manual,front_wheel_drive,4.0,"factory_tuner,performance",compact,wagon,29,21,1385,24815,9
5717,chevrolet,hhr,2010,premium_unleaded_(recommended),260.0,4.0,manual,front_wheel_drive,4.0,"factory_tuner,performance",compact,wagon,29,21,1385,26255,8
11109,volvo,v50,2009,premium_unleaded_(recommended),168.0,5.0,automatic,front_wheel_drive,4.0,luxury,compact,wagon,31,20,870,29800,9
11112,volvo,v50,2010,premium_unleaded_(recommended),168.0,5.0,automatic,front_wheel_drive,4.0,luxury,compact,wagon,30,21,870,28700,8

In [188]:
F2 = (df.make == 'fiat') & (df.model == '500l')
F2

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [189]:
df.loc[F2, 'market_category'] = df.loc[F2, 'market_category'].fillna('luxury')
df[(df.make == 'fiat') & (df.model == '500l')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
570,fiat,500l,2015,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,4.0,luxury,compact,wagon,33,25,819,19345,3
571,fiat,500l,2015,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,4.0,luxury,compact,wagon,33,25,819,23095,3
572,fiat,500l,2015,premium_unleaded_(recommended),160.0,4.0,automatic,front_wheel_drive,4.0,luxury,compact,wagon,30,22,819,24695,3
573,fiat,500l,2015,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,4.0,luxury,compact,wagon,33,25,819,21695,3
574,fiat,500l,2015,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,4.0,luxury,compact,wagon,33,25,819,20695,3
575,fiat,500l,2016,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,4.0,luxury,compact,wagon,33,25,819,21880,2
576,fiat,500l,2016,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,4.0,luxury,compact,wagon,33,25,819,23395,2
577,fiat,500l,2016,premium_unleaded_(recommended),160.0,4.0,automatic,front_wheel_drive,4.0,luxury,compact,wagon,30,22,819,24795,2
578,fiat,500l,2016,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,4.0,luxury,compact,wagon,33,25,819,20795,2
579,fiat,500l,2016,premium_unleaded_(recommended),160.0,4.0,manual,front_wheel_drive,4.0,luxury,compact,wagon,33,25,819,19495,2
580,fiat,500l,2017,premium_unleaded_(recommended),160.0,4.0,automatic,front_wheel_drive,4.0,luxury,compact,wagon,30,22,819,23695,1
581,fiat,500l,2017,premium_unleaded_(recommended),160.0,4.0,automatic,front_wheel_drive,4.0,luxury,compact,wagon,30,22,819,20995,1
582,fiat,500l,2017,premium_unleaded_(recommended),160.0,4.0,automatic,front_wheel_drive,4.0,luxury,compact,wagon,30,22,819,22995,1

In [190]:
df[df['market_category'].isnull()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
623,mazda,5,2013,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,passenger_minivan,28,22,586,24470,5
624,mazda,5,2013,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,passenger_minivan,28,22,586,20940,5
625,mazda,5,2013,regular_unleaded,157.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,passenger_minivan,28,21,586,19940,5
626,mazda,5,2013,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,passenger_minivan,28,22,586,22070,5
627,mazda,5,2014,regular_unleaded,157.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,passenger_minivan,28,21,586,20140,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11792,subaru,xt,1991,regular_unleaded,97.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,29,22,640,2000,27
11793,subaru,xt,1991,regular_unleaded,145.0,6.0,automatic,front_wheel_drive,2.0,NaN,compact,coupe,26,18,640,2000,27
11794,subaru,xt,1991,regular_unleaded,145.0,6.0,manual,all_wheel_drive,2.0,NaN,compact,coupe,23,16,640,2000,27
11867,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,4dr_suv,21,15,549,64520,3
11868,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,21,14,549,67520,3

In [191]:
df[(df.make == 'mazda') & (df.model == '5')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
623,mazda,5,2013,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,passenger_minivan,28,22,586,24470,5
624,mazda,5,2013,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,passenger_minivan,28,22,586,20940,5
625,mazda,5,2013,regular_unleaded,157.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,passenger_minivan,28,21,586,19940,5
626,mazda,5,2013,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,passenger_minivan,28,22,586,22070,5
627,mazda,5,2014,regular_unleaded,157.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,passenger_minivan,28,21,586,20140,4
628,mazda,5,2014,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,passenger_minivan,28,22,586,24670,4
629,mazda,5,2014,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,passenger_minivan,28,22,586,21140,4
630,mazda,5,2014,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,passenger_minivan,28,22,586,22270,4
631,mazda,5,2015,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,passenger_minivan,28,21,586,24770,3
632,mazda,5,2015,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,passenger_minivan,28,21,586,22370,3
633,mazda,5,2015,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,passenger_minivan,28,21,586,21240,3

In [192]:
df[(df.make == 'mazda') & (df.engine_fuel_type == 'regular_unleaded') & (df.engine_cylinders == 4.0) & (df.driven_wheels == 'front_wheel_drive') & (df.vehicle_size == 'compact')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
112,mazda,2,2012,regular_unleaded,100.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,35,29,586,16020,6
113,mazda,2,2012,regular_unleaded,100.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,35,29,586,14530,6
114,mazda,2,2012,regular_unleaded,100.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,34,28,586,16860,6
115,mazda,2,2012,regular_unleaded,100.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,34,28,586,15370,6
116,mazda,2,2013,regular_unleaded,100.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,34,28,586,17050,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10818,mazda,tribute,2010,regular_unleaded,171.0,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,28,21,586,22445,8
10822,mazda,tribute,2011,regular_unleaded,171.0,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,28,21,586,25700,7
10824,mazda,tribute,2011,regular_unleaded,171.0,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,28,21,586,23740,7
10826,mazda,tribute,2011,regular_unleaded,171.0,4.0,automatic,front_wheel_drive,4.0,crossover,compact,4dr_suv,28,21,586,22595,7
10828,mazda,tribute,2011,regular_unleaded,171.0,4.0,manual,front_wheel_drive,4.0,crossover,compact,4dr_suv,28,23,586,20555,7

In [193]:
df[(df.engine_fuel_type == 'regular_unleaded') & (df.engine_cylinders == 4.0) & (df.driven_wheels == 'front_wheel_drive') & (df.vehicle_size == 'compact') & (df.number_of_doors == 4.0)]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
112,mazda,2,2012,regular_unleaded,100.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,35,29,586,16020,6
113,mazda,2,2012,regular_unleaded,100.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,35,29,586,14530,6
114,mazda,2,2012,regular_unleaded,100.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,34,28,586,16860,6
115,mazda,2,2012,regular_unleaded,100.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,34,28,586,15370,6
116,mazda,2,2013,regular_unleaded,100.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,34,28,586,17050,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11824,toyota,yaris,2016,regular_unleaded,106.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,36,30,2031,15995,2
11828,toyota,yaris,2017,regular_unleaded,106.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,35,30,2031,16375,1
11829,toyota,yaris,2017,regular_unleaded,106.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,35,30,2031,17285,1
11830,toyota,yaris,2017,regular_unleaded,106.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,35,30,2031,18000,1
11831,toyota,yaris,2017,regular_unleaded,106.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,4dr_hatchback,36,30,2031,17200,1

In [194]:
M_5 = (df.make == 'mazda') & (df.model == '5')
M_5

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [195]:
df.loc[M_5, 'market_category'] = df.loc[M_5, 'market_category'].fillna('hatchback')
df[(df.make == 'mazda') & (df.model == '5')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
623,mazda,5,2013,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,passenger_minivan,28,22,586,24470,5
624,mazda,5,2013,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,passenger_minivan,28,22,586,20940,5
625,mazda,5,2013,regular_unleaded,157.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,passenger_minivan,28,21,586,19940,5
626,mazda,5,2013,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,passenger_minivan,28,22,586,22070,5
627,mazda,5,2014,regular_unleaded,157.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,passenger_minivan,28,21,586,20140,4
628,mazda,5,2014,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,passenger_minivan,28,22,586,24670,4
629,mazda,5,2014,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,passenger_minivan,28,22,586,21140,4
630,mazda,5,2014,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,passenger_minivan,28,22,586,22270,4
631,mazda,5,2015,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,passenger_minivan,28,21,586,24770,3
632,mazda,5,2015,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,passenger_minivan,28,21,586,22370,3
633,mazda,5,2015,regular_unleaded,157.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,passenger_minivan,28,21,586,21240,3

In [196]:
df[df['market_category'].isnull()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
674,pontiac,6000,1990,regular_unleaded,140.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,27,17,210,2000,28
675,pontiac,6000,1990,regular_unleaded,110.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,29,20,210,2000,28
676,pontiac,6000,1990,regular_unleaded,140.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,wagon,27,17,210,2000,28
677,pontiac,6000,1990,regular_unleaded,140.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,wagon,27,17,210,2000,28
678,pontiac,6000,1990,regular_unleaded,140.0,6.0,automatic,all_wheel_drive,4.0,NaN,midsize,sedan,27,17,210,2000,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11792,subaru,xt,1991,regular_unleaded,97.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,29,22,640,2000,27
11793,subaru,xt,1991,regular_unleaded,145.0,6.0,automatic,front_wheel_drive,2.0,NaN,compact,coupe,26,18,640,2000,27
11794,subaru,xt,1991,regular_unleaded,145.0,6.0,manual,all_wheel_drive,2.0,NaN,compact,coupe,23,16,640,2000,27
11867,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,4dr_suv,21,15,549,64520,3
11868,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,21,14,549,67520,3

In [197]:
df[(df.make == 'pontiac') & (df.model == '6000')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
674,pontiac,6000,1990,regular_unleaded,140.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,27,17,210,2000,28
675,pontiac,6000,1990,regular_unleaded,110.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,29,20,210,2000,28
676,pontiac,6000,1990,regular_unleaded,140.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,wagon,27,17,210,2000,28
677,pontiac,6000,1990,regular_unleaded,140.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,wagon,27,17,210,2000,28
678,pontiac,6000,1990,regular_unleaded,140.0,6.0,automatic,all_wheel_drive,4.0,NaN,midsize,sedan,27,17,210,2000,28
679,pontiac,6000,1991,regular_unleaded,140.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,wagon,28,17,210,2000,27
680,pontiac,6000,1991,regular_unleaded,140.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,28,17,210,2000,27
681,pontiac,6000,1991,regular_unleaded,110.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,28,19,210,2000,27

In [198]:
df[(df.make == 'pontiac') & (df.engine_fuel_type == 'regular_unleaded') & (df['market_category'].notnull()) & (df.number_of_doors == 4.0) & (df.vehicle_size == 'midsize')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1670,pontiac,aztek,2003,regular_unleaded,185.0,6.0,automatic,all_wheel_drive,4.0,crossover,midsize,4dr_suv,22,16,210,23820,15
1671,pontiac,aztek,2003,regular_unleaded,185.0,6.0,automatic,front_wheel_drive,4.0,crossover,midsize,4dr_suv,24,17,210,20870,15
1672,pontiac,aztek,2004,regular_unleaded,185.0,6.0,automatic,all_wheel_drive,4.0,crossover,midsize,4dr_suv,22,16,210,24190,14
1673,pontiac,aztek,2004,regular_unleaded,185.0,6.0,automatic,front_wheel_drive,4.0,crossover,midsize,4dr_suv,24,17,210,21275,14
1674,pontiac,aztek,2005,regular_unleaded,185.0,6.0,automatic,all_wheel_drive,4.0,crossover,midsize,4dr_suv,22,16,210,24445,13
1675,pontiac,aztek,2005,regular_unleaded,185.0,6.0,automatic,front_wheel_drive,4.0,crossover,midsize,4dr_suv,24,17,210,21530,13
5183,pontiac,g6,2008,regular_unleaded,252.0,6.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,26,17,210,26960,10
5186,pontiac,g6,2008,regular_unleaded,219.0,6.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,26,17,210,23100,10
5187,pontiac,g6,2009,regular_unleaded,252.0,6.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,26,17,210,28580,9
5189,pontiac,g6,2009,regular_unleaded,221.0,6.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,26,17,210,24180,9
5195,pontiac,g6,2009,regular_unleaded,164.0,4.0,automatic,front_wheel_drive,4.0,flex_fuel,midsize,sedan,30,22,210,21165,9
5196,pontiac,g6,2009,regular_unleaded,252.0,6.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,26,17,210,29060,9
5504,pontiac,grand_prix,2006,regular_unleaded,303.0,8.0,automatic,front_wheel_drive,4.0,"factory_tuner,high-performance",midsize,sedan,25,16,210,27330,12
5506,pontiac,grand_prix,2007,regular_unleaded,303.0,8.0,automatic,front_wheel_drive,4.0,"factory_tuner,high-performance",midsize,sedan,25,16,210,28815,11

In [199]:
P_6000 = (df.make == 'pontiac') & (df.model == '6000')
P_6000

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [200]:
df.loc[P_6000, 'market_category'] = df.loc[P_6000, 'market_category'].fillna('performance')
df[(df.make == 'pontiac') & (df.model == '6000')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
674,pontiac,6000,1990,regular_unleaded,140.0,6.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,27,17,210,2000,28
675,pontiac,6000,1990,regular_unleaded,110.0,4.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,29,20,210,2000,28
676,pontiac,6000,1990,regular_unleaded,140.0,6.0,automatic,front_wheel_drive,4.0,performance,midsize,wagon,27,17,210,2000,28
677,pontiac,6000,1990,regular_unleaded,140.0,6.0,automatic,front_wheel_drive,4.0,performance,midsize,wagon,27,17,210,2000,28
678,pontiac,6000,1990,regular_unleaded,140.0,6.0,automatic,all_wheel_drive,4.0,performance,midsize,sedan,27,17,210,2000,28
679,pontiac,6000,1991,regular_unleaded,140.0,6.0,automatic,front_wheel_drive,4.0,performance,midsize,wagon,28,17,210,2000,27
680,pontiac,6000,1991,regular_unleaded,140.0,6.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,28,17,210,2000,27
681,pontiac,6000,1991,regular_unleaded,110.0,4.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,28,19,210,2000,27

In [201]:
df[df['market_category'].isnull()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
685,mazda,626,2000,regular_unleaded,170.0,6.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,25,19,586,2080,18
686,mazda,626,2000,regular_unleaded,170.0,6.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,25,19,586,2234,18
687,mazda,626,2000,regular_unleaded,130.0,4.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,29,23,586,2000,18
688,mazda,626,2000,regular_unleaded,130.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,25,19,586,2146,18
689,mazda,626,2001,premium_unleaded_(required),165.0,6.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,25,19,586,22935,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11792,subaru,xt,1991,regular_unleaded,97.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,29,22,640,2000,27
11793,subaru,xt,1991,regular_unleaded,145.0,6.0,automatic,front_wheel_drive,2.0,NaN,compact,coupe,26,18,640,2000,27
11794,subaru,xt,1991,regular_unleaded,145.0,6.0,manual,all_wheel_drive,2.0,NaN,compact,coupe,23,16,640,2000,27
11867,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,4dr_suv,21,15,549,64520,3
11868,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,21,14,549,67520,3

In [202]:
df[(df.make == 'mazda') & (df.driven_wheels == 'front_wheel_drive') & (df.vehicle_size == 'midsize') & (df.vehicle_style == 'sedan')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
398,mazda,3,2017,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,37,28,586,21495,1
399,mazda,3,2017,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,midsize,sedan,37,27,586,17845,1
400,mazda,3,2017,regular_unleaded,184.0,4.0,manual,front_wheel_drive,4.0,performance,midsize,sedan,34,25,586,23145,1
401,mazda,3,2017,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,36,27,586,24195,1
407,mazda,3,2017,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,37,28,586,18895,1
410,mazda,3,2017,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,midsize,sedan,37,27,586,20445,1
685,mazda,626,2000,regular_unleaded,170.0,6.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,25,19,586,2080,18
686,mazda,626,2000,regular_unleaded,170.0,6.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,25,19,586,2234,18
687,mazda,626,2000,regular_unleaded,130.0,4.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,29,23,586,2000,18
688,mazda,626,2000,regular_unleaded,130.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,25,19,586,2146,18
689,mazda,626,2001,premium_unleaded_(required),165.0,6.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,25,19,586,22935,17
690,mazda,626,2001,premium_unleaded_(required),165.0,6.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,25,19,586,19935,17
691,mazda,626,2001,regular_unleaded,125.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,25,19,586,20935,17
692,mazda,626,2001,regular_unleaded,125.0,4.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,29,23,586,18735,17
693,mazda,626,2002,premium_unleaded_(required),165.0,6.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,25,19,586,19985,16
694,mazda,626,2002,regular_unleaded,125.0,4.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,29,23,586,18785,16
695,mazda,626,2002,premium_unleaded_(required),165.0,6.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,25,19,586,21885,16
705,mazda,6,2015,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,38,26,586,24895,3
706,mazda,6,2015,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,38,26,586,22895,3
707,mazda,6,2015,regular_unleaded,184.0,4.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,37,25,586,23845,3
708,mazda,6,2015,regular_unleaded,184.0,4.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,37,25,586,21190,3
709,mazda,6,2015,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,40,28,586,29895,3
710,mazda,6,2016,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,38,26,586,22995,2
711,mazda,6,2016,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,38,26,586,24995,2
712,mazda,6,2016,regular_unleaded,184.0,4.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,37,25,586,21495,2
713,mazda,6,2016,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,38,26,586,30195,2
714,mazda,6,2016,regular_unleaded,184.0,4.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,37,25,586,23945,2
715,mazda,6,2017,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,35,26,586,30695,1
716,mazda,6,2017,regular_unleaded,184.0,4.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,34,24,586,21945,1
717,mazda,6,2017,regular_unleaded,184.0,4.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,34,24,586,24195,1
718,mazda,6,2017,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,35,26,586,22995,1
719,mazda,6,2017,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,35,26,586,25245,1
6806,mazda,millenia,2000,regular_unleaded,210.0,6.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,25,17,586,2381,18
6807,mazda,millenia,2000,regular_unleaded,210.0,6.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,25,17,586,2337,18
6808,mazda,millenia,2000,regular_unleaded,170.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,24,17,586,2138,18
6809,mazda,millenia,2001,premium_unleaded_(required),210.0,6.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,25,17,586,31025,17
6810,mazda,millenia,2001,regular_unleaded,170.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,24,17,586,28025,17
6811,mazda,millenia,2002,regular_unleaded,170.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,24,17,586,28075,16
6812,mazda,millenia,2002,premium_unleaded_(required),210.0,6.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,25,17,586,31075,16
6813,mazda,millenia,2002,premium_unleaded_(required),210.0,6.0,automatic,front_wheel_drive,4.0,performance,midsize,sedan,25,17,586,31675,16
6814,mazda,millenia,2002,regular_unleaded,170.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,24,17,586,28875,16

In [203]:
M_M = (df.make == 'mazda') & (df.driven_wheels == 'front_wheel_drive') & (df.vehicle_size == 'midsize') & (df.vehicle_style == 'sedan')
M_M

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [204]:
df.loc[M_M, 'market_category'] = df.loc[M_M, 'market_category'].fillna('performance')

In [205]:
df[df['market_category'].isnull()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
981,mazda,929,1993,regular_unleaded,195.0,6.0,automatic,rear_wheel_drive,4.0,NaN,midsize,sedan,22,17,586,2000,25
982,mazda,929,1994,regular_unleaded,193.0,6.0,automatic,rear_wheel_drive,4.0,NaN,midsize,sedan,22,17,586,2000,24
983,mazda,929,1995,regular_unleaded,193.0,6.0,automatic,rear_wheel_drive,4.0,NaN,midsize,sedan,22,17,586,2000,23
1173,hyundai,accent,2014,regular_unleaded,138.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,37,27,1439,15645,4
1175,hyundai,accent,2014,regular_unleaded,138.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,38,27,1439,14645,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11792,subaru,xt,1991,regular_unleaded,97.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,29,22,640,2000,27
11793,subaru,xt,1991,regular_unleaded,145.0,6.0,automatic,front_wheel_drive,2.0,NaN,compact,coupe,26,18,640,2000,27
11794,subaru,xt,1991,regular_unleaded,145.0,6.0,manual,all_wheel_drive,2.0,NaN,compact,coupe,23,16,640,2000,27
11867,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,4dr_suv,21,15,549,64520,3
11868,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,21,14,549,67520,3

In [206]:
df[(df.make == 'mazda') & (df.model == '929')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
981,mazda,929,1993,regular_unleaded,195.0,6.0,automatic,rear_wheel_drive,4.0,NaN,midsize,sedan,22,17,586,2000,25
982,mazda,929,1994,regular_unleaded,193.0,6.0,automatic,rear_wheel_drive,4.0,NaN,midsize,sedan,22,17,586,2000,24
983,mazda,929,1995,regular_unleaded,193.0,6.0,automatic,rear_wheel_drive,4.0,NaN,midsize,sedan,22,17,586,2000,23

In [207]:
df[(df.engine_fuel_type == 'regular_unleaded')& (df.transmission_type == 'automatic') & (df.engine_cylinders == 6.0) & (df.driven_wheels == 'rear_wheel_drive') & (df.vehicle_size == 'midsize') & (df.vehicle_style == 'sedan')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
167,mercedes-benz,300-class,1991,regular_unleaded,158.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,22,17,617,2000,27
170,mercedes-benz,300-class,1991,regular_unleaded,177.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,22,16,617,2000,27
181,mercedes-benz,300-class,1992,regular_unleaded,177.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,22,16,617,2065,26
184,mercedes-benz,300-class,1992,regular_unleaded,158.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,23,18,617,2000,26
189,mercedes-benz,300-class,1993,regular_unleaded,217.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,22,17,617,2187,25
192,mercedes-benz,300-class,1993,regular_unleaded,194.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,23,17,617,2247,25
754,volvo,760,1990,regular_unleaded,144.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,19,15,870,2000,28
981,mazda,929,1993,regular_unleaded,195.0,6.0,automatic,rear_wheel_drive,4.0,NaN,midsize,sedan,22,17,586,2000,25
982,mazda,929,1994,regular_unleaded,193.0,6.0,automatic,rear_wheel_drive,4.0,NaN,midsize,sedan,22,17,586,2000,24
983,mazda,929,1995,regular_unleaded,193.0,6.0,automatic,rear_wheel_drive,4.0,NaN,midsize,sedan,22,17,586,2000,23
1003,volvo,960,1995,regular_unleaded,181.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,23,15,870,2000,23
1004,volvo,960,1996,regular_unleaded,181.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,24,16,870,2000,22
1007,volvo,960,1997,regular_unleaded,181.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,24,16,870,2000,21
1543,cadillac,ats,2016,regular_unleaded,335.0,6.0,automatic,rear_wheel_drive,4.0,"luxury,high-performance",midsize,sedan,30,20,1624,41340,2
1545,cadillac,ats,2016,regular_unleaded,335.0,6.0,automatic,rear_wheel_drive,4.0,"luxury,high-performance",midsize,sedan,30,20,1624,45155,2
1550,cadillac,ats,2016,regular_unleaded,335.0,6.0,automatic,rear_wheel_drive,4.0,"luxury,high-performance",midsize,sedan,30,20,1624,48110,2
1559,cadillac,ats,2017,regular_unleaded,335.0,6.0,automatic,rear_wheel_drive,4.0,"luxury,high-performance",midsize,sedan,30,20,1624,46995,1
1561,cadillac,ats,2017,regular_unleaded,335.0,6.0,automatic,rear_wheel_drive,4.0,"luxury,high-performance",midsize,sedan,30,20,1624,43995,1
2346,cadillac,catera,1999,regular_unleaded,200.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,23,16,1624,2066,19
2347,cadillac,catera,2000,regular_unleaded,200.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,23,16,1624,2103,18
2348,cadillac,catera,2000,regular_unleaded,200.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,23,16,1624,2241,18
3087,toyota,cressida,1990,regular_unleaded,190.0,6.0,automatic,rear_wheel_drive,4.0,"crossover,performance",midsize,sedan,22,17,2031,2000,28
3088,toyota,cressida,1991,regular_unleaded,190.0,6.0,automatic,rear_wheel_drive,4.0,"crossover,performance",midsize,sedan,22,17,2031,2000,27
3089,toyota,cressida,1992,regular_unleaded,190.0,6.0,automatic,rear_wheel_drive,4.0,"crossover,performance",midsize,sedan,22,17,2031,2000,26
5133,infiniti,g35,2006,regular_unleaded,280.0,6.0,automatic,rear_wheel_drive,4.0,"luxury,performance",midsize,sedan,23,17,190,31450,12
5993,infiniti,j30,1995,regular_unleaded,210.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,22,16,190,2000,23
5994,infiniti,j30,1996,regular_unleaded,210.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,22,16,190,2000,22
5995,infiniti,j30,1996,regular_unleaded,210.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,22,16,190,2000,22
5996,infiniti,j30,1997,regular_unleaded,210.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,22,16,190,2081,21
5997,infiniti,j30,1997,regular_unleaded,210.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,22,16,190,2032,21
5998,infiniti,j30,1997,regular_unleaded,210.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,22,16,190,2081,21
5999,infiniti,j30,1997,regular_unleaded,210.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,22,16,190,2000,21
8948,volvo,s90,1998,regular_unleaded,181.0,6.0,automatic,rear_wheel_drive,4.0,luxury,midsize,sedan,23,16,870,2269,20

In [208]:
M_929 = (df.make == 'mazda') & (df.model == '929')
M_929

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [209]:
df.loc[M_929, 'market_category'] = df.loc[M_929, 'market_category'].fillna('luxury')

In [210]:
df[df['market_category'].isnull()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1173,hyundai,accent,2014,regular_unleaded,138.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,37,27,1439,15645,4
1175,hyundai,accent,2014,regular_unleaded,138.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,38,27,1439,14645,4
1177,hyundai,accent,2015,regular_unleaded,137.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,38,27,1439,14745,3
1179,hyundai,accent,2015,regular_unleaded,137.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,37,26,1439,15745,3
1183,hyundai,accent,2016,regular_unleaded,137.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,37,26,1439,15745,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11792,subaru,xt,1991,regular_unleaded,97.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,29,22,640,2000,27
11793,subaru,xt,1991,regular_unleaded,145.0,6.0,automatic,front_wheel_drive,2.0,NaN,compact,coupe,26,18,640,2000,27
11794,subaru,xt,1991,regular_unleaded,145.0,6.0,manual,all_wheel_drive,2.0,NaN,compact,coupe,23,16,640,2000,27
11867,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,4dr_suv,21,15,549,64520,3
11868,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,21,14,549,67520,3

In [211]:
df[(df.make == 'hyundai') & (df.vehicle_size == 'compact') & (df.vehicle_style == 'sedan')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1173,hyundai,accent,2014,regular_unleaded,138.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,37,27,1439,15645,4
1175,hyundai,accent,2014,regular_unleaded,138.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,38,27,1439,14645,4
1177,hyundai,accent,2015,regular_unleaded,137.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,38,27,1439,14745,3
1179,hyundai,accent,2015,regular_unleaded,137.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,37,26,1439,15745,3
1183,hyundai,accent,2016,regular_unleaded,137.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,37,26,1439,15745,2
1187,hyundai,accent,2016,regular_unleaded,137.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,38,27,1439,14745,2
3856,hyundai,elantra,2015,regular_unleaded,173.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,35,24,1439,22600,3
3857,hyundai,elantra,2015,regular_unleaded,145.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,37,27,1439,21700,3
3858,hyundai,elantra,2015,regular_unleaded,145.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,38,28,1439,18250,3
3859,hyundai,elantra,2015,regular_unleaded,145.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,37,27,1439,17250,3
3860,hyundai,elantra,2015,regular_unleaded,166.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,35,24,1439,22600,3
3861,hyundai,elantra,2015,regular_unleaded,173.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,34,24,1439,21600,3
3862,hyundai,elantra,2015,regular_unleaded,145.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,37,27,1439,21700,3
3863,hyundai,elantra,2016,regular_unleaded,173.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,35,24,1439,21250,2
3864,hyundai,elantra,2016,regular_unleaded,145.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,38,28,1439,18250,2
3865,hyundai,elantra,2016,regular_unleaded,166.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,35,24,1439,21250,2
3866,hyundai,elantra,2016,regular_unleaded,145.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,37,27,1439,21700,2
3867,hyundai,elantra,2016,regular_unleaded,173.0,4.0,manual,front_wheel_drive,4.0,performance,compact,sedan,34,24,1439,20250,2
3868,hyundai,elantra,2016,regular_unleaded,145.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,37,27,1439,17250,2
3869,hyundai,elantra,2016,regular_unleaded,145.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,37,27,1439,21700,2
3870,hyundai,elantra,2016,regular_unleaded,145.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,38,28,1439,19700,2
3871,hyundai,elantra,2017,regular_unleaded,147.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,38,29,1439,18150,1
3872,hyundai,elantra,2017,regular_unleaded,147.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,37,28,1439,22350,1
3873,hyundai,elantra,2017,regular_unleaded,147.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,38,29,1439,18150,1
3874,hyundai,elantra,2017,regular_unleaded,128.0,4.0,automated_manual,front_wheel_drive,4.0,NaN,compact,sedan,40,32,1439,20650,1
3875,hyundai,elantra,2017,regular_unleaded,147.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,36,26,1439,17150,1
3876,hyundai,elantra,2017,regular_unleaded,147.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,37,28,1439,22350,1
3877,hyundai,elantra,2017,regular_unleaded,201.0,4.0,automated_manual,front_wheel_drive,4.0,NaN,compact,sedan,33,26,1439,22750,1
3878,hyundai,elantra,2017,regular_unleaded,201.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,30,22,1439,21650,1
3879,hyundai,elantra,2017,regular_unleaded,147.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,38,29,1439,20250,1
4282,hyundai,excel,1992,regular_unleaded,81.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,30,25,1439,2000,26
4284,hyundai,excel,1992,regular_unleaded,81.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,33,25,1439,2000,26
4285,hyundai,excel,1993,regular_unleaded,81.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,30,25,1439,2000,25
4287,hyundai,excel,1993,regular_unleaded,81.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,33,25,1439,2000,25
4290,hyundai,excel,1994,regular_unleaded,81.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,33,24,1439,2000,24

In [212]:
H = (df.make == 'hyundai') & (df.vehicle_size == 'compact') & (df.vehicle_style == 'sedan')
H

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [213]:
df.loc[H, 'market_category'] = df.loc[H, 'market_category'].fillna('performance')

In [214]:
df[df['market_category'].isnull()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1189,plymouth,acclaim,1993,regular_unleaded,100.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,29,22,535,2000,25
1190,plymouth,acclaim,1994,regular_unleaded,106.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,25,19,535,2000,24
1191,plymouth,acclaim,1995,regular_unleaded,100.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,26,19,535,2000,23
1213,honda,accord,2015,regular_unleaded,278.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,34,21,2202,32270,3
1217,honda,accord,2015,regular_unleaded,185.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,36,27,2202,30195,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11792,subaru,xt,1991,regular_unleaded,97.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,29,22,640,2000,27
11793,subaru,xt,1991,regular_unleaded,145.0,6.0,automatic,front_wheel_drive,2.0,NaN,compact,coupe,26,18,640,2000,27
11794,subaru,xt,1991,regular_unleaded,145.0,6.0,manual,all_wheel_drive,2.0,NaN,compact,coupe,23,16,640,2000,27
11867,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,4dr_suv,21,15,549,64520,3
11868,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,21,14,549,67520,3

In [215]:
df[(df.make == 'plymouth') & (df.engine_fuel_type == 'regular_unleaded')  &(df.vehicle_size == 'compact') & (df.vehicle_style == 'sedan')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1189,plymouth,acclaim,1993,regular_unleaded,100.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,29,22,535,2000,25
1190,plymouth,acclaim,1994,regular_unleaded,106.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,25,19,535,2000,24
1191,plymouth,acclaim,1995,regular_unleaded,100.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,26,19,535,2000,23
2829,plymouth,colt,1993,regular_unleaded,113.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,31,23,535,2000,25
2830,plymouth,colt,1993,regular_unleaded,92.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,36,28,535,2000,25
2838,plymouth,colt,1994,regular_unleaded,113.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,30,23,535,2000,24
2839,plymouth,colt,1994,regular_unleaded,113.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,30,23,535,2000,24
7182,plymouth,neon,1999,regular_unleaded,132.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,36,24,535,2000,19
7184,plymouth,neon,1999,regular_unleaded,132.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,36,24,535,2000,19
7185,plymouth,neon,1999,regular_unleaded,150.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,36,24,535,2000,19
7186,plymouth,neon,2000,regular_unleaded,132.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,31,24,535,2000,18
7187,plymouth,neon,2000,regular_unleaded,132.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,31,24,535,2044,18
7188,plymouth,neon,2001,regular_unleaded,132.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,30,24,535,12715,17

In [216]:
df[(df.engine_fuel_type == 'regular_unleaded')& (df.engine_cylinders == 4.0) & (df.driven_wheels == 'front_wheel_drive') &(df.vehicle_size == 'compact') & (df.vehicle_style == 'sedan')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
358,mazda,3,2015,regular_unleaded,184.0,4.0,manual,front_wheel_drive,4.0,performance,compact,sedan,37,25,586,25045,3
359,mazda,3,2015,regular_unleaded,184.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,39,28,586,26095,3
360,mazda,3,2015,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,performance,compact,sedan,41,30,586,23795,3
361,mazda,3,2015,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,sedan,41,29,586,19595,3
362,mazda,3,2015,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,sedan,41,29,586,18445,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11359,nissan,versa,2017,regular_unleaded,109.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,36,27,2009,11990,1
11360,nissan,versa,2017,regular_unleaded,109.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,39,31,2009,14130,1
11361,nissan,versa,2017,regular_unleaded,109.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,sedan,39,31,2009,15720,1
11809,toyota,yaris_ia,2017,regular_unleaded,106.0,4.0,manual,front_wheel_drive,4.0,hatchback,compact,sedan,39,30,2031,15950,1
11810,toyota,yaris_ia,2017,regular_unleaded,106.0,4.0,automatic,front_wheel_drive,4.0,hatchback,compact,sedan,40,32,2031,17050,1

In [217]:
r = df[(df.engine_fuel_type == 'regular_unleaded')& (df.engine_cylinders == 4.0) & (df.driven_wheels == 'front_wheel_drive') &(df.vehicle_size == 'compact') & (df.vehicle_style == 'sedan')]

In [218]:
r['market_category'].unique()

array(['performance', 'hatchback', 'luxury', nan, 'hybrid',
       'luxury,performance'], dtype=object)

In [219]:
NA_0 = (df.make == 'plymouth') & (df.engine_fuel_type == 'regular_unleaded')  &(df.vehicle_size == 'compact') & (df.vehicle_style == 'sedan')
NA_0

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [220]:
df.loc[NA_0, 'market_category'] = df.loc[NA_0, 'market_category'].fillna(0)

In [221]:
df[df['market_category'].isnull()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1213,honda,accord,2015,regular_unleaded,278.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,34,21,2202,32270,3
1217,honda,accord,2015,regular_unleaded,185.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,36,27,2202,30195,3
1220,honda,accord,2015,regular_unleaded,189.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,35,26,2202,24665,3
1221,honda,accord,2015,regular_unleaded,185.0,4.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,34,24,2202,25030,3
1223,honda,accord,2015,regular_unleaded,185.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,36,27,2202,25830,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11792,subaru,xt,1991,regular_unleaded,97.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,29,22,640,2000,27
11793,subaru,xt,1991,regular_unleaded,145.0,6.0,automatic,front_wheel_drive,2.0,NaN,compact,coupe,26,18,640,2000,27
11794,subaru,xt,1991,regular_unleaded,145.0,6.0,manual,all_wheel_drive,2.0,NaN,compact,coupe,23,16,640,2000,27
11867,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,4dr_suv,21,15,549,64520,3
11868,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,21,14,549,67520,3

In [222]:
d = df[(df.make == 'honda') & (df.model == 'accord')]

In [223]:
d['market_category'].unique()

array(['performance', nan, 'luxury'], dtype=object)

In [224]:
H_A = (df.make == 'honda') & (df.model == 'accord')
H_A

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [225]:
df.loc[H_A, 'market_category'] = df.loc[H_A, 'market_category'].fillna('performance,luxury')

In [226]:
df[(df['market_category'].isnull())]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1287,oldsmobile,achieva,1996,regular_unleaded,150.0,4.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,30,20,26,2000,22
1290,oldsmobile,achieva,1997,regular_unleaded,150.0,4.0,unknown,front_wheel_drive,4.0,NaN,midsize,sedan,29,19,26,2000,21
1291,oldsmobile,achieva,1998,regular_unleaded,150.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,27,18,26,2000,20
1300,suzuki,aerio,2005,regular_unleaded,155.0,4.0,automatic,all_wheel_drive,4.0,NaN,compact,sedan,26,21,481,17049,13
1301,suzuki,aerio,2005,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,28,22,481,16349,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11792,subaru,xt,1991,regular_unleaded,97.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,29,22,640,2000,27
11793,subaru,xt,1991,regular_unleaded,145.0,6.0,automatic,front_wheel_drive,2.0,NaN,compact,coupe,26,18,640,2000,27
11794,subaru,xt,1991,regular_unleaded,145.0,6.0,manual,all_wheel_drive,2.0,NaN,compact,coupe,23,16,640,2000,27
11867,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,4dr_suv,21,15,549,64520,3
11868,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,21,14,549,67520,3

In [227]:
df[(df.make == 'oldsmobile') & (df.model == 'achieva')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1287,oldsmobile,achieva,1996,regular_unleaded,150.0,4.0,manual,front_wheel_drive,4.0,NaN,midsize,sedan,30,20,26,2000,22
1288,oldsmobile,achieva,1996,regular_unleaded,150.0,4.0,manual,front_wheel_drive,2.0,luxury,midsize,coupe,30,20,26,2000,22
1289,oldsmobile,achieva,1997,regular_unleaded,150.0,4.0,unknown,front_wheel_drive,2.0,luxury,midsize,coupe,29,19,26,2000,21
1290,oldsmobile,achieva,1997,regular_unleaded,150.0,4.0,unknown,front_wheel_drive,4.0,NaN,midsize,sedan,29,19,26,2000,21
1291,oldsmobile,achieva,1998,regular_unleaded,150.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,27,18,26,2000,20

In [228]:
O_A = (df.make == 'oldsmobile') & (df.model == 'achieva')
O_A

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [229]:
df.loc[O_A, 'market_category'] = df.loc[O_A, 'market_category'].fillna('luxury')

In [230]:
df[(df['market_category'].isnull())]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1300,suzuki,aerio,2005,regular_unleaded,155.0,4.0,automatic,all_wheel_drive,4.0,NaN,compact,sedan,26,21,481,17049,13
1301,suzuki,aerio,2005,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,28,22,481,16349,13
1302,suzuki,aerio,2005,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,28,22,481,15949,13
1303,suzuki,aerio,2005,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,28,22,481,13449,13
1304,suzuki,aerio,2005,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,28,22,481,15449,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11792,subaru,xt,1991,regular_unleaded,97.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,29,22,640,2000,27
11793,subaru,xt,1991,regular_unleaded,145.0,6.0,automatic,front_wheel_drive,2.0,NaN,compact,coupe,26,18,640,2000,27
11794,subaru,xt,1991,regular_unleaded,145.0,6.0,manual,all_wheel_drive,2.0,NaN,compact,coupe,23,16,640,2000,27
11867,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,4dr_suv,21,15,549,64520,3
11868,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,21,14,549,67520,3

In [231]:
ttt = df[(df.make == 'suzuki') & (df.engine_fuel_type == 'regular_unleaded') & (df.vehicle_size == 'compact') & (df['market_category'].isnull())]
ttt

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1300,suzuki,aerio,2005,regular_unleaded,155.0,4.0,automatic,all_wheel_drive,4.0,NaN,compact,sedan,26,21,481,17049,13
1301,suzuki,aerio,2005,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,28,22,481,16349,13
1302,suzuki,aerio,2005,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,28,22,481,15949,13
1303,suzuki,aerio,2005,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,sedan,28,22,481,13449,13
1304,suzuki,aerio,2005,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,28,22,481,15449,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11478,suzuki,x-90,1997,regular_unleaded,95.0,4.0,manual,four_wheel_drive,2.0,NaN,compact,2dr_suv,26,22,481,2000,21
11479,suzuki,x-90,1997,regular_unleaded,95.0,4.0,manual,rear_wheel_drive,2.0,NaN,compact,2dr_suv,26,22,481,2000,21
11480,suzuki,x-90,1998,regular_unleaded,95.0,4.0,manual,four_wheel_drive,2.0,NaN,compact,2dr_suv,26,22,481,2000,20
11481,suzuki,x-90,1998,regular_unleaded,95.0,4.0,manual,four_wheel_drive,2.0,NaN,compact,2dr_suv,26,22,481,2000,20
11482,suzuki,x-90,1998,regular_unleaded,95.0,4.0,manual,rear_wheel_drive,2.0,NaN,compact,2dr_suv,26,22,481,2000,20

In [232]:
ttt['market_category'].unique()

array([nan], dtype=object)

In [233]:
ttt = df[(df.vehicle_style == 'wagon') & (df.engine_fuel_type == 'regular_unleaded') & (df.vehicle_size == 'compact') & (df['market_category'].notnull())]

In [234]:
ttt['market_category'].unique()

array(['luxury,performance', 'luxury', 'hybrid', 'crossover'],
      dtype=object)

In [235]:
tt = df[(df.make == 'suzuki') & (df.vehicle_style == 'sedan')]

In [236]:
tt['market_category'].unique()

array([nan], dtype=object)

In [237]:
S_S = (df.make == 'suzuki') & (df.vehicle_style == 'sedan')

In [238]:
df.loc[S_S, 'market_category'] = df.loc[S_S, 'market_category'].fillna(0)

In [239]:
df[(df['market_category'].isnull())]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1301,suzuki,aerio,2005,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,28,22,481,16349,13
1302,suzuki,aerio,2005,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,28,22,481,15949,13
1304,suzuki,aerio,2005,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,28,22,481,15449,13
1305,suzuki,aerio,2005,regular_unleaded,155.0,4.0,automatic,all_wheel_drive,4.0,NaN,compact,wagon,26,21,481,17349,13
1307,suzuki,aerio,2005,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,26,21,481,16849,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11792,subaru,xt,1991,regular_unleaded,97.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,29,22,640,2000,27
11793,subaru,xt,1991,regular_unleaded,145.0,6.0,automatic,front_wheel_drive,2.0,NaN,compact,coupe,26,18,640,2000,27
11794,subaru,xt,1991,regular_unleaded,145.0,6.0,manual,all_wheel_drive,2.0,NaN,compact,coupe,23,16,640,2000,27
11867,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,4dr_suv,21,15,549,64520,3
11868,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,21,14,549,67520,3

In [240]:
df[(df.make == 'suzuki') & (df.vehicle_style == 'wagon')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1301,suzuki,aerio,2005,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,28,22,481,16349,13
1302,suzuki,aerio,2005,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,28,22,481,15949,13
1304,suzuki,aerio,2005,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,28,22,481,15449,13
1305,suzuki,aerio,2005,regular_unleaded,155.0,4.0,automatic,all_wheel_drive,4.0,NaN,compact,wagon,26,21,481,17349,13
1307,suzuki,aerio,2005,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,26,21,481,16849,13
1311,suzuki,aerio,2005,regular_unleaded,155.0,4.0,automatic,all_wheel_drive,4.0,NaN,compact,wagon,26,21,481,17849,13
1314,suzuki,aerio,2006,regular_unleaded,155.0,4.0,automatic,all_wheel_drive,4.0,NaN,compact,wagon,26,21,481,16599,12
1315,suzuki,aerio,2006,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,28,22,481,15499,12
1319,suzuki,aerio,2006,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,28,22,481,15299,12
1320,suzuki,aerio,2006,regular_unleaded,155.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,28,22,481,14599,12
1322,suzuki,aerio,2006,regular_unleaded,155.0,4.0,automatic,all_wheel_drive,4.0,NaN,compact,wagon,26,21,481,17099,12
1324,suzuki,aerio,2006,regular_unleaded,155.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,28,22,481,16199,12
4222,suzuki,esteem,2000,regular_unleaded,122.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,31,24,481,2000,18
4223,suzuki,esteem,2000,regular_unleaded,122.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,31,24,481,2000,18
4225,suzuki,esteem,2001,regular_unleaded,122.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,30,23,481,16499,17
4226,suzuki,esteem,2001,regular_unleaded,122.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,30,26,481,15499,17
4228,suzuki,esteem,2001,regular_unleaded,122.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,30,26,481,16699,17
4229,suzuki,esteem,2001,regular_unleaded,122.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,30,26,481,15699,17
4230,suzuki,esteem,2001,regular_unleaded,122.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,32,24,481,13699,17
4233,suzuki,esteem,2001,regular_unleaded,122.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,30,26,481,14699,17
4237,suzuki,esteem,2001,regular_unleaded,122.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,31,24,481,14699,17
4239,suzuki,esteem,2001,regular_unleaded,122.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,32,24,481,14499,17
4242,suzuki,esteem,2002,regular_unleaded,122.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,30,23,481,16799,16
4243,suzuki,esteem,2002,regular_unleaded,122.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,31,24,481,14799,16
4245,suzuki,esteem,2002,regular_unleaded,122.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,31,24,481,13799,16
4246,suzuki,esteem,2002,regular_unleaded,122.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,30,23,481,14799,16
4247,suzuki,esteem,2002,regular_unleaded,122.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,30,23,481,16599,16
4250,suzuki,esteem,2002,regular_unleaded,122.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,30,23,481,15799,16
4800,suzuki,forenza,2006,regular_unleaded,126.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,27,19,481,16699,12
4802,suzuki,forenza,2006,regular_unleaded,126.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,27,19,481,14499,12
4805,suzuki,forenza,2006,regular_unleaded,126.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,27,19,481,15399,12
4807,suzuki,forenza,2006,regular_unleaded,126.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,27,19,481,15799,12
4808,suzuki,forenza,2007,regular_unleaded,127.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,27,19,481,16349,11
4809,suzuki,forenza,2007,regular_unleaded,127.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,27,19,481,14899,11
4810,suzuki,forenza,2007,regular_unleaded,127.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,27,19,481,15399,11
4812,suzuki,forenza,2007,regular_unleaded,127.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,27,19,481,16499,11
4819,suzuki,forenza,2007,regular_unleaded,127.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,27,19,481,15999,11
4820,suzuki,forenza,2007,regular_unleaded,127.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,27,19,481,16949,11
4821,suzuki,forenza,2007,regular_unleaded,127.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,27,19,481,15249,11
4822,suzuki,forenza,2007,regular_unleaded,127.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,27,19,481,15849,11
4825,suzuki,forenza,2008,regular_unleaded,127.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,27,19,481,16489,10
4826,suzuki,forenza,2008,regular_unleaded,127.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,27,19,481,17689,10
4827,suzuki,forenza,2008,regular_unleaded,127.0,4.0,automatic,front_wheel_drive,4.0,NaN,compact,wagon,27,19,481,16989,10
4831,suzuki,forenza,2008,regular_unleaded,127.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,27,19,481,15889,10
4833,suzuki,forenza,2008,regular_unleaded,127.0,4.0,manual,front_wheel_drive,4.0,NaN,compact,wagon,27,19,481,15389,10

In [241]:
ty = df[(df.vehicle_style == 'wagon') & (df.engine_cylinders == 4.0) & (df.vehicle_size == 'compact') & (df.engine_fuel_type == 'regular_unleaded') & (df.number_of_doors == 4.0) & (df.driven_wheels == 'front_wheel_drive')]

In [242]:
ty['market_category'].unique()

array([nan, 'hybrid'], dtype=object)

In [243]:
ty = (df.vehicle_style == 'wagon') & (df.engine_cylinders == 4.0) & (df.vehicle_size == 'compact') & (df.engine_fuel_type == 'regular_unleaded') & (df.number_of_doors == 4.0) & (df.driven_wheels == 'front_wheel_drive')

In [244]:
df.loc[ty, 'market_category'] = df.loc[ty, 'market_category'].fillna(0)

In [245]:
ty_1 = df[(df.vehicle_style == 'wagon') & (df.engine_cylinders == 4.0) & (df.vehicle_size == 'compact') & (df.engine_fuel_type == 'regular_unleaded') & (df.number_of_doors == 4.0) & (df.driven_wheels == 'all_wheel_drive')]
ty_1

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
801,saab,9-2x,2005,regular_unleaded,165.0,4.0,manual,all_wheel_drive,4.0,"luxury,performance",compact,wagon,27,20,376,22990,13
803,saab,9-2x,2006,regular_unleaded,173.0,4.0,manual,all_wheel_drive,4.0,luxury,compact,wagon,26,19,376,22990,12
1305,suzuki,aerio,2005,regular_unleaded,155.0,4.0,automatic,all_wheel_drive,4.0,NaN,compact,wagon,26,21,481,17349,13
1311,suzuki,aerio,2005,regular_unleaded,155.0,4.0,automatic,all_wheel_drive,4.0,NaN,compact,wagon,26,21,481,17849,13
1314,suzuki,aerio,2006,regular_unleaded,155.0,4.0,automatic,all_wheel_drive,4.0,NaN,compact,wagon,26,21,481,16599,12
1322,suzuki,aerio,2006,regular_unleaded,155.0,4.0,automatic,all_wheel_drive,4.0,NaN,compact,wagon,26,21,481,17099,12
2825,plymouth,colt,1992,regular_unleaded,113.0,4.0,manual,all_wheel_drive,4.0,NaN,compact,wagon,24,19,535,2000,26
2828,plymouth,colt,1993,regular_unleaded,113.0,4.0,manual,all_wheel_drive,4.0,NaN,compact,wagon,24,19,535,2000,25
2835,plymouth,colt,1994,regular_unleaded,136.0,4.0,manual,all_wheel_drive,4.0,NaN,compact,wagon,22,18,535,2000,24
5359,volkswagen,golf_alltrack,2017,regular_unleaded,170.0,4.0,automated_manual,all_wheel_drive,4.0,crossover,compact,wagon,30,22,873,26950,1
5360,volkswagen,golf_alltrack,2017,regular_unleaded,170.0,4.0,automated_manual,all_wheel_drive,4.0,crossover,compact,wagon,30,22,873,32890,1
5361,volkswagen,golf_alltrack,2017,regular_unleaded,170.0,4.0,automated_manual,all_wheel_drive,4.0,crossover,compact,wagon,30,22,873,30530,1
5362,volkswagen,golf_alltrack,2017,regular_unleaded,170.0,4.0,manual,all_wheel_drive,4.0,crossover,compact,wagon,30,22,873,25850,1
5363,volkswagen,golf_alltrack,2017,regular_unleaded,170.0,4.0,manual,all_wheel_drive,4.0,crossover,compact,wagon,30,22,873,29430,1

In [246]:
ty_1 = (df.vehicle_style == 'wagon') & (df.engine_cylinders == 4.0) & (df.vehicle_size == 'compact') & (df.engine_fuel_type == 'regular_unleaded') & (df.number_of_doors == 4.0) & (df.driven_wheels == 'all_wheel_drive')
ty_1

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [247]:
df.loc[ty_1, 'market_category'] = df.loc[ty_1, 'market_category'].fillna(0)

In [248]:
df[(df['market_category'].isnull())]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1331,ford,aerostar,1995,regular_unleaded,135.0,6.0,automatic,rear_wheel_drive,3.0,NaN,midsize,cargo_minivan,22,16,5657,2000,23
1332,ford,aerostar,1995,regular_unleaded,135.0,6.0,automatic,rear_wheel_drive,3.0,NaN,midsize,passenger_minivan,22,15,5657,2000,23
1333,ford,aerostar,1995,regular_unleaded,155.0,6.0,automatic,all_wheel_drive,3.0,NaN,large,passenger_minivan,18,14,5657,2000,23
1334,ford,aerostar,1995,regular_unleaded,135.0,6.0,automatic,rear_wheel_drive,3.0,NaN,large,passenger_minivan,22,15,5657,2000,23
1335,ford,aerostar,1996,regular_unleaded,140.0,6.0,automatic,rear_wheel_drive,3.0,NaN,midsize,passenger_minivan,21,15,5657,2000,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11792,subaru,xt,1991,regular_unleaded,97.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,29,22,640,2000,27
11793,subaru,xt,1991,regular_unleaded,145.0,6.0,automatic,front_wheel_drive,2.0,NaN,compact,coupe,26,18,640,2000,27
11794,subaru,xt,1991,regular_unleaded,145.0,6.0,manual,all_wheel_drive,2.0,NaN,compact,coupe,23,16,640,2000,27
11867,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,4dr_suv,21,15,549,64520,3
11868,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,21,14,549,67520,3

In [249]:
df[(df.make == 'ford')]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1331,ford,aerostar,1995,regular_unleaded,135.0,6.0,automatic,rear_wheel_drive,3.0,NaN,midsize,cargo_minivan,22,16,5657,2000,23
1332,ford,aerostar,1995,regular_unleaded,135.0,6.0,automatic,rear_wheel_drive,3.0,NaN,midsize,passenger_minivan,22,15,5657,2000,23
1333,ford,aerostar,1995,regular_unleaded,155.0,6.0,automatic,all_wheel_drive,3.0,NaN,large,passenger_minivan,18,14,5657,2000,23
1334,ford,aerostar,1995,regular_unleaded,135.0,6.0,automatic,rear_wheel_drive,3.0,NaN,large,passenger_minivan,22,15,5657,2000,23
1335,ford,aerostar,1996,regular_unleaded,140.0,6.0,automatic,rear_wheel_drive,3.0,NaN,midsize,passenger_minivan,21,15,5657,2000,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11443,ford,windstar,2003,regular_unleaded,200.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,22,16,5657,23070,15
11444,ford,windstar,2003,regular_unleaded,200.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,22,16,5657,26315,15
11445,ford,windstar,2003,regular_unleaded,200.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,22,16,5657,29230,15
11446,ford,windstar,2003,regular_unleaded,200.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,22,16,5657,34825,15
11447,ford,windstar,2003,regular_unleaded,200.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,22,16,5657,31835,15

In [250]:
df[(df.vehicle_style == 'passenger_minivan')& (df.engine_fuel_type == 'regular_unleaded') &(df.vehicle_size == 'midsize') & (df['market_category'].notnull())]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
7410,chrysler,pacifica,2017,regular_unleaded,287.0,6.0,automatic,front_wheel_drive,4.0,performance,midsize,passenger_minivan,28,18,1013,42495,1
10374,buick,terraza,2007,regular_unleaded,240.0,6.0,automatic,front_wheel_drive,4.0,flex_fuel,midsize,passenger_minivan,23,16,155,30780,11
10375,buick,terraza,2007,regular_unleaded,240.0,6.0,automatic,front_wheel_drive,4.0,flex_fuel,midsize,passenger_minivan,23,16,155,28000,11
10376,buick,terraza,2007,regular_unleaded,240.0,6.0,automatic,front_wheel_drive,4.0,flex_fuel,midsize,passenger_minivan,23,16,155,26660,11
11080,chevrolet,uplander,2007,regular_unleaded,240.0,6.0,automatic,front_wheel_drive,4.0,flex_fuel,midsize,passenger_minivan,23,16,1385,23280,11
11081,chevrolet,uplander,2007,regular_unleaded,240.0,6.0,automatic,front_wheel_drive,4.0,flex_fuel,midsize,passenger_minivan,23,16,1385,23280,11
11082,chevrolet,uplander,2007,regular_unleaded,240.0,6.0,automatic,front_wheel_drive,4.0,flex_fuel,midsize,passenger_minivan,23,16,1385,27405,11
11083,chevrolet,uplander,2007,regular_unleaded,240.0,6.0,automatic,front_wheel_drive,4.0,flex_fuel,midsize,passenger_minivan,23,16,1385,33050,11
11084,chevrolet,uplander,2007,regular_unleaded,240.0,6.0,automatic,front_wheel_drive,4.0,flex_fuel,midsize,passenger_minivan,23,16,1385,29350,11
11088,chevrolet,uplander,2008,regular_unleaded,240.0,6.0,automatic,front_wheel_drive,4.0,flex_fuel,midsize,passenger_minivan,23,16,1385,24250,10
11090,chevrolet,uplander,2008,regular_unleaded,240.0,6.0,automatic,front_wheel_drive,4.0,flex_fuel,midsize,passenger_minivan,23,16,1385,29330,10
11091,chevrolet,uplander,2008,regular_unleaded,240.0,6.0,automatic,front_wheel_drive,4.0,flex_fuel,midsize,passenger_minivan,23,16,1385,24250,10
11416,chrysler,voyager,2002,regular_unleaded,150.0,4.0,automatic,front_wheel_drive,4.0,flex_fuel,midsize,passenger_minivan,23,17,1013,19155,16

In [251]:
df[(df.vehicle_style == 'cargo_minivan')& (df.engine_fuel_type == 'regular_unleaded') &(df.vehicle_size == 'midsize') & (df['market_category'].notnull())]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
11079,chevrolet,uplander,2007,regular_unleaded,240.0,6.0,automatic,front_wheel_drive,4.0,flex_fuel,midsize,cargo_minivan,23,16,1385,22105,11
11089,chevrolet,uplander,2008,regular_unleaded,240.0,6.0,automatic,front_wheel_drive,4.0,flex_fuel,midsize,cargo_minivan,23,16,1385,23080,10

In [252]:
df[(df.vehicle_style == 'passenger_minivan')& (df.engine_fuel_type == 'regular_unleaded') &(df.vehicle_size == 'midsize') & (df['market_category'].isnull())]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1332,ford,aerostar,1995,regular_unleaded,135.0,6.0,automatic,rear_wheel_drive,3.0,NaN,midsize,passenger_minivan,22,15,5657,2000,23
1335,ford,aerostar,1996,regular_unleaded,140.0,6.0,automatic,rear_wheel_drive,3.0,NaN,midsize,passenger_minivan,21,15,5657,2000,22
1342,ford,aerostar,1997,regular_unleaded,140.0,6.0,automatic,rear_wheel_drive,3.0,NaN,midsize,passenger_minivan,22,15,5657,2000,21
3973,hyundai,entourage,2007,regular_unleaded,242.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,23,16,1439,26395,11
3974,hyundai,entourage,2007,regular_unleaded,242.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,23,16,1439,28895,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11443,ford,windstar,2003,regular_unleaded,200.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,22,16,5657,23070,15
11444,ford,windstar,2003,regular_unleaded,200.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,22,16,5657,26315,15
11445,ford,windstar,2003,regular_unleaded,200.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,22,16,5657,29230,15
11446,ford,windstar,2003,regular_unleaded,200.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,22,16,5657,34825,15
11447,ford,windstar,2003,regular_unleaded,200.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,passenger_minivan,22,16,5657,31835,15

In [253]:
Pass_van = (df.vehicle_style == 'passenger_minivan')& (df.engine_fuel_type == 'regular_unleaded') &(df.vehicle_size == 'midsize') & (df['market_category'].isnull())
Pass_van

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [254]:
df.loc[Pass_van, 'market_category'] = df.loc[Pass_van, 'market_category'].fillna('flex_fuel')

In [255]:
cargo_van = (df.vehicle_style == 'cargo_minivan')& (df.engine_fuel_type == 'regular_unleaded') &(df.vehicle_size == 'midsize') & (df['market_category'].isnull())
cargo_van

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [256]:
df.loc[cargo_van, 'market_category'] = df.loc[cargo_van, 'market_category'].fillna('flex_fuel')

In [257]:
df[df['market_category'].isnull()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1333,ford,aerostar,1995,regular_unleaded,155.0,6.0,automatic,all_wheel_drive,3.0,NaN,large,passenger_minivan,18,14,5657,2000,23
1334,ford,aerostar,1995,regular_unleaded,135.0,6.0,automatic,rear_wheel_drive,3.0,NaN,large,passenger_minivan,22,15,5657,2000,23
1336,ford,aerostar,1996,regular_unleaded,155.0,6.0,automatic,all_wheel_drive,3.0,NaN,large,passenger_minivan,19,13,5657,2000,22
1337,ford,aerostar,1996,regular_unleaded,140.0,6.0,automatic,rear_wheel_drive,3.0,NaN,large,passenger_minivan,21,15,5657,2000,22
1340,ford,aerostar,1997,regular_unleaded,140.0,6.0,automatic,rear_wheel_drive,3.0,NaN,large,passenger_minivan,22,15,5657,2000,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11792,subaru,xt,1991,regular_unleaded,97.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,29,22,640,2000,27
11793,subaru,xt,1991,regular_unleaded,145.0,6.0,automatic,front_wheel_drive,2.0,NaN,compact,coupe,26,18,640,2000,27
11794,subaru,xt,1991,regular_unleaded,145.0,6.0,manual,all_wheel_drive,2.0,NaN,compact,coupe,23,16,640,2000,27
11867,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,4dr_suv,21,15,549,64520,3
11868,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,21,14,549,67520,3

In [258]:
df[(df.vehicle_style == 'passenger_minivan')& (df.vehicle_size == 'large') &(df.driven_wheels == 'all_wheel_drive') & (df['market_category'].notnull())]

Empty DataFrame
Columns: [make, model, year, engine_fuel_type, engine_hp, engine_cylinders, transmission_type, driven_wheels, number_of_doors, market_category, vehicle_size, vehicle_style, highway_mpg, city_mpg, popularity, msrp, age]
Index: []

In [259]:
pass_large = (df.vehicle_style == 'passenger_minivan')& (df.engine_fuel_type == 'regular_unleaded') &(df.vehicle_size == 'large') & (df['market_category'].isnull())
pass_large

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [260]:
df.loc[pass_large, 'market_category'] = df.loc[pass_large, 'market_category'].fillna('flex_fuel')

In [261]:
df['market_category'].replace('flex_fuel\t', 'flex_fuel', inplace = True)

In [262]:
df[df['market_category'].isnull()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1343,oldsmobile,alero,2002,regular_unleaded,170.0,6.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,27,18,26,22395,16
1344,oldsmobile,alero,2002,regular_unleaded,170.0,6.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,27,18,26,21080,16
1345,oldsmobile,alero,2002,regular_unleaded,140.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,30,21,26,19605,16
1346,oldsmobile,alero,2002,regular_unleaded,170.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,27,18,26,21080,16
1347,oldsmobile,alero,2002,regular_unleaded,140.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,30,21,26,17805,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11792,subaru,xt,1991,regular_unleaded,97.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,29,22,640,2000,27
11793,subaru,xt,1991,regular_unleaded,145.0,6.0,automatic,front_wheel_drive,2.0,NaN,compact,coupe,26,18,640,2000,27
11794,subaru,xt,1991,regular_unleaded,145.0,6.0,manual,all_wheel_drive,2.0,NaN,compact,coupe,23,16,640,2000,27
11867,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,4dr_suv,21,15,549,64520,3
11868,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,21,14,549,67520,3

In [263]:
df[(df.vehicle_style == 'coupe') & (df.vehicle_size == 'midsize') &(df.driven_wheels == 'front_wheel_drive') & (df['market_category'].notnull())]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1212,honda,accord,2015,regular_unleaded,278.0,6.0,manual,front_wheel_drive,2.0,performance,midsize,coupe,28,18,2202,30775,3
1214,honda,accord,2015,regular_unleaded,278.0,6.0,automatic,front_wheel_drive,2.0,performance,midsize,coupe,32,21,2202,32550,3
1215,honda,accord,2015,regular_unleaded,185.0,4.0,manual,front_wheel_drive,2.0,luxury,midsize,coupe,34,24,2202,23775,3
1216,honda,accord,2015,regular_unleaded,185.0,4.0,automatic,front_wheel_drive,2.0,luxury,midsize,coupe,35,26,2202,26300,3
1218,honda,accord,2015,regular_unleaded,185.0,4.0,manual,front_wheel_drive,2.0,luxury,midsize,coupe,34,24,2202,25450,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10007,dodge,stratus,2004,regular_unleaded,200.0,6.0,automatic,front_wheel_drive,2.0,performance,midsize,coupe,25,18,1851,23520,14
10012,dodge,stratus,2004,regular_unleaded,147.0,4.0,manual,front_wheel_drive,2.0,luxury,midsize,coupe,29,21,1851,19850,14
10013,dodge,stratus,2004,regular_unleaded,142.0,4.0,automatic,front_wheel_drive,2.0,luxury,midsize,coupe,26,19,1851,20675,14
10016,dodge,stratus,2005,regular_unleaded,200.0,6.0,manual,front_wheel_drive,2.0,performance,midsize,coupe,27,18,1851,22980,13
10018,dodge,stratus,2005,regular_unleaded,147.0,4.0,manual,front_wheel_drive,2.0,luxury,midsize,coupe,29,21,1851,20135,13

In [264]:
df[(df.make == 'oldsmobile') & (df.model == 'alero') & (df['market_category'].notnull())]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1348,oldsmobile,alero,2002,regular_unleaded,140.0,4.0,automatic,front_wheel_drive,2.0,luxury,midsize,coupe,30,21,26,17805,16
1349,oldsmobile,alero,2002,regular_unleaded,140.0,4.0,automatic,front_wheel_drive,2.0,luxury,midsize,coupe,30,21,26,19855,16
1352,oldsmobile,alero,2003,regular_unleaded,140.0,4.0,automatic,front_wheel_drive,2.0,luxury,midsize,coupe,30,21,26,18085,15
1358,oldsmobile,alero,2003,regular_unleaded,140.0,4.0,automatic,front_wheel_drive,2.0,luxury,midsize,coupe,30,21,26,20035,15
1362,oldsmobile,alero,2004,regular_unleaded,140.0,4.0,automatic,front_wheel_drive,2.0,luxury,midsize,coupe,31,21,26,20435,14
1363,oldsmobile,alero,2004,regular_unleaded,140.0,4.0,automatic,front_wheel_drive,2.0,luxury,midsize,coupe,31,21,26,18485,14

In [265]:
df[(df.make == 'oldsmobile') & (df.model == 'alero') & (df.vehicle_style == 'coupe') & (df['market_category'].isnull())]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1343,oldsmobile,alero,2002,regular_unleaded,170.0,6.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,27,18,26,22395,16
1344,oldsmobile,alero,2002,regular_unleaded,170.0,6.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,27,18,26,21080,16
1353,oldsmobile,alero,2003,regular_unleaded,170.0,6.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,27,18,26,21585,15
1355,oldsmobile,alero,2003,regular_unleaded,170.0,6.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,27,18,26,22935,15
1359,oldsmobile,alero,2004,regular_unleaded,170.0,6.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,27,18,26,23335,14
1366,oldsmobile,alero,2004,regular_unleaded,170.0,6.0,automatic,front_wheel_drive,2.0,NaN,midsize,coupe,27,18,26,21985,14

In [266]:
old_alero = (df.make == 'oldsmobile') & (df.model == 'alero') & (df.vehicle_style == 'coupe') & (df['market_category'].isnull())
old_alero

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913    False
Length: 11914, dtype: bool

In [267]:
df.loc[old_alero, 'market_category'] = df.loc[old_alero, 'market_category'].fillna('luxury')

In [268]:
df[df['market_category'].isnull()]

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,age
1345,oldsmobile,alero,2002,regular_unleaded,140.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,30,21,26,19605,16
1346,oldsmobile,alero,2002,regular_unleaded,170.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,27,18,26,21080,16
1347,oldsmobile,alero,2002,regular_unleaded,140.0,4.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,30,21,26,17805,16
1350,oldsmobile,alero,2002,regular_unleaded,170.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,27,18,26,22145,16
1351,oldsmobile,alero,2003,regular_unleaded,170.0,6.0,automatic,front_wheel_drive,4.0,NaN,midsize,sedan,27,18,26,21585,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11792,subaru,xt,1991,regular_unleaded,97.0,4.0,manual,front_wheel_drive,2.0,NaN,compact,coupe,29,22,640,2000,27
11793,subaru,xt,1991,regular_unleaded,145.0,6.0,automatic,front_wheel_drive,2.0,NaN,compact,coupe,26,18,640,2000,27
11794,subaru,xt,1991,regular_unleaded,145.0,6.0,manual,all_wheel_drive,2.0,NaN,compact,coupe,23,16,640,2000,27
11867,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,rear_wheel_drive,4.0,NaN,large,4dr_suv,21,15,549,64520,3
11868,gmc,yukon,2015,premium_unleaded_(recommended),420.0,8.0,automatic,four_wheel_drive,4.0,NaN,large,4dr_suv,21,14,549,67520,3

In [269]:
qwe = df[(df.vehicle_size == 'midsize') & (df.engine_fuel_type == 'regular_unleaded') & (df.vehicle_style == 'sedan') & (df['market_category'].notnull())]

In [270]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   make               11914 non-null  object
 1   model              11914 non-null  object
 2   year               11914 non-null  int64
 3   engine_fuel_type   11914 non-null  object
 4   engine_hp          11914 non-null  float64
 5   engine_cylinders   11914 non-null  float64
 6   transmission_type  11914 non-null  object
 7   driven_wheels      11914 non-null  object
 8   number_of_doors    11914 non-null  object
 9   market_category    9277 non-null   object
 10  vehicle_size       11914 non-null  object
 11  vehicle_style      11914 non-null  object
 12  highway_mpg        11914 non-null  int64
 13  city_mpg           11914 non-null  int64
 14  popularity         11914 non-null  int64
 15  msrp               11914 non-null  int64
 16  age                11914 non-null  int64
dtypes: float64(2), int64(6), object(9)
memory usage: 1.5+ MB

In [271]:
df['market_category'] = df['market_category'].fillna(0)

In [272]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score 
from sklearn.metrics import mean_squared_error

import matplotlib.pyplot as plt

In [273]:
model = LinearRegression()

In [274]:
dummies = pd.get_dummies(df)

C:\Users\Lakshmeesh s reddy\anaconda3\lib\site-packages\pandas\core\algorithms.py:798: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  uniques = Index(uniques)

In [275]:
dummies

,year,engine_hp,engine_cylinders,highway_mpg,city_mpg,popularity,msrp,age,make_acura,make_alfa_romeo,...,vehicle_style_convertible,vehicle_style_convertible_suv,vehicle_style_coupe,vehicle_style_crew_cab_pickup,vehicle_style_extended_cab_pickup,vehicle_style_passenger_minivan,vehicle_style_passenger_van,vehicle_style_regular_cab_pickup,vehicle_style_sedan,vehicle_style_wagon
0,2011,335.0,6.0,26,19,3916,46135,7,0,0,...,0,0,1,0,0,0,0,0,0,0
1,2011,300.0,6.0,28,19,3916,40650,7,0,0,...,1,0,0,0,0,0,0,0,0,0
2,2011,300.0,6.0,28,20,3916,36350,7,0,0,...,0,0,1,0,0,0,0,0,0,0
3,2011,230.0,6.0,28,18,3916,29450,7,0,0,...,0,0,1,0,0,0,0,0,0,0
4,2011,230.0,6.0,28,18,3916,34500,7,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,2012,300.0,6.0,23,16,204,46120,6,1,0,...,0,0,0,0,0,0,0,0,0,0
11910,2012,300.0,6.0,23,16,204,56670,6,1,0,...,0,0,0,0,0,0,0,0,0,0
11911,2012,300.0,6.0,23,16,204,50620,6,1,0,...,0,0,0,0,0,0,0,0,0,0
11912,2013,300.0,6.0,23,16,204,50920,5,1,0,...,0,0,0,0,0,0,0,0,0,0
11913,2006,221.0,6.0,26,17,61,28995,12,0,0,...,0,0,0,0,0,0,0,0,1,0

In [276]:
X = dummies.drop('msrp', axis = 'columns')

In [277]:
y = dummies['msrp']

In [278]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [279]:
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [280]:
model.fit(X_train, y_train)

LinearRegression()

In [281]:
model.intercept_

2.5925809336455562e+17

In [282]:
model.coef_

array([-2.92581907e+17,  1.12960000e+05,  2.04800000e+03, ...,
       -1.31368633e+15, -6.97844124e+14, -6.97844124e+14])

In [283]:
model.predict(X_train)

array([36576.,  7104., 37216., ..., 39200., 33152., 72704.])

In [284]:
model.fit(X_test, y_test)

LinearRegression()

In [285]:
model.intercept_

7.029869770044924e+17

In [286]:
model.coef_

array([-7.06724675e+17,  1.00992000e+05,  6.52800000e+03, ...,
       -2.28328460e+15,  1.02865372e+15,  1.02865372e+15])

In [287]:
model.coef_

array([-7.06724675e+17,  1.00992000e+05,  6.52800000e+03, ...,
       -2.28328460e+15,  1.02865372e+15,  1.02865372e+15])

In [288]:
model.score(X_test, y_test)

0.9889808637398257